(()=>{'use strict';
const VER='24.0.0', KEY='acqProV24', SNAP='acqProV24Snapshot', LOG='acqProV24Log';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const IDS=['netStatus','healthLine','installBtn','selfCheckBtn','mContacts','mConv','mNews','mAppt','mProps','goalsBox','newsBtn','goalsBtn','say','name','phone','address','source','note','outcome','nextAction','nextDate','zoneOpenBtn','hereBtn','manualZoneBtn','resumeBtn','nextZoneBtn','zoneBox','contactsBtn','reportBtn','backupBtn','sellerBtn','publicationBtn','reelBtn','portfolioBtn','portfolioWaBtn','deluxeBox','closeContactBtn','stopBtn','genericDialog','dialogTitle','dialogBody','dialogClose'];
const R={};IDS.forEach(id=>R[id]=$(id));
const {netStatus,healthLine,installBtn,selfCheckBtn,mContacts,mConv,mNews,mAppt,mProps,goalsBox,newsBtn,goalsBtn,say,name,phone,address,source,note,outcome,nextAction,nextDate,zoneOpenBtn,hereBtn,manualZoneBtn,resumeBtn,nextZoneBtn,zoneBox,contactsBtn,reportBtn,backupBtn,sellerBtn,publicationBtn,reelBtn,portfolioBtn,portfolioWaBtn,deluxeBox,closeContactBtn,stopBtn,genericDialog,dialogTitle,dialogBody,dialogClose}=R;
const defaults={version:VER,contacts:[],stats:{contacts:0,conversations:0,news:0,appointments:0,properties:0},goals:{conversations:100,news:20,appointments:5,properties:3},session:{active:false,situation:null},zones:[],zoneIndex:0,lastZone:null,events:[],seller:{docs:{},pq:{}},publication:null};
const S={
persona:{start:'Buongiorno, sono un agente immobiliare e sto lavorando in questa zona. Posso farle una domanda veloce? Sa se nel condominio o qui vicino qualcuno sta pensando di vendere casa?',si:'Grazie. Se conosce qualcuno che ne parla, può lasciargli il mio contatto. E lei ha mai fatto valutare il suo immobile recentemente?',no:'Nessun problema. Le lascio solo un riferimento per una valutazione futura.',nonsa:'Secondo lei in questa zona oggi le case si vendono facilmente oppure restano ferme?',fretta:'Le rubo dieci secondi: cerco immobili da acquisire in questa zona. Se sente qualcuno che pensa di vendere, posso lasciarle il mio contatto?',diffidente:'Non le sto chiedendo dati personali. Sto semplicemente lavorando sul mercato della zona e mi presento.',interessato:'Sta pensando di vendere presto, conoscere il valore oppure valutare più avanti?'},
cartello:{start:'Registra indirizzo e dati pubblici del cartello. Poi chiedi se vende direttamente o è già seguito da un’agenzia.',si:'Da quanto tempo è sul mercato e sta ottenendo le richieste che si aspettava?',no:'Non interferisco con rapporti in corso. Se in futuro desidera un secondo parere sul posizionamento, posso prepararlo.',nonsa:'Mi interessa capire chi gestisce la vendita, così evito contatti inutili.',fretta:'Le lascio il mio riferimento. Se vuole un confronto su prezzo o strategia, mi ricontatti.',diffidente:'Ho usato soltanto il riferimento pubblicato sul cartello.',interessato:'Posso preparare un’analisi sintetica: prezzo, concorrenza, tempi e criticità.'},
condominio:{start:'Buongiorno. Sono un agente immobiliare e sto lavorando proprio su questa microzona. Sa se nel condominio ci sono proprietari che stanno valutando una vendita?',si:'Può semplicemente dare loro il mio contatto, senza raccogliere dati di terzi.',no:'Posso lasciarle comunque un riferimento per una valutazione futura?',nonsa:'Lei sa quanto vale oggi un appartamento come il suo in questa zona?',fretta:'Solo dieci secondi: lavoro sulle vendite della zona e cerco immobili.',diffidente:'Non le chiedo dati personali. Sto solo facendo presidio commerciale della zona.',interessato:'Vuole conoscere il valore, sta pensando di vendere o vuole capire i tempi?'},
attivita:{start:'Buongiorno, lavoro nel settore immobiliare qui in zona. Le capita di sentire clienti parlare di case da vendere, trasferimenti o immobili vuoti?',si:'Se ricapita, può semplicemente dare il mio contatto.',no:'Le lascio comunque il contatto: magari domani entra qualcuno che dice “devo vendere casa”.',nonsa:'Nessun problema. Sto costruendo una rete locale.',fretta:'Le lascio solo il contatto: cerco immobili da acquisire in zona.',diffidente:'Nessuna richiesta di dati. Mi interessava solo presentarmi.',interessato:'Possiamo scambiarci i riferimenti e restare in contatto.'},
professionista:{start:'Quando un suo cliente le dice spontaneamente che deve vendere, vorrei essere una delle persone che può indicargli. Possiamo capire se ha senso collaborare?',si:'Io posso ricambiare indirizzando a lei clienti che hanno bisogno del suo servizio.',no:'Le lascio il mio riferimento, nel caso si presenti una situazione compatibile.',nonsa:'Possiamo partire senza impegni: scambiamoci i riferimenti.',fretta:'Le lascio il mio contatto. Cerco immobili e posso inviarle clienti pertinenti.',diffidente:'Non chiedo dati dei suoi clienti. Mi interessa essere un riferimento professionale.',interessato:'Quali tipi di clienti incontra più spesso?'},
telefono:{start:'Buongiorno, sono un agente immobiliare. La contatto per una ragione precisa collegata a un immobile o a una richiesta nella sua zona. Ha trenta secondi?',si:'Sta valutando una vendita, una semplice stima oppure al momento non è un tema?',no:'Va bene. Non la trattengo. Buona giornata.',nonsa:'Le dico il motivo del contatto in una frase e poi mi ferma lei se non è pertinente.',fretta:'Le lascio nome e ragione del contatto. Se vuole, ci risentiamo in un momento migliore.',diffidente:'Le chiarisco subito fonte e motivo del contatto; se non desidera proseguire, interrompiamo qui.',interessato:'Qual è la sua priorità: prezzo, tempi, discrezione oppure capire se esiste già domanda?'}
};
const DOCS=['Documento d’identità e codice fiscale dei proprietari','Titolo di provenienza / atto di acquisto','Visura catastale aggiornata','Planimetria catastale','APE','Documentazione urbanistica disponibile','Regolamento e situazione condominiale','Ultimi verbali e spese condominiali','Documentazione mutuo / ipoteche se presenti','Documenti successione o donazione se presenti','Contratto di locazione se occupato','Chiavi e riferimenti tecnici utili'];
const PQ=['Perché sta valutando la vendita?','Entro quando vorrebbe vendere?','Ha già individuato un’altra casa o una destinazione successiva?','Ci sono altri proprietari che devono decidere?','L’immobile è libero, occupato o locato?','Ha già ricevuto valutazioni o proposte?','Qual è la sua aspettativa di prezzo?','Ci sono mutui, ipoteche, successioni, donazioni o criticità note?','Quanto è disponibile a preparare l’immobile prima della vendita?','Come preferisce ricevere aggiornamenti e report?'];
const STRATEGY=['Controllo documentazione e criticità prima della commercializzazione','Analisi comparativa, microzona, concorrenza e strategia prezzo','Preparazione immobile: ordine, luce, piccoli interventi e home staging quando utile','Foto, video/Reel, planimetrie e testi commerciali','Piano di pubblicazione preciso con canali, date, stato e link reali','Database acquirenti, richiami e campagne previste','Open House quando adatto, promozione preventiva e follow-up','Prequalifica acquirenti: esigenza, tempi, budget e mutuo','Report proprietario: richieste, visite, feedback, obiezioni e azioni successive','Gestione proposta, condizioni, controproposte e negoziazione','Aggiornamento continuo della strategia fino alla vendita','Coordinamento documenti e scadenze fino al rogito'];
const PUB_DEFAULT=['Sito F1 Immobiliare','Immobiliare.it','Facebook F1 Immobiliare','Instagram F1 Immobiliare','Reel Facebook + Instagram','Gruppi Facebook locali','CRM acquirenti compatibili','WhatsApp contatti compatibili','Meta Ads geolocalizzata','Volantini microzona','Vetrina / materiale agenzia','Cartello immobile','Rete professionisti / segnalazioni','Open House'];
const LINKS={portfolio:'https://cdn.shopify.com/s/files/1/1046/2730/6835/files/Portfolio_Performance_Report_Joseph_Digital_Strategist_PREMIUM_FINALE_CON_FOTO_E_INVITO_v4.pdf?v=1787228245',deluxeVille:'https://cdn.shopify.com/s/files/1/1046/2730/6835/files/F1_Piano_Marketing_Deluxe_Ville_Villini.pdf?v=1787226181',deluxeSign:'https://cdn.shopify.com/s/files/1/1046/2730/6835/files/F1_Piano_Marketing_Deluxe_Appartamenti_Signorili.pdf?v=1787227485',reels:'https://josephsocialmedia2-spec.github.io/open-social-scheduler/monday-control.html',center:'https://josephsocialmedia2-spec.github.io/open-social-scheduler/content-center.html',scheduler:'https://josephsocialmedia2-spec.github.io/open-social-scheduler/',meta:'https://business.facebook.com/latest/home'};
let state=loadState(), installEvent=null;
function clone(x){return JSON.parse(JSON.stringify(x))}
function mergeState(base,x){const o=clone(base);if(!x||typeof x!=='object')return o;Object.assign(o,x);o.stats={...base.stats,...(x.stats||{})};o.goals={...base.goals,...(x.goals||{})};o.session={...base.session,...(x.session||{})};if(!Array.isArray(o.contacts))o.contacts=[];if(!Array.isArray(o.zones))o.zones=[];if(!Array.isArray(o.events))o.events=[];if(!o.seller)o.seller={docs:{},pq:{}};return o}
function migrateLegacy(s){try{const d=JSON.parse(localStorage.getItem('acqProMobile')||'null');if(d){if(!s.contacts.length&&Array.isArray(d.contacts))s.contacts=d.contacts;const st=d.stats||{};s.stats.contacts=Math.max(s.stats.contacts||0,st.c||0,s.contacts.length);s.stats.conversations=Math.max(s.stats.conversations||0,st.v||0);s.stats.appointments=Math.max(s.stats.appointments||0,st.a||0);s.stats.properties=Math.max(s.stats.properties||0,st.i||0)}}catch{}try{const p=JSON.parse(localStorage.getItem('f1Performance')||'null');if(p){s.stats.news=Math.max(s.stats.news||0,p.news||0);if(p.goals)s.goals={...s.goals,conversations:p.goals.v??s.goals.conversations,news:p.goals.news??s.goals.news,appointments:p.goals.a??s.goals.appointments,properties:p.goals.i??s.goals.properties}}}catch{}try{const z=JSON.parse(localStorage.getItem('f1VaiZonaTargets')||'null');if(!s.zones.length&&Array.isArray(z))s.zones=z}catch{}try{const l=JSON.parse(localStorage.getItem('f1LastZone')||'null');if(!s.lastZone&&l)s.lastZone=l}catch{}try{const p=JSON.parse(localStorage.getItem('acqPublicationPlan')||'null');if(!s.publication&&p)s.publication=p}catch{}try{const se=JSON.parse(localStorage.getItem('acqSeller')||'null');if(se&&Object.keys(s.seller.docs||{}).length===0)s.seller=se}catch{}return s}
function loadState(){try{let x=JSON.parse(localStorage.getItem(KEY)||'null');return migrateLegacy(mergeState(defaults,x))}catch{try{const snap=JSON.parse(localStorage.getItem(SNAP)||'null');if(snap?.state)return migrateLegacy(mergeState(defaults,snap.state))}catch{}return migrateLegacy(clone(defaults))}}
function compatWrite(){localStorage.setItem('acqProMobile',JSON.stringify({contacts:state.contacts,stats:{c:state.stats.contacts,v:state.stats.conversations,a:state.stats.appointments,i:state.stats.properties}}));localStorage.setItem('f1Performance',JSON.stringify({news:state.stats.news,goals:{v:state.goals.conversations,news:state.goals.news,a:state.goals.appointments,i:state.goals.properties}}));localStorage.setItem('f1VaiZonaTargets',JSON.stringify(state.zones));if(state.lastZone)localStorage.setItem('f1LastZone',JSON.stringify(state.lastZone));if(state.publication)localStorage.setItem('acqPublicationPlan',JSON.stringify(state.publication));localStorage.setItem('acqSeller',JSON.stringify(state.seller))}
function persist(reason='update'){try{state.version=VER;state.events.push({ts:new Date().toISOString(),type:reason});if(state.events.length>300)state.events=state.events.slice(-300);const raw=JSON.stringify(state);localStorage.setItem(KEY,raw);localStorage.setItem(SNAP,JSON.stringify({ts:new Date().toISOString(),state}));compatWrite();idbSave(raw).catch(()=>{});renderMetrics()}catch(e){logError('persist',e)}}
function logError(msg,extra){try{const a=JSON.parse(localStorage.getItem(LOG)||'[]');a.push({ts:new Date().toISOString(),msg,extra:String(extra||'')});while(a.length>100)a.shift();localStorage.setItem(LOG,JSON.stringify(a))}catch{}}
function openDB(){return new Promise((resolve,reject)=>{if(!('indexedDB'in window))return reject();const q=indexedDB.open('AcquisitoreProDB',1);q.onupgradeneeded=()=>q.result.createObjectStore('kv');q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)})}
async function idbSave(raw){const db=await openDB();return new Promise((res,rej)=>{const tx=db.transaction('kv','readwrite');tx.objectStore('kv').put(raw,'state');tx.oncomplete=()=>{db.close();res()};tx.onerror=()=>{db.close();rej(tx.error)}})}
function setNet(){netStatus.textContent=navigator.onLine?'ONLINE':'OFFLINE';netStatus.style.background=navigator.onLine?'#1f9d50':'#d63c34'}window.addEventListener('online',setNet);window.addEventListener('offline',setNet);
function setText(t){say.textContent=t}
function startSituation(k){if(!S[k])return;if(!state.session.active){state.stats.conversations++;state.session.active=true}state.session.situation=k;setText(S[k].start);persist('conversation-start')}
function answer(k){const s=S[state.session.situation];setText(s?.[k]||'Prima ascolta la risposta, poi registra le informazioni utili e la prossima azione.')}
function resetContact(){['name','phone','address','note','nextAction','nextDate'].forEach(id=>$(id).value='');source.value='Giro zona';outcome.value='Da richiamare';state.session={active:false,situation:null};setText('Contatto salvato. Scegli la prossima situazione.')}
function closeContact(){const c={id:'c'+Date.now(),name:name.value.trim(),phone:phone.value.trim(),address:address.value.trim(),source:source.value,note:note.value.trim(),outcome:outcome.value,next:nextAction.value.trim(),date:nextDate.value,ts:new Date().toISOString()};if(!c.name&&!c.phone&&!c.address&&!c.note&&!state.session.active){setText('Nessun contatto in corso. Inserisci almeno un dato o avvia una conversazione.');return}state.contacts.unshift(c);state.stats.contacts++;if(['Appuntamento','Valutazione'].includes(c.outcome))state.stats.appointments++;if(['Nuovo immobile','Possibile vendita'].includes(c.outcome))state.stats.properties++;persist('contact-close');resetContact();renderContactsIfOpen()}
function renderMetrics(){const s=state.stats;mContacts.textContent=s.contacts;mConv.textContent=s.conversations;mNews.textContent=s.news;mAppt.textContent=s.appointments;mProps.textContent=s.properties;const items=[['Conversazioni',s.conversations,state.goals.conversations],['Notizie',s.news,state.goals.news],['Appuntamenti',s.appointments,state.goals.appointments],['Immobili',s.properties,state.goals.properties]];const all=items.every(x=>x[1]>=x[2]);goalsBox.innerHTML=(all?'<div class="goal won">🏆 TUTTI I TRAGUARDI SUPERATI</div>':'')+items.map(([n,v,g])=>{const pct=g?Math.min(100,Math.round(v/g*100)):100;return `<div class="goal ${v>=g?'won':''}">${v>=g?'🏆 ':''}<b>${n}</b>: ${v}/${g} — ${v>=g?'TRAGUARDO SUPERATO':'ti mancano ancora '+Math.max(0,g-v)}<div class="progress"><i style="width:${pct}%"></i></div></div>`}).join('')}
function setGoals(){const g=state.goals;const q=(label,v)=>{const x=prompt(label,String(v));return x===null?null:Math.max(0,parseInt(x,10)||0)};const a=q('Traguardo conversazioni',g.conversations);if(a===null)return;const b=q('Traguardo notizie prese',g.news);if(b===null)return;const c=q('Traguardo appuntamenti',g.appointments);if(c===null)return;const d=q('Traguardo immobili',g.properties);if(d===null)return;state.goals={conversations:a,news:b,appointments:c,properties:d};persist('goals')}
function showDialog(title,html){dialogTitle.textContent=title;dialogBody.innerHTML=html;genericDialog.showModal()}
function zoneCurrent(){if(!state.zones.length)return null;if(state.zoneIndex>=state.zones.length)state.zoneIndex=0;return state.zones[state.zoneIndex]}
function renderZone(){const x=zoneCurrent();zoneBox.innerHTML=x?`<b>${esc(x.paese||'Zona')} — ${esc(x.via||'Via')} ${esc(x.civico||'')}</b><br><span class="pill">${esc(x.segnale||'Giro zona')}</span><br>COSA CERCARE: ${esc(x.cosa||'Presidio / acquisizione')}<br>PREZZO: ${esc(x.prezzo||'—')}<br><span class="small">${state.zoneIndex+1} di ${state.zones.length}</span>`:'Nessuna destinazione salvata. Usa SONO QUI o INSERISCI VIA E CIVICO.'}
function zoneForm(prefill={}){showDialog('DESTINAZIONE',`<div class="fields"><input id="zPaese" placeholder="Paese / zona" value="${esc(prefill.paese||'')}"><input id="zVia" placeholder="Via" value="${esc(prefill.via||'')}"><input id="zCivico" placeholder="Numero civico" value="${esc(prefill.civico||'')}"><input id="zCosa" placeholder="Cosa cercare" value="${esc(prefill.cosa||'')}"><input id="zPrezzo" placeholder="Prezzo" value="${esc(prefill.prezzo||'')}"><input id="zSegnale" placeholder="Segnale" value="${esc(prefill.segnale||'')}"><button id="zSave" class="btn green">SALVA VIA / CIVICO</button><div id="zGeoInfo" class="small"></div></div>`);$('zSave').onclick=()=>{const x={paese:$('zPaese').value.trim(),via:$('zVia').value.trim(),civico:$('zCivico').value.trim(),cosa:$('zCosa').value.trim(),prezzo:$('zPrezzo').value.trim(),segnale:$('zSegnale').value.trim(),lat:prefill.lat??null,lon:prefill.lon??null};if(!x.via){$('zGeoInfo').textContent='Inserisci almeno la via.';return}state.zones.push(x);state.zoneIndex=state.zones.length-1;state.lastZone={...x,savedAt:new Date().toISOString()};persist('zone-save');genericDialog.close();renderZone()}}
function geoPosition(options){return new Promise((res,rej)=>navigator.geolocation.getCurrentPosition(res,rej,options))}
async function reverseGeocode(lat,lon){const ctl=new AbortController(),t=setTimeout(()=>ctl.abort(),3000);try{const u=`https://nominatim.openstreetmap.org/reverse?format=jsonv2&lat=${encodeURIComponent(lat)}&lon=${encodeURIComponent(lon)}&zoom=18&addressdetails=1&accept-language=it`;const r=await fetch(u,{signal:ctl.signal,headers:{Accept:'application/json'}});if(!r.ok)throw Error('http');const d=await r.json(),a=d.address||{};return{paese:a.city||a.town||a.village||a.municipality||a.hamlet||'',via:a.road||a.pedestrian||a.residential||a.path||'',civico:a.house_number||''}}finally{clearTimeout(t)}}
async function here(){if(!navigator.geolocation){zoneForm({});return}hereBtn.disabled=true;hereBtn.textContent='📍 RILEVO POSIZIONE…';try{let p;try{p=await geoPosition({enableHighAccuracy:false,timeout:4000,maximumAge:120000})}catch{p=await geoPosition({enableHighAccuracy:false,timeout:2200,maximumAge:900000})}const base={lat:p.coords.latitude,lon:p.coords.longitude,accuracy:Math.round(p.coords.accuracy||0)};zoneForm(base);const info=$('zGeoInfo');if(info)info.textContent='Coordinate rilevate'+(base.accuracy?' · precisione circa '+base.accuracy+' m':'')+'. Cerco via e civico senza bloccare la scheda…';reverseGeocode(base.lat,base.lon).then(x=>{if($('zPaese')&&!$('zPaese').value)$('zPaese').value=x.paese;if($('zVia')&&!$('zVia').value)$('zVia').value=x.via;if($('zCivico')&&!$('zCivico').value)$('zCivico').value=x.civico;if($('zGeoInfo'))$('zGeoInfo').textContent='Indirizzo compilato. Verifica e salva.'}).catch(()=>{if($('zGeoInfo'))$('zGeoInfo').textContent='Coordinate trovate; indirizzo automatico non disponibile. Inserisci via/civico e salva.'})}catch{zoneForm({});if($('zGeoInfo'))$('zGeoInfo').textContent='Posizione non disponibile in pochi secondi. Inserisci via/civico manualmente.'}finally{hereBtn.disabled=false;hereBtn.textContent='📍 SONO QUI — VIA / CIVICO / ZONA'}}
async function nearbyRoads(x){const ctl=new AbortController(),t=setTimeout(()=>ctl.abort(),4500);try{const q=`[out:json];way(around:350,${x.lat},${x.lon})[highway][name];out tags;`;const r=await fetch('https://overpass-api.de/api/interpreter',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded;charset=UTF-8'},body:'data='+encodeURIComponent(q),signal:ctl.signal});if(!r.ok)throw Error('http');const d=await r.json();return [...new Set((d.elements||[]).map(e=>e.tags?.name).filter(Boolean))].slice(0,12)}finally{clearTimeout(t)}}
async function resumeYesterday(){const x=state.lastZone;if(!x){zoneBox.textContent='Nessun punto precedente salvato.';return}if(!x.lat||!x.lon){state.zones.push({...x});state.zoneIndex=state.zones.length-1;renderZone();zoneBox.innerHTML+=`<br><span class="small">Ultimo punto recuperato. Per cercare vie adiacenti usa SONO QUI quando sei sul posto.</span>`;return}zoneBox.textContent='Cerco vie adiacenti…';try{const names=await nearbyRoads(x),seen=new Set(state.zones.map(z=>z.via));names.filter(v=>v!==x.via&&!seen.has(v)).forEach(v=>state.zones.push({paese:x.paese||'',via:v,civico:'',cosa:'Presidio / acquisizione',prezzo:'',segnale:'Via adiacente',lat:x.lat,lon:x.lon}));state.zoneIndex=Math.max(0,state.zones.findIndex(z=>z.via===x.via)+1);persist('resume-zone');renderZone()}catch{renderZone();zoneBox.innerHTML+=`<br><span class="small">Servizio vie vicine non disponibile ora. Le destinazioni già salvate restano utilizzabili.</span>`}}
function contactsHtml(){if(!state.contacts.length)return '<p>Nessun contatto salvato.</p>';return `<div class="list">${state.contacts.slice(0,200).map(c=>`<div class="row"><b>${esc(c.name||'Senza nome')}</b>${esc(c.address||'')}<br>${c.phone?`<a href="tel:${esc(c.phone)}">${esc(c.phone)}</a> · <a href="https://wa.me/${String(c.phone).replace(/\D/g,'')}" target="_blank">WhatsApp</a><br>`:''}<span class="pill">${esc(c.outcome)}</span><span class="pill">${esc(c.source)}</span><br><span class="small">${esc(c.note||'')} ${c.next?'· Prossima: '+esc(c.next):''}</span></div>`).join('')}</div>`}
function renderContactsIfOpen(){if(genericDialog.open&&dialogTitle.textContent==='CONTATTI SALVATI')dialogBody.innerHTML=contactsHtml()}
function download(name,mime,text){const b=new Blob([text],{type:mime}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
function csv(){const rows=[['Data','Nome','Telefono','Indirizzo','Fonte','Esito','Nota','Prossima azione','Data richiamo'],...state.contacts.map(c=>[c.ts,c.name,c.phone,c.address,c.source,c.outcome,c.note,c.next,c.date])];return rows.map(r=>r.map(v=>'"'+String(v??'').replaceAll('"','""')+'"').join(',')).join('\n')}
function reportDialog(){showDialog('REPORT E DOWNLOAD',`<p><b>Contatti:</b> ${state.stats.contacts} · <b>Conversazioni:</b> ${state.stats.conversations} · <b>Notizie:</b> ${state.stats.news} · <b>Appuntamenti:</b> ${state.stats.appointments} · <b>Immobili:</b> ${state.stats.properties}</p><div class="toolbar"><button id="reportJson" class="btn blue">SCARICA REPORT JSON</button><button id="reportCsv" class="btn green">SCARICA CONTATTI CSV</button></div>`);$('reportJson').onclick=()=>download('Acquisitore_Pro_Report_'+new Date().toISOString().slice(0,10)+'.json','application/json',JSON.stringify({generatedAt:new Date().toISOString(),version:VER,stats:state.stats,goals:state.goals,lastZone:state.lastZone,zones:state.zones,contacts:state.contacts,publication:state.publication},null,2));$('reportCsv').onclick=()=>download('Acquisitore_Pro_Contatti_'+new Date().toISOString().slice(0,10)+'.csv','text/csv;charset=utf-8',csv())}
function backupDialog(){showDialog('BACKUP / RIPRISTINO',`<p>Salva tutti i dati locali dell’app. Il ripristino non richiede un server.</p><div class="toolbar"><button id="bkDown" class="btn green">⬇ SCARICA BACKUP</button><label class="btn blue" style="text-align:center">↩ SCEGLI BACKUP<input id="bkFile" type="file" accept=".json,application/json" hidden></label></div><div id="bkInfo" class="small"></div>`);$('bkDown').onclick=()=>download('Acquisitore_Pro_BACKUP_'+new Date().toISOString().slice(0,10)+'.json','application/json',JSON.stringify({app:'Acquisitore Pro',version:VER,createdAt:new Date().toISOString(),state},null,2));$('bkFile').onchange=async e=>{try{const f=e.target.files[0],o=JSON.parse(await f.text());if(o.app!=='Acquisitore Pro'||!o.state)throw Error();state=mergeState(defaults,o.state);persist('restore-backup');$('bkInfo').textContent='Backup ripristinato.';renderAll()}catch{$('bkInfo').textContent='Backup non valido. Nessun dato modificato.'}}}
function sellerDialog(){const docs=DOCS.map((d,i)=>`<label class="row"><input type="checkbox" data-doc="${i}" ${state.seller.docs?.[i]?'checked':''}> ${esc(d)}</label>`).join('');const pq=PQ.map((q,i)=>`<div class="row"><b>${i+1}. ${esc(q)}</b><textarea data-pq="${i}" style="width:100%;min-height:55px">${esc(state.seller.pq?.[i]||'')}</textarea></div>`).join('');const str=STRATEGY.map((s,i)=>`<div class="row"><b>${i+1}. ${esc(s)}</b></div>`).join('');showDialog('DOCUMENTI / PREQUALIFICA / STRATEGIA',`<details open><summary>📑 LISTA DOCUMENTI</summary>${docs}</details><details><summary>🧭 PREQUALIFICA</summary>${pq}</details><details><summary>📈 STRATEGIA DI VENDITA</summary>${str}</details><div class="toolbar"><button id="sellerSave" class="btn green">SALVA</button><button id="sellerPub" class="btn blue">PIANO PUBBLICAZIONE</button></div>`);$('sellerSave').onclick=()=>{state.seller.docs={};dialogBody.querySelectorAll('[data-doc]').forEach(x=>state.seller.docs[x.dataset.doc]=x.checked);state.seller.pq={};dialogBody.querySelectorAll('[data-pq]').forEach(x=>state.seller.pq[x.dataset.pq]=x.value);persist('seller-save');genericDialog.close()};$('sellerPub').onclick=publicationDialog}
function publicationData(){if(state.publication?.channels)return state.publication;return {property:'',address:'',channels:PUB_DEFAULT.map((name,i)=>({id:i,name,planned:![11,13].includes(i),date:'',status:'DA PROGRAMMARE',url:''}))}}
function publicationDialog(){state.publication=publicationData();const p=state.publication;showDialog('PIANO PUBBLICAZIONE',`<div class="fields"><input id="pProp" placeholder="Immobile" value="${esc(p.property||'')}"><input id="pAddr" placeholder="Indirizzo" value="${esc(p.address||'')}"></div><div class="list">${p.channels.map((c,i)=>`<div class="row"><label><input type="checkbox" data-pp="${i}" ${c.planned?'checked':''}> <b>${esc(c.name)}</b></label><div class="grid3"><input data-pdate="${i}" type="date" value="${esc(c.date||'')}"><select data-pstatus="${i}"><option ${c.status==='DA PROGRAMMARE'?'selected':''}>DA PROGRAMMARE</option><option ${c.status==='PROGRAMMATO'?'selected':''}>PROGRAMMATO</option><option ${c.status==='PUBBLICATO'?'selected':''}>PUBBLICATO</option><option ${c.status==='AGGIORNATO'?'selected':''}>AGGIORNATO</option></select><input data-purl="${i}" placeholder="Link reale" value="${esc(c.url||'')}"></div></div>`).join('')}</div><button id="pSave" class="btn green">SALVA PIANO</button>`);$('pSave').onclick=()=>{p.property=$('pProp').value;p.address=$('pAddr').value;p.channels.forEach((c,i)=>{c.planned=dialogBody.querySelector(`[data-pp="${i}"]`).checked;c.date=dialogBody.querySelector(`[data-pdate="${i}"]`).value;c.status=dialogBody.querySelector(`[data-pstatus="${i}"]`).value;c.url=dialogBody.querySelector(`[data-purl="${i}"]`).value});persist('publication-save');genericDialog.close()}}
function reelDialog(){showDialog('REEL SOCIAL',`<p>Flusso: anteprima → verifica contenuto approvato → pubblicazione / programmazione.</p><div class="toolbar"><a class="btn green" href="${LINKS.reels}" target="_blank">▶ REEL PRONTI</a><a class="btn blue" href="${LINKS.center}" target="_blank">📅 CENTRO SOCIAL</a><a class="btn" href="${LINKS.meta}" target="_blank">📘 META BUSINESS SUITE</a><a class="btn" href="${LINKS.scheduler}" target="_blank">⏱ OPEN SOCIAL SCHEDULER</a></div><p class="small">Non pubblicare due volte lo stesso contenuto. Segui contenuto e orario indicati nel Centro Social.</p>`)}
function deluxe(){const rows=[['VILLE & VILLINI',LINKS.deluxeVille],['APPARTAMENTI SIGNORILI',LINKS.deluxeSign]];deluxeBox.innerHTML=rows.map(([n,u])=>`<div class="row"><b>${n}</b><div class="toolbar"><button class="btn" onclick="window.open('${u}','_blank','noopener')">📄 APRI PDF</button><button class="btn green" onclick="window.open('https://wa.me/?text='+encodeURIComponent('Buongiorno, come concordato le invio il Piano Marketing Deluxe F1.\\n\\n${u}\\n\\nF1 Immobiliare'),'_blank','noopener')">🟢 WHATSAPP</button></div></div>`).join('')}
function selfCheck(){const checks={dom:!!name&&!!closeContactBtn,storage:false,secure:window.isSecureContext,geo:'geolocation'in navigator,sw:'serviceWorker'in navigator,idb:'indexedDB'in window,state:Array.isArray(state.contacts)&&Array.isArray(state.zones)};try{localStorage.setItem('__acq_test','1');checks.storage=localStorage.getItem('__acq_test')==='1';localStorage.removeItem('__acq_test')}catch{}const failed=Object.entries(checks).filter(([,v])=>!v).map(([k])=>k);healthLine.textContent=failed.length?'ATTENZIONE: '+failed.join(', '):'AUTODIAGNOSI LOCALE OK · dati preservati · versione '+VER;healthLine.style.color=failed.length?'#9b2d25':'#176233';return checks}
function renderAll(){renderMetrics();renderZone();setNet();deluxe();selfCheck()}
window.addEventListener('error',e=>logError(e.message,e.filename+':'+e.lineno));window.addEventListener('unhandledrejection',e=>logError('promise',e.reason));
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();installEvent=e;installBtn.classList.remove('hidden')});installBtn.onclick=async()=>{if(!installEvent)return;installEvent.prompt();await installEvent.userChoice;installEvent=null;installBtn.classList.add('hidden')};
document.querySelectorAll('[data-situation]').forEach(b=>b.onclick=()=>startSituation(b.dataset.situation));document.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(b.dataset.answer));
closeContactBtn.onclick=closeContact;stopBtn.onclick=()=>{persist('stop');setText('Lavoro salvato. Puoi chiudere l’app.')};newsBtn.onclick=()=>{state.stats.news++;persist('news')};goalsBtn.onclick=setGoals;zoneOpenBtn.onclick=renderZone;hereBtn.onclick=here;manualZoneBtn.onclick=()=>zoneForm({});resumeBtn.onclick=resumeYesterday;nextZoneBtn.onclick=()=>{if(state.zones.length){state.zoneIndex=(state.zoneIndex+1)%state.zones.length;persist('zone-next');renderZone()}};
contactsBtn.onclick=()=>showDialog('CONTATTI SALVATI',contactsHtml());reportBtn.onclick=reportDialog;backupBtn.onclick=backupDialog;sellerBtn.onclick=sellerDialog;publicationBtn.onclick=publicationDialog;reelBtn.onclick=reelDialog;selfCheckBtn.onclick=selfCheck;dialogClose.onclick=()=>genericDialog.close();
portfolioBtn.onclick=()=>window.open(LINKS.portfolio,'_blank','noopener');portfolioWaBtn.onclick=()=>window.open('https://wa.me/?text='+encodeURIComponent('Buongiorno, le invio il Portfolio Performance Report.\n\n'+LINKS.portfolio),'_blank','noopener');
renderAll();persist('boot');
})();