(()=>{
'use strict';
if(window.__ACQ_CORE_LOADER__)return;window.__ACQ_CORE_LOADER__=true;
const VER='22.1.0',LOG='acqDiagLog',SNAP='acqLastGoodSnapshot',FAIL='acqBootFailures';
const REQUIRED=[['acquisizione-vai-qui-addon.js',()=>!!document.getElementById('acquisizioneVaiQuiButton')],['performance-addon.js',()=>!!document.getElementById('perfCard')],['chiudi-contatto-addon.js',()=>typeof window.closeContact==='function'],['backup-addon.js',()=>!!document.getElementById('backupDataButton')]];
const OPTIONAL=['piano-pubblicazione-addon.js','strategia-dettagli-addon.js','piano-deluxe-whatsapp-addon.js','reel-social-addon.js','digital-strategist-addon.js'];
const DATA_KEYS=['acqProMobile','acqSeller','acqPublicationPlan','f1VaiZonaTargets','f1LastZone','f1Performance'];
function diag(type,msg,extra){try{const a=JSON.parse(localStorage.getItem(LOG)||'[]');a.push({ts:new Date().toISOString(),type,msg,extra:extra||null,ver:VER});while(a.length>150)a.shift();localStorage.setItem(LOG,JSON.stringify(a))}catch{}}
function normalize(){const s=document.getElementById('source');if(!s)return;const m={Referral:'Segnalazione',Partner:'Professionista / collaboratore',Inbound:'Persona che ci ha contattato'};[...s.options].forEach(o=>{const t=o.textContent.trim();if(m[t]){o.textContent=m[t];o.value=m[t]}});if(m[s.value])s.value=m[s.value]}
function validData(){try{const r=localStorage.getItem('acqProMobile');if(!r)return true;const d=JSON.parse(r);return d&&Array.isArray(d.contacts)&&d.stats&&typeof d.stats==='object'}catch{return false}}
function snapshot(){try{if(!validData())return;const data={};DATA_KEYS.forEach(k=>data[k]=localStorage.getItem(k));localStorage.setItem(SNAP,JSON.stringify({ts:new Date().toISOString(),data}));diag('snapshot','Snapshot valido creato')}catch(e){diag('error','Snapshot fallito',String(e))}}
function restore(){try{const s=JSON.parse(localStorage.getItem(SNAP)||'null');if(!s?.data)return false;Object.entries(s.data).forEach(([k,v])=>v===null?localStorage.removeItem(k):localStorage.setItem(k,v));diag('repair','Snapshot ripristinato');return true}catch(e){diag('error','Ripristino fallito',String(e));return false}}
function health(){if(!validData()){diag('error','Dati principali corrotti');restore()}try{const n=Object.keys(localStorage).reduce((t,k)=>t+(localStorage.getItem(k)||'').length,0);if(n>3500000)diag('warn','Archivio locale grande',{chars:n})}catch{}}
function load(file,attempt=0,timeout=4500){return new Promise((resolve,reject)=>{const existing=[...document.scripts].find(s=>s.dataset.acqAddon===file);if(existing&&attempt===0){resolve();return}const s=document.createElement('script');let done=false;const timer=setTimeout(()=>{if(done)return;done=true;s.remove();reject(new Error('timeout '+file))},timeout);s.src='./'+file+'?v=22&a='+attempt+'&t='+Date.now();s.async=true;s.dataset.acqAddon=file;s.onload=()=>{if(done)return;done=true;clearTimeout(timer);resolve()};s.onerror=()=>{if(done)return;done=true;clearTimeout(timer);s.remove();reject(new Error('load '+file))};document.body.appendChild(s)})}
async function ensure(file,test,required){for(let i=0;i<2;i++){try{if(test?.())return true;await load(file,i);await new Promise(r=>setTimeout(r,50));if(!test||test()){diag('module','OK '+file);return true}}catch(e){diag('warn','Errore modulo '+file,{attempt:i+1,error:String(e)})}}if(required)diag('error','Modulo obbligatorio assente '+file);return false}
function safe(){document.documentElement.dataset.acqSafeMode='1';if(!document.getElementById('acqSafeModeNotice')){const b=document.createElement('div');b.id='acqSafeModeNotice';b.style.cssText='position:sticky;top:0;z-index:9999;padding:8px;background:#fff3cd;color:#6b5300;text-align:center;font:700 12px Arial';b.textContent='MODALITÀ SICURA — core operativo, dati preservati';document.body.prepend(b)}diag('repair','Modalità sicura attivata')}
function check(){normalize();const opts=[...document.querySelectorAll('#source option')].map(o=>o.textContent.trim());const c={core:typeof window.start==='function'&&typeof window.ans==='function',contact:!!document.getElementById('name')&&!!document.getElementById('phone')&&!!document.getElementById('address'),sources:!opts.some(x=>['Referral','Partner','Inbound'].includes(x)),close:typeof window.closeContact==='function',zone:!!document.getElementById('acquisizioneVaiQuiButton'),geo:!!document.getElementById('sonoQuiButton'),resume:!!document.getElementById('riprendiDaIeri'),manualAddress:!!document.getElementById('inserisciViaCivico'),performance:!!document.getElementById('perfCard'),news:!!document.getElementById('newsBtn'),goals:!!document.getElementById('goalBtn'),backup:!!document.getElementById('backupDataButton')};const fail=Object.entries(c).filter(([,v])=>!v).map(([k])=>k);diag(fail.length?'warn':'ok','Autodiagnosi',{checks:c,fail});return{checks:c,fail}}
function failCount(){const n=(+localStorage.getItem(FAIL)||0)+1;localStorage.setItem(FAIL,String(n));if(n>=4)safe()}
window.addEventListener('error',e=>{diag('js-error',e.message,{src:e.filename,line:e.lineno});failCount()});window.addEventListener('unhandledrejection',e=>{diag('promise-error',String(e.reason));failCount()});
async function boot(){normalize();health();setTimeout(snapshot,400);for(const [f,t] of REQUIRED)await ensure(f,t,true);for(const f of OPTIONAL)ensure(f,null,false);normalize();const r=check();if(r.fail.some(x=>['core','contact','close','zone'].includes(x)))safe();else localStorage.setItem(FAIL,'0');snapshot();window.__ACQ_READY__=true;window.dispatchEvent(new CustomEvent('acquisitorepro:ready',{detail:r}))}
window.AcqDiagnostics={version:VER,run:check,log:()=>JSON.parse(localStorage.getItem(LOG)||'[]'),snapshot,restore,safe};
if(document.readyState==='complete')setTimeout(boot,0);else window.addEventListener('load',()=>setTimeout(boot,0),{once:true});
})();