(()=>{'use strict';
const state={step:1,me:null,team:[],tours:[],staffId:'',comune:'',zona:'',via:'',start:'',sequence:[],busy:false};
const $=id=>document.getElementById(id),txt=v=>String(v??'').trim(),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const labels=['FUNZIONARIO','COMUNE','ZONA','VIA','PARTENZA','CIVICI'];
function setMsg(text,bad=false){const e=$('msg');e.textContent=text||'';e.className='msg'+(text?' show '+(bad?'bad':'ok'):'')}
function parseSeq(raw){const out=[],seen=new Set();String(raw||'').split(/[;,\n\s]+/).map(txt).filter(Boolean).forEach(x=>{if(!seen.has(x)){seen.add(x);out.push(x)}});return out}
function selectedStaff(){return state.team.find(x=>String(x.user_id)===String(state.staffId))||null}
function panelHtml(){
  const staff=selectedStaff();
  return [
`<div class="panel ${state.step===1?'on':''}" data-step="1"><h2>A CHI ASSEGNI QUESTO GIRO?</h2><p>Scegli un funzionario attivo.</p><div class="staff-list">${state.team.length?state.team.map(s=>`<label class="staff-card ${String(s.user_id)===String(state.staffId)?'selected':''}"><input type="radio" name="staff" value="${esc(s.user_id)}" ${String(s.user_id)===String(state.staffId)?'checked':''}><div class="staff-copy"><strong>${esc([s.first_name,s.last_name].filter(Boolean).join(' ')||s.role)}</strong><small>${esc(s.role||'FUNZIONARIO')}${s.assigned_territory?.via?' · '+esc(s.assigned_territory.via):''}</small></div></label>`).join(''):'<div class="empty">NESSUN FUNZIONARIO DISPONIBILE</div>'}</div></div>`,
`<div class="panel ${state.step===2?'on':''}" data-step="2"><h2>IN QUALE COMUNE DEVE LAVORARE?</h2><p>Il Comune è obbligatorio.</p><label>COMUNE<input id="comune" value="${esc(state.comune)}" autocomplete="address-level2" placeholder="Es. Avigliana"></label></div>`,
`<div class="panel ${state.step===3?'on':''}" data-step="3"><h2>VUOI SPECIFICARE UNA ZONA?</h2><p>Zona o microzona è facoltativa.</p><label>ZONA / MICROZONA<input id="zona" value="${esc(state.zona)}" placeholder="Es. Zona A"></label></div>`,
`<div class="panel ${state.step===4?'on':''}" data-step="4"><h2>QUALE STRADA DEVE LAVORARE?</h2><p>Inserisci la via reale da assegnare.</p><label>VIA<input id="via" value="${esc(state.via)}" autocomplete="street-address" placeholder="Es. Via Felice Goffi"></label></div>`,
`<div class="panel ${state.step===5?'on':''}" data-step="5"><h2>DA QUALE CIVICO DEVE PARTIRE?</h2><p>Il primo civico deve coincidere con il primo elemento della sequenza.</p><label>PRIMO CIVICO<input id="start" value="${esc(state.start)}" inputmode="numeric" placeholder="Es. 1"></label></div>`,
`<div class="panel ${state.step===6?'on':''}" data-step="6"><h2>IN QUALE ORDINE DEVE LAVORARE I CIVICI?</h2><p>La sequenza è esplicita: F1 non inventa il civico successivo.</p><label>SEQUENZA CIVICI<textarea id="sequence" placeholder="1, 3, 5, 7, 9">${esc(state.sequence.join(', '))}</textarea></label><div class="helpers"><button class="btn secondary" id="oddBtn" type="button">GENERA DISPARI</button><button class="btn secondary" id="evenBtn" type="button">GENERA PARI</button></div><div class="sequence-preview" id="seqPreview"></div><div class="summary" id="summary"><div><span>FUNZIONARIO</span><strong>${esc(staff?[staff.first_name,staff.last_name].filter(Boolean).join(' '):'—')}</strong></div><div><span>COMUNE</span><strong>${esc(state.comune||'—')}</strong></div><div><span>ZONA</span><strong>${esc(state.zona||'—')}</strong></div><div><span>VIA</span><strong>${esc(state.via||'—')}</strong></div><div><span>PARTENZA</span><strong>${esc(state.sequence[0]||state.start||'—')}</strong></div><div><span>CIVICI</span><strong>${esc(state.sequence.join(' → ')||'—')}</strong></div><div><span>TOTALE</span><strong>${state.sequence.length}</strong></div></div></div>`
  ].join('');
}
function renderSteps(){$('steps').innerHTML=labels.map((l,i)=>`<div class="step ${state.step===i+1?'on':''}">${i+1}. ${l}</div>`).join('')}
function syncInputs(){const map={comune:'comune',zona:'zona',via:'via',start:'start'};for(const [id,key] of Object.entries(map)){const e=$(id);if(e)e.addEventListener('input',()=>{state[key]=e.value})}document.querySelectorAll('input[name="staff"]').forEach(r=>r.addEventListener('change',()=>{state.staffId=r.value;render()}));const s=$('sequence');if(s)s.addEventListener('input',()=>{state.sequence=parseSeq(s.value);if(!state.start&&state.sequence[0])state.start=state.sequence[0];renderPreview()});$('oddBtn')?.addEventListener('click',()=>generateParity(1));$('evenBtn')?.addEventListener('click',()=>generateParity(0))}
function renderPreview(){const p=$('seqPreview');if(p)p.innerHTML=state.sequence.map(x=>`<span class="civic">${esc(x)}</span>`).join('')||'<span style="color:#68736b">Nessun civico inserito.</span>';const s=$('summary');if(s&&state.step===6){const staff=selectedStaff();s.innerHTML=`<div><span>FUNZIONARIO</span><strong>${esc(staff?[staff.first_name,staff.last_name].filter(Boolean).join(' '):'—')}</strong></div><div><span>COMUNE</span><strong>${esc(state.comune||'—')}</strong></div><div><span>ZONA</span><strong>${esc(state.zona||'—')}</strong></div><div><span>VIA</span><strong>${esc(state.via||'—')}</strong></div><div><span>PARTENZA</span><strong>${esc(state.sequence[0]||state.start||'—')}</strong></div><div><span>CIVICI</span><strong>${esc(state.sequence.join(' → ')||'—')}</strong></div><div><span>TOTALE</span><strong>${state.sequence.length}</strong></div>`}}
function render(){renderSteps();$('panels').innerHTML=panelHtml()+`<div class="nav"><button class="btn secondary" id="back" type="button" ${state.step===1?'disabled':''}><i class="fa-solid fa-arrow-left"></i> INDIETRO</button>${state.step<6?'<button class="btn primary" id="next" type="button">AVANTI <i class="fa-solid fa-arrow-right"></i></button>':'<button class="btn primary" id="assign" type="button">ASSEGNA GIRO <i class="fa-solid fa-check"></i></button>'}</div>`;syncInputs();renderPreview();$('back')?.addEventListener('click',()=>{capture();if(state.step>1){state.step--;setMsg('');render()}});$('next')?.addEventListener('click',()=>{capture();const err=validateStep(state.step);if(err){setMsg(err,true);return}state.step++;setMsg('');render()});$('assign')?.addEventListener('click',assignTour)}
function capture(){if($('comune'))state.comune=$('comune').value;if($('zona'))state.zona=$('zona').value;if($('via'))state.via=$('via').value;if($('start'))state.start=$('start').value;if($('sequence'))state.sequence=parseSeq($('sequence').value)}
function validateStep(step){if(step===1&&!state.staffId)return'SELEZIONA UN FUNZIONARIO';if(step===2&&!txt(state.comune))return'INSERISCI IL COMUNE';if(step===4&&!txt(state.via))return'INSERISCI LA VIA';if(step===5&&!txt(state.start))return'INSERISCI IL PRIMO CIVICO';if(step===6){if(!state.sequence.length)return'INSERISCI ALMENO UN CIVICO';if(txt(state.start)&&txt(state.sequence[0])!==txt(state.start))return'IL PRIMO CIVICO DEVE COINCIDERE CON IL PRIMO ELEMENTO DELLA SEQUENZA'}return''}
function generateParity(parity){capture();const startN=parseInt(state.start,10);const endRaw=prompt('CIVICO FINALE');const endN=parseInt(endRaw,10);if(!Number.isFinite(startN)||!Number.isFinite(endN)||endN<startN){setMsg('INDICA UN CIVICO INIZIALE E FINALE VALIDI',true);return}const seq=[];for(let n=startN;n<=endN;n++)if(Math.abs(n)%2===parity)seq.push(String(n));if(!seq.length){setMsg('NESSUN CIVICO GENERATO CON QUESTI LIMITI',true);return}state.sequence=seq;state.start=seq[0];render()}
async function assignTour(){capture();const err=validateStep(6);if(err){setMsg(err,true);return}if(state.busy)return;state.busy=true;$('assign').disabled=true;setMsg('SALVATAGGIO GIRO IN CORSO…');try{const r=await F1StaffData.rpc('f1_territory_assign_tour',{p_user_id:state.staffId,p_comune:txt(state.comune),p_zona:txt(state.zona),p_via:txt(state.via),p_street_segment:'',p_civics:state.sequence});if(!r?.ok){if(r?.code==='ACTIVE_TOUR_EXISTS'){const x=r.existing||{};setMsg(`IL FUNZIONARIO HA GIÀ UN GIRO ATTIVO: ${x.comune||''} ${x.via||''} · prossimo civico ${x.next_civic||'da configurare'}. Nessun dato è stato sovrascritto.`,true)}else setMsg(r?.message||'GIRO NON ASSEGNATO',true);return}$('panels').style.display='none';$('steps').style.display='none';document.querySelector('.nav')?.remove();$('msg').className='msg';$('successScreen').classList.add('on');const staff=selectedStaff();$('successText').textContent=`${staff?[staff.first_name,staff.last_name].filter(Boolean).join(' '):'Funzionario'} · ${r.comune} · ${r.via} · ${r.civic_sequence.length} civici · primo civico ${r.next_civic}.`;await loadTours()}catch(e){setMsg('GIRO NON ASSEGNATO. I DATI INSERITI SONO STATI MANTENUTI. '+String(e?.message||e),true)}finally{state.busy=false;if($('assign'))$('assign').disabled=false}}
async function loadTours(){try{state.tours=await F1StaffData.rpc('f1_territory_admin_tours')||[];const box=$('tours');box.innerHTML=state.tours.length?state.tours.map(t=>{const pct=t.total_count?Math.round((Number(t.completed_count||0)/Number(t.total_count))*100):0;return`<div class="tour"><strong>${esc([t.first_name,t.last_name].filter(Boolean).join(' ')||t.role)}</strong><small>${esc(t.comune)}${t.via?' · '+esc(t.via):''}</small><small>Ultimo: ${esc(t.last_civic||'—')} · Prossimo: ${esc(t.next_civic||'—')} · ${esc(String(t.status||'').replaceAll('_',' '))}</small><div class="bar"><i style="width:${pct}%"></i></div><small>${Number(t.completed_count||0)} / ${Number(t.total_count||0)} civici</small></div>`}).join(''):'<div class="empty">NESSUN GIRO TERRITORIALE ATTIVO</div>'}catch(e){$('tours').innerHTML=`<div class="empty">${esc(e?.message||e)}</div>`}}
function reset(){Object.assign(state,{step:1,staffId:'',comune:'',zona:'',via:'',start:'',sequence:[],busy:false});$('panels').style.display='';$('steps').style.display='grid';$('successScreen').classList.remove('on');setMsg('');render()}
async function init(){try{if(!F1Sync?.configured?.()||!(await F1Sync.ensureSession())){location.replace('setup-cloud.html?return=assegna-giro.html');return}state.me=await F1StaffData.me();if(String(state.me.role||'').toUpperCase()!=='TITOLARE'){document.body.innerHTML='<main class="wrap"><section class="card"><h1>ACCESSO RISERVATO AL TITOLARE</h1><a class="btn dark" href="ricerca-territoriale.html">TORNA ALLA DASHBOARD</a></section></main>';return}state.team=await F1StaffData.rpc('f1_territory_admin_team')||[];if(state.team.length===1)state.staffId=state.team[0].user_id;await loadTours();render();$('assignAnother')?.addEventListener('click',reset)}catch(e){console.error(e);setMsg(String(e?.message||e),true)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();