(()=>{'use strict';
const $=id=>document.getElementById(id),txt=v=>String(v??'').trim();let list=[],kpis={},selected=null,loading=false,photoUrl='';
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function setStatus(msg,bad=false){const e=$('status');e.textContent=msg;e.className='status'+(bad?' err':'');}
function formStatus(form,msg,bad=false){const e=form.querySelector('[data-form-status]');if(e){e.textContent=msg;e.className='status'+(bad?' err':'');}}
function phoneHref(v){return 'tel:'+txt(v).replace(/[^+\d]/g,'');}
function fmtDate(v){if(!v)return'—';try{return new Intl.DateTimeFormat('it-IT',{timeZone:'Europe/Rome',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch(_){return v}}
function badge(r){const s=txt(r.office_status||r.workflow_state||r.status);const c=s==='VERIFICATO'?'ok':s==='DA_RICHIAMARE'?'follow':'work';return `<span class="badge ${c}">${esc(s.replaceAll('_',' ')||'DA LAVORARE')}</span>`;}
function render(){const body=$('rows');body.innerHTML=list.map((r,i)=>{const phone=txt(r.phone_normalized),verified=r.office_status==='VERIFICATO';return `<tr><td><span class="main">${esc(fmtDate(r.observed_at))}</span><span class="mut">Agg. ${esc(fmtDate(r.updated_at))}</span></td><td><span class="main">${esc([r.first_name,r.last_name].filter(Boolean).join(' ')||'—')}</span></td><td><span class="main">${esc([r.comune,r.via,r.civico].filter(Boolean).join(' · '))}</span><span class="mut">${esc(r.zona||'')}</span></td><td><span class="main">${esc((r.sign_type||'CARTELLO').replaceAll('_',' '))}</span><span class="mut">${esc(r.property_type||'')}</span></td><td><span class="phone">${esc(phone||'—')}</span><span class="mut">${r.phone_confirmed?'Confermato sul territorio':'Da verificare'}</span></td><td>${badge(r)}</td><td><span class="main">${esc(r.next_action||'—')}</span><span class="mut">${esc((r.workflow_state||'').replaceAll('_',' '))}</span></td><td><div class="rowbuttons"><button class="btn" data-act="detail" data-i="${i}">APRI SCHEDA</button>${r.photo_storage_path?`<button class="btn" data-act="photo" data-i="${i}">VEDI FOTO</button>`:''}<button class="btn gold" data-act="verify" data-i="${i}">VERIFICA NUMERO</button><a class="btn primary" data-call="${i}" href="${verified&&phone?phoneHref(phone):'#'}" ${verified&&phone?'':'aria-disabled="true" style="pointer-events:none;opacity:.4"'}>CHIAMA</a>${verified&&phone?`<button class="btn" data-act="outcome" data-i="${i}">REGISTRA ESITO</button>`:''}</div></td></tr>`}).join('');$('empty').hidden=!!list.length;$('kpiVerified').textContent=Number(kpis.cartelli_verificati||0);$('kpiCalls').textContent=Number(kpis.telefonate_effettuate||0);$('kpiReached').textContent=Number(kpis.contatti_raggiunti||0);$('kpiFollow').textContent=Number(kpis.richiami||0);$('kpiQualified').textContent=Number(kpis.qualificati||0);$('kpiAppointments').textContent=Number(kpis.appuntamenti||0);wireRows();}
async function load(){if(loading)return;loading=true;setStatus('CARICAMENTO CODA UFFICIO…');try{const result=await Promise.all([F1StaffData.rpc('f1_territory_admin_signs',{p_search:txt($('search').value),p_status:txt($('filter').value),p_limit:300}),F1StaffData.rpc('f1_territory_office_kpis',{p_date:null})]);list=result[0]||[];kpis=result[1]||{};render();setStatus(`✓ ${list.length} CARTELL${list.length===1?'O':'I'} DISPONIBIL${list.length===1?'E':'I'} IN UFFICIO.`)}catch(e){setStatus('ERRORE · '+String(e?.message||e),true)}finally{loading=false}}
function wireRows(){document.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>{const r=list[Number(b.dataset.i)];if(!r)return;const a=b.dataset.act;if(a==='verify')openVerify(r);if(a==='outcome')openOutcome(r);if(a==='photo')viewPhoto(r);if(a==='detail')openDetail(r)});document.querySelectorAll('[data-call]').forEach(a=>a.addEventListener('click',()=>{const r=list[Number(a.dataset.call)];if(!r?.phone_normalized||r.office_status!=='VERIFICATO')return;setTimeout(()=>openOutcome(r),350)}));}
function openVerify(r){selected=r;$('verifyAddress').innerHTML=`<strong>${esc([r.comune,r.via,r.civico].filter(Boolean).join(' · '))}</strong><p>${esc((r.sign_type||'').replaceAll('_',' '))}<br>Numero OCR: ${esc(r.phone_ocr_raw||'—')}</p>`;const f=$('verifyForm');f.elements.phone.value=txt(r.phone_normalized);f.elements.valid.value=r.phone_normalized?'1':'0';f.elements.note.value='';formStatus(f,'');$('verifyDlg').showModal();}
async function verify(ev){ev.preventDefault();const f=ev.currentTarget;if(!selected||!f.reportValidity())return;const fd=new FormData(f),valid=fd.get('valid')==='1',phone=txt(fd.get('phone'));if(valid&&!phone){formStatus(f,'INSERISCI IL NUMERO DA VERIFICARE.',true);return}formStatus(f,'SALVATAGGIO VERIFICA…');try{await F1StaffData.rpc('f1_territory_office_verify_sign',{p_observation_id:selected.observation_id,p_phone_valid:valid,p_phone_normalized:phone,p_note:txt(fd.get('note'))});$('verifyDlg').close();await load()}catch(e){formStatus(f,String(e?.message||e),true)}}
function openOutcome(r){selected=r;$('outcomeAddress').innerHTML=`<strong>${esc([r.comune,r.via,r.civico].filter(Boolean).join(' · '))}</strong><p>Telefono: ${esc(r.phone_normalized||'—')}<br>${esc((r.sign_type||'').replaceAll('_',' '))}</p>`;const f=$('outcomeForm');f.reset();$('callbackWrap').hidden=true;formStatus(f,'');$('outcomeDlg').showModal();}
async function saveOutcome(ev){ev.preventDefault();const f=ev.currentTarget;if(!selected||!f.reportValidity())return;const fd=new FormData(f),out=txt(fd.get('outcome')),date=txt(fd.get('callback_date'));if(out==='RICHIAMARE'&&!date){formStatus(f,'INDICA LA DATA DEL RICHIAMO.',true);return}formStatus(f,'SALVATAGGIO ESITO…');try{await F1StaffData.rpc('f1_territory_office_call_result',{p_observation_id:selected.observation_id,p_outcome:out,p_note:txt(fd.get('note')),p_callback_date:date||null});$('outcomeDlg').close();await load()}catch(e){formStatus(f,String(e?.message||e),true)}}
async function duplicateRows(r){try{const d=await F1StaffData.rpc('f1_territory_sign_duplicates',{p_phone_normalized:r.phone_normalized||'',p_comune:r.comune||'',p_via:r.via||'',p_civico:r.civico||'',p_sign_type:r.sign_type||''})||[];return d.filter(x=>String(x.observation_id||'')!==String(r.observation_id))}catch(_){return[]}}
async function openDetail(r){selected=r;$('detailBody').innerHTML='<div class="status">CARICAMENTO SCHEDA…</div>';$('detailDlg').showModal();try{const [h,d]=await Promise.all([F1StaffData.rpc('f1_territory_office_sign_history',{p_observation_id:r.observation_id}),duplicateRows(r)]);const o=h?.observation||r,ints=h?.interactions||[];$('detailBody').innerHTML=`<div class="two"><div class="detail"><strong>INDIRIZZO</strong><p>${esc([o.comune,o.zona,o.via,o.civico].filter(Boolean).join(' · '))}</p></div><div class="detail"><strong>RILEVATO DA</strong><p>${esc([r.first_name,r.last_name].filter(Boolean).join(' ')||'—')}\n${esc(fmtDate(o.observed_at))}</p></div></div><div class="two"><div class="detail"><strong>CARTELLO</strong><p>${esc((o.sign_type||'').replaceAll('_',' '))}\n${esc(o.property_type||'')}</p></div><div class="detail"><strong>TELEFONO</strong><p>${esc(o.phone_normalized||'—')}\n${o.phone_confirmed?'CONFERMATO':'DA VERIFICARE'}</p></div></div><div class="detail"><strong>TESTO OCR / CONFERMATO</strong><p>${esc(o.ocr_text_confirmed||o.ocr_text_raw||'—')}</p></div><div class="detail"><strong>STATO / PROSSIMA AZIONE</strong><p>${esc((o.workflow_state||'').replaceAll('_',' '))}\n${esc(o.next_action||'—')}</p></div>${d.length?`<div class="warn"><b>⚠ POSSIBILI DUPLICATI</b>${d.slice(0,8).map(x=>`<div class="dup"><strong>${esc(x.source_type==='LEAD'?'CRM LEAD':'CARTELLO TERRITORIALE')}</strong><span>${esc([x.display_name,x.comune,x.via,x.civico,x.phone].filter(Boolean).join(' · '))}</span><span>${esc(x.status||'')} · ${esc(x.next_action||'')}</span></div>`).join('')}</div>`:'<div class="detail"><strong>DUPLICATI</strong><p>Nessun duplicato rilevato per telefono o indirizzo.</p></div>'}<div><span class="label">STORICO UNICO</span><div class="history">${ints.length?ints.map(i=>`<div class="event"><b>${esc(fmtDate(i.occurred_at))} · ${esc((i.interaction_type||'EVENTO').replaceAll('_',' '))}</b><span>${esc((i.outcome||'').replaceAll('_',' '))} · ${esc(i.next_action||'')}</span>${i.note?`<p>${esc(i.note)}</p>`:''}</div>`).join(''):'<div class="event"><b>${esc(fmtDate(o.observed_at))} · NOTIZIERE</b><span>Cartello fotografato e inviato all’ufficio.</span></div>'}</div></div>`;}catch(e){$('detailBody').innerHTML=`<div class="status err">${esc(String(e?.message||e))}</div>`}}
async function viewPhoto(r){if(!r.photo_storage_path)return;selected=r;if(photoUrl){URL.revokeObjectURL(photoUrl);photoUrl=''}$('photoImg').removeAttribute('src');$('photoStatus').textContent='CARICAMENTO FOTO…';$('photoDlg').showModal();try{const cfg=window.F1_SUPABASE||{},token=await F1Sync.authToken(),path=r.photo_storage_path.split('/').map(encodeURIComponent).join('/'),res=await fetch(cfg.url.replace(/\/$/,'')+`/storage/v1/object/authenticated/f1-territory-photos/${path}`,{headers:{apikey:cfg.anonKey,Authorization:'Bearer '+token}});if(!res.ok)throw new Error('FOTO NON DISPONIBILE: '+res.status);const blob=await res.blob();photoUrl=URL.createObjectURL(blob);$('photoImg').src=photoUrl;$('photoStatus').textContent='✓ FOTO ORIGINALE DEL CARTELLO';}catch(e){$('photoStatus').textContent=String(e?.message||e);$('photoStatus').className='status err'}}
function wire(){document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());$('refreshBtn').onclick=load;$('searchBtn').onclick=load;$('search').addEventListener('keydown',e=>{if(e.key==='Enter')load()});$('filter').onchange=load;$('verifyForm').onsubmit=verify;$('outcomeForm').onsubmit=saveOutcome;$('outcomeForm').elements.outcome.onchange=e=>{$('callbackWrap').hidden=e.target.value!=='RICHIAMARE'};addEventListener('f1:realtime-change',()=>setTimeout(load,250));addEventListener('focus',()=>load());setInterval(load,45000);}
async function boot(){wire();try{if(!window.F1Sync?.configured?.()||!await F1Sync.ensureSession()){location.replace('setup-cloud.html?return='+encodeURIComponent('cartelli-ufficio.html'));return}await F1StaffData.me();document.documentElement.classList.remove('f1-auth-pending');window.F1Realtime?.start?.();await load()}catch(e){document.documentElement.classList.remove('f1-auth-pending');setStatus('ACCESSO NON DISPONIBILE · '+String(e?.message||e),true)}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
