(function(){
'use strict';
const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const TYPES=['PROPERTY','REQUEST','LEAD','NEWS','TASK','OPPORTUNITY'];
const LABELS={PROPERTY:'IMMOBILI',REQUEST:'RICHIESTE',LEAD:'CONTATTI',NEWS:'NOTIZIE',TASK:'ATTIVITÀ',OPPORTUNITY:'OPPORTUNITÀ'};
const state={points:[],active:new Set(TYPES),map:null,layer:null};
function setStatus(msg,kind=''){const n=$('#status');n.textContent=msg;n.className='status '+kind}
async function auth(){if(!window.F1Sync?.configured?.())throw new Error('Supabase non configurato');if(!(await F1Sync.ensureSession())){location.replace('setup-cloud.html?return='+encodeURIComponent('f1-crm-map.html'));return false}await F1StaffData.me();return true}
function renderFilters(){const counts=Object.fromEntries(TYPES.map(t=>[t,state.points.filter(p=>p.entity_type===t).length]));$('#filters').innerHTML=TYPES.map(t=>`<label class="filter"><span><input type="checkbox" data-type="${t}" checked> ${LABELS[t]}</span><b>${counts[t]}</b></label>`).join('');document.querySelectorAll('[data-type]').forEach(x=>x.onchange=()=>{x.checked?state.active.add(x.dataset.type):state.active.delete(x.dataset.type);renderPoints()})}
function filtered(){const q=$('#q').value.trim().toLowerCase();return state.points.filter(p=>state.active.has(p.entity_type)&&(!q||[p.label,p.address,p.entity_type,p.source].join(' ').toLowerCase().includes(q)))}
function popup(p){return `<div><b>${esc(LABELS[p.entity_type]||p.entity_type)}</b><br><strong>${esc(p.label||p.entity_id)}</strong><br><span>${esc(p.address||'')}</span><br><small>${esc(p.geo_precision||'')}</small></div>`}
function renderPoints(){const rows=filtered();$('#summary').textContent=`${rows.length} punti visibili su ${state.points.length} coordinate reali.`;$('#pointList').innerHTML=rows.slice(0,60).map(p=>`<article class="point"><b>${esc(LABELS[p.entity_type]||p.entity_type)} · ${esc(p.label||p.entity_id)}</b><span>${esc(p.address||'')} · ${Number(p.latitude).toFixed(5)}, ${Number(p.longitude).toFixed(5)}</span></article>`).join('');if(!state.map)return;state.layer.clearLayers();for(const p of rows){if(!Number.isFinite(Number(p.latitude))||!Number.isFinite(Number(p.longitude)))continue;L.marker([Number(p.latitude),Number(p.longitude)]).bindPopup(popup(p)).addTo(state.layer)}if(rows.length){const bounds=L.latLngBounds(rows.map(p=>[Number(p.latitude),Number(p.longitude)]));if(bounds.isValid())state.map.fitBounds(bounds.pad(.12),{maxZoom:16})}}
function initMap(){if(!window.L)throw new Error('Libreria cartografica non caricata');state.map=L.map('map',{zoomControl:true});L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(state.map);state.layer=L.layerGroup().addTo(state.map)}
async function boot(){try{if(!(await auth()))return;state.points=await F1StaffData.rpc('f1_map_points',{})||[];renderFilters();$('#q').oninput=renderPoints;if(!state.points.length){$('#emptyOverlay').hidden=false;$('#summary').textContent='0 punti geolocalizzati reali nel CRM.';setStatus('IN SVILUPPO · 0 PUNTI GEO REALI','warn');return}initMap();renderPoints();setStatus('MAPPA COLLEGATA · '+state.points.length+' PUNTI REALI','ok')}catch(e){console.error(e);$('#emptyOverlay').hidden=false;setStatus('ERRORE · '+(e.message||e),'err')}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();