(()=>{'use strict';
const $=id=>document.getElementById(id),txt=v=>String(v??'').trim(),esc=v=>txt(v).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m])),num=v=>Number(v||0),up=v=>txt(v).toUpperCase();
let model=null,profile=null,territoryContext=null,current=null,busy=false;
function status(el,msg,bad=false){if(!el)return;el.textContent=msg;el.className='status'+(bad?' err':'')}
function formStatus(form,msg,bad=false){status(form.querySelector('[data-form-status]'),msg,bad)}
function openDlg(id){const d=$(id);if(d&&!d.open)d.showModal()}
function closeDlg(id){const d=$(id);if(d?.open)d.close()}
function iso(v){if(!v)return null;const d=new Date(v);return Number.isNaN(d.getTime())?null:d.toISOString()}
function pct(a,b){return b>0?Math.max(0,Math.min(100,Math.round(a/b*100))):0}
function setBusy(v){busy=!!v;document.querySelectorAll('button[type="submit"]').forEach(b=>b.disabled=busy)}
function stageClass(s){return['NON_INTERESSATO','PERSO','CONTATTO_ERRATO'].includes(up(s))?'bad':['FOLLOW_UP','RICHIAMARE','DA_PAGARE','OFFERTA_INVIATA'].includes(up(s))?'warn':''}
function renderState(){const s=model?.state||{},t=s.today||{},p=s.pipeline||{},a=s.alerts||{},tom=s.tomorrow||{},m=F1CashEngine.money;
 $('goalValue').textContent=m(s.goal);$('collectedValue').textContent=m(s.collected);$('missingValue').textContent=m(s.missing);$('confirmedValue').textContent=m(s.confirmed);$('toCollectValue').textContent=m(s.to_collect);$('goalProgress').style.width=pct(num(s.collected),num(s.goal))+'%';
 $('todayProspects').textContent=t.new_prospects||0;$('todayConversations').textContent=t.conversations||0;$('todayAppointments').textContent=t.appointments||0;$('todayOffers').textContent=t.offers||0;$('todaySales').textContent=t.sales||0;$('todayCollected').textContent=m(s.collected_today);$('pipelineValue').textContent=m(s.pipeline_value);
 $('pProspects').textContent=p.prospects||0;$('pInterested').textContent=p.interested||0;$('pAppointments').textContent=p.appointments||0;$('pOffers').textContent=p.offers||0;$('pAccepted').textContent=p.accepted||0;$('pPaid').textContent=p.paid||0;
 $('targetDate').textContent=s.target_date?new Intl.DateTimeFormat('it-IT').format(new Date(s.target_date+'T12:00:00')):'DA CONFIGURARE';$('daysRemaining').textContent=s.days_remaining==null?'—':s.days_remaining;$('dailyNeeded').textContent=s.daily_needed==null?'—':m(s.daily_needed);$('tomFollowups').textContent=tom.followups||0;$('tomAppointments').textContent=tom.appointments||0;$('tomActions').textContent=tom.actions||0;
 renderAlerts(a);renderNext(s.next_action||{});renderOpportunities();renderConversions();renderAdmin();
}
function renderAlerts(a){const defs=[['FOLLOW-UP SCADUTI','overdue_followups'],['APPUNTAMENTI ≤ 30 MIN','appointments_30m'],['OFFERTE DA RICHIAMARE','offers_due'],['PAGATI SENZA PRODUZIONE','paid_without_production'],['CONSEGNE/PRODUZIONE SCADUTE','production_due'],['PAGAMENTI ATTESI','payments_expected'],['SENZA PROSSIMA AZIONE','no_next_action']];$('alerts').innerHTML=defs.map(([label,key])=>`<div class="alert">${esc(label)} <strong>${Number(a[key]||0)}</strong></div>`).join('')}
function findOpp(id){return(model?.opportunities||[]).find(o=>String(o.opportunity_id)===String(id))||null}
function renderNext(n){const name=txt(n.business_name),action=txt(n.next_action||'TROVA UNA NUOVA ATTIVITÀ'),loc=[n.via,n.civico,n.comune].filter(Boolean).join(' · ');$('nowAction').textContent=action;$('nowWho').textContent=name||'PROSPECTING TERRITORIALE';$('nowReason').textContent=name?[loc,txt(n.observed_issue)&&F1CashEngine.human(n.observed_issue)].filter(Boolean).join(' · '):'Non ci sono azioni commerciali prioritarie: registra una nuova attività reale.';const host=$('nowButtons');host.innerHTML='';if(!n.opportunity_id){host.innerHTML='<button class="btn primary" data-new-prospect>＋ TROVA ATTIVITÀ</button>';host.querySelector('[data-new-prospect]').onclick=()=>prepareProspect(false);return}const o=findOpp(n.opportunity_id)||n;host.append(button('APRI SCHEDA','btn primary',()=>showDetail(o)));if(txt(n.telefono)){const a=document.createElement('a');a.className='btn';a.textContent='CHIAMA';a.href=F1CashEngine.telHref(n.telefono);host.append(a);const w=document.createElement('a');w.className='btn';w.textContent='WHATSAPP';w.href=F1CashEngine.waHref(n.telefono);w.target='_blank';w.rel='noopener';host.append(w)}host.append(button('REGISTRA ESITO','btn gold',()=>prepareOutcome(o)))}
function button(label,cls,fn){const b=document.createElement('button');b.type='button';b.className=cls;b.textContent=label;b.onclick=fn;return b}
function filteredOpps(){const f=up($('stageFilter').value);return(model?.opportunities||[]).filter(o=>!f||up(o.stage)===f)}
function renderOpportunities(){const rows=filteredOpps().slice(0,80);$('opportunityList').innerHTML=rows.length?rows.map(o=>`<div class="opp"><div><strong>${esc(o.business_name||o.azienda||'Attività senza nome')}</strong><small>${esc([o.category,o.comune,[o.via,o.civico].filter(Boolean).join(' ')].filter(Boolean).join(' · '))}</small><span class="stage ${stageClass(o.stage)}">${esc(F1CashEngine.human(o.stage))}</span><small>Prossima: ${esc(F1CashEngine.human(o.next_action))}${o.next_action_at?' · '+esc(F1CashEngine.dateTime(o.next_action_at)):''}</small></div><div><button class="btn" data-open="${esc(o.opportunity_id)}">APRI</button></div></div>`).join(''):'<div class="empty">Nessun prospect F1 CASH. Registra soltanto attività reali osservate o contatti reali.</div>';document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>showDetail(findOpp(b.dataset.open)))}
function renderConversions(){const c=model?.conversions||{},r=c.rates||{},defs=[['Prospect → conversazione','prospect_to_conversation',c.prospect],['Conversazione → interesse','conversation_to_interest',c.conversation],['Interesse → appuntamento','interest_to_appointment',c.interest],['Appuntamento → offerta','appointment_to_offer',c.appointment],['Offerta → vendita','offer_to_sale',c.offer],['Vendita → pagamento','sale_to_payment',c.sale]];$('conversions').innerHTML=defs.map(([label,key,n])=>`<div class="conv"><strong>${r[key]==null?'—':esc(r[key]+'%')}</strong><small>${esc(label)}</small><small>base: ${Number(n||0)}</small></div>`).join('');$('convNote').textContent=`Percentuali mostrate solo con almeno ${Number(c.minimum_sample||10)} casi nel denominatore.`}
function renderAdmin(){const isOwner=up(profile?.role)==='TITOLARE';$('goalBtn').style.display=isOwner?'':'none';$('productsBtn').style.display=isOwner?'':'none'}
async function refresh(force=true){try{model=await F1CashEngine.load({scope:'ME',force});profile=model.profile;renderState();status($('nowStatus'),'OPERATIVO')}catch(e){status($('nowStatus'),'ERRORE · '+String(e?.message||e),true)}}
async function boot(){try{if(!window.F1Sync?.configured?.()||!await F1Sync.ensureSession()){location.replace('setup-cloud.html?return='+encodeURIComponent('f1-cash.html'+location.search));return}profile=await F1StaffData.me();$('todayDate').textContent=new Intl.DateTimeFormat('it-IT',{timeZone:'Europe/Rome',weekday:'short',day:'2-digit',month:'short'}).format(new Date()).toUpperCase();await refresh(true);document.documentElement.classList.remove('f1-auth-pending');const q=new URLSearchParams(location.search);if(q.get('mode')==='new'){await prepareProspect(q.get('from')==='territory');if(q.get('from')==='territory')$('returnBanner').style.display='block'}}catch(e){document.documentElement.classList.remove('f1-auth-pending');status($('nowStatus'),'ERRORE · '+String(e?.message||e),true)}}
async function prepareProspect(fromTerritory=false){territoryContext=null;const f=$('prospectForm');f.reset();$('manualLocation').style.display='grid';$('territoryHint').hidden=true;if(fromTerritory){try{const t=await F1CashEngine.territory(),p=t?.progress||null;if(p){const civico=txt(p.next_civic||p.civic_start);territoryContext={progress_id:p.progress_id,comune:p.comune,zona:p.zona,via:p.via,civico};$('territoryHint').hidden=false;$('territoryHint').innerHTML=`<b>DATI EREDITATI DAL GIRO</b><br>${esc([p.comune,p.zona,p.via,civico&&'civico '+civico].filter(Boolean).join(' · '))}<br>Comune, via, civico, GPS, data, ora e operatore non vanno reinseriti.`;$('manualLocation').style.display='none'}}catch(e){status($('nowStatus'),'GIRO NON DISPONIBILE · puoi registrare manualmente Comune e via.',true)}}openDlg('prospectDlg')}
async function saveProspect(ev){ev.preventDefault();if(busy)return;const form=ev.currentTarget;if(!form.reportValidity())return;const fd=new FormData(form);const p={business_name:fd.get('business_name'),category:fd.get('category'),observed_issue:fd.get('observed_issue'),evidence_kind:fd.get('evidence_kind'),phone:fd.get('phone'),email:fd.get('email'),website:fd.get('website'),social:fd.get('social'),contact_person:fd.get('contact_person'),notes:fd.get('notes')};if(territoryContext)Object.assign(p,territoryContext);else Object.assign(p,{comune:fd.get('comune'),zona:fd.get('zona'),via:fd.get('via'),civico:fd.get('civico')});if(!txt(p.comune)||!txt(p.via)){formStatus(form,'COMUNE E VIA SONO OBBLIGATORI',true);return}setBusy(true);formStatus(form,'SALVATAGGIO OPPORTUNITÀ…');try{const r=await F1CashEngine.createProspect(p);formStatus(form,r?.action==='EXISTING_OPPORTUNITY'?'ATTIVITÀ GIÀ PRESENTE · apro il record esistente.':'✓ OPPORTUNITÀ SALVATA · PROSSIMA AZIONE: CONTATTARE');await refresh(true);setTimeout(()=>{closeDlg('prospectDlg');if(new URLSearchParams(location.search).get('return'))location.href=new URLSearchParams(location.search).get('return')},650)}catch(e){formStatus(form,'SALVATAGGIO NON COMPLETATO — I DATI SONO STATI MANTENUTI. '+String(e?.message||e),true)}finally{setBusy(false)}}
async function showDetail(o){if(!o)return;current=o;$('detailTitle').textContent=o.business_name||o.azienda||'OPPORTUNITÀ';$('detailMeta').innerHTML=`${esc([o.category,o.comune,[o.via,o.civico].filter(Boolean).join(' ')].filter(Boolean).join(' · '))}<br>Stato: <b>${esc(F1CashEngine.human(o.stage))}</b> · prossima azione: <b>${esc(F1CashEngine.human(o.next_action))}</b><br>Proposto: ${esc(F1CashEngine.money(o.proposed_value))} · Accettato: ${esc(F1CashEngine.money(o.accepted_value))} · Incassato: ${esc(F1CashEngine.money(o.paid_total))}`;const g=F1CashEngine.conversationGuide(o);$('guideBox').innerHTML=`<b>PERCHÉ CONTATTI</b><br>${esc(g.why)}<br><br><b>OBIETTIVO</b><br>${esc(g.objective)}<br><br><b>TRACCIA</b><br>${esc(g.opening)}<br><br><b>PROSSIMA DOMANDA</b><br>${esc(g.nextQuestion)}<br><br><b>MICRO-OBIETTIVO</b><br>${esc(g.microGoal)}`;const a=$('detailActions');a.innerHTML='';if(txt(o.telefono)){const c=document.createElement('a');c.className='btn primary';c.href=F1CashEngine.telHref(o.telefono);c.textContent='CHIAMA';a.append(c);const w=document.createElement('a');w.className='btn';w.href=F1CashEngine.waHref(o.telefono);w.target='_blank';w.rel='noopener';w.textContent='WHATSAPP';a.append(w)}a.append(button('COME È ANDATA?','btn gold',()=>{closeDlg('detailDlg');prepareOutcome(o)}));a.append(button('OFFERTA','btn',()=>{closeDlg('detailDlg');prepareOffer(o)}));a.append(button('PAGAMENTO','btn blue',()=>{closeDlg('detailDlg');preparePayment(o)}));if(['PAGATO','IN_PRODUZIONE','CONSEGNATO'].includes(up(o.stage)))a.append(button('PRODUZIONE','btn',()=>{closeDlg('detailDlg');prepareProduction(o)}));$('historyBox').textContent='Caricamento contatti precedenti…';openDlg('detailDlg');try{const h=await F1CashEngine.history(o.lead_id,8);$('historyBox').innerHTML='<b>CONTATTI PRECEDENTI</b><br>'+(h.length?h.map(x=>`${esc(F1CashEngine.dateTime(x.occurred_at))} · ${esc(F1CashEngine.human(x.outcome))}${x.note?' · '+esc(x.note):''}`).join('<br>'):'Nessuna interazione registrata.')}catch(_){$('historyBox').textContent='Contatti precedenti non disponibili.'}}
function prepareOutcome(o){current=o;const f=$('outcomeForm');f.reset();f.elements.opportunity_id.value=o.opportunity_id;$('outcomeDateWrap').hidden=true;openDlg('outcomeDlg')}
async function saveOutcome(ev){ev.preventDefault();if(busy)return;const f=ev.currentTarget;if(!f.reportValidity())return;const fd=new FormData(f),code=fd.get('outcome'),needs=F1CashEngine.nextNeedsDate(code),next=iso(fd.get('next_at'));if(needs&&!next){formStatus(f,'INDICA DATA E ORA DELLA PROSSIMA AZIONE',true);return}setBusy(true);formStatus(f,'REGISTRAZIONE ESITO…');try{const r=await F1CashEngine.outcome(fd.get('opportunity_id'),code,fd.get('note'),next);formStatus(f,'✓ REGISTRATO · PROSSIMA AZIONE: '+F1CashEngine.human(r.next_action));await refresh(true);setTimeout(()=>closeDlg('outcomeDlg'),450)}catch(e){formStatus(f,'ERRORE · '+String(e?.message||e),true)}finally{setBusy(false)}}
function fillProducts(){const sel=$('offerProduct');sel.innerHTML='<option value="">Prodotto non ancora definito</option>'+(model?.products||[]).map(p=>`<option value="${esc(p.product_id)}" data-target="${Number(p.target_price||0)}">${esc(p.name)} · ${esc(F1CashEngine.money(p.target_price))}</option>`).join('')}
function prepareOffer(o){fillProducts();const f=$('offerForm');f.reset();f.elements.opportunity_id.value=o.opportunity_id;if(o.product_id)f.elements.product_id.value=o.product_id;if(num(o.proposed_value)>0)f.elements.proposed_value.value=o.proposed_value;if(num(o.accepted_value)>0)f.elements.accepted_value.value=o.accepted_value;openDlg('offerDlg')}
async function saveOffer(ev){ev.preventDefault();if(busy)return;const f=ev.currentTarget;if(!f.reportValidity())return;const fd=new FormData(f);setBusy(true);formStatus(f,'SALVATAGGIO OFFERTA…');try{await F1CashEngine.offer(fd.get('opportunity_id'),fd.get('product_id'),fd.get('proposed_value'),fd.get('accepted_value'),iso(fd.get('followup_at')));formStatus(f,'✓ OFFERTA REGISTRATA · la liquidità resta invariata finché non registri un incasso.');await refresh(true);setTimeout(()=>closeDlg('offerDlg'),500)}catch(e){formStatus(f,'ERRORE · '+String(e?.message||e),true)}finally{setBusy(false)}}
function preparePayment(o){const f=$('paymentForm');f.reset();f.elements.opportunity_id.value=o.opportunity_id;openDlg('paymentDlg')}
async function savePayment(ev){ev.preventDefault();if(busy)return;const f=ev.currentTarget;if(!f.reportValidity())return;const fd=new FormData(f);setBusy(true);formStatus(f,'REGISTRAZIONE INCASSO…');try{const r=await F1CashEngine.payment(fd.get('opportunity_id'),fd.get('amount'),iso(fd.get('received_at')),fd.get('method'),fd.get('note'));formStatus(f,'✓ INCASSATO '+F1CashEngine.money(fd.get('amount'))+' · residuo '+F1CashEngine.money(r.remaining));await refresh(true);setTimeout(()=>closeDlg('paymentDlg'),600)}catch(e){formStatus(f,'ERRORE · '+String(e?.message||e),true)}finally{setBusy(false)}}
function prepareProduction(o){const f=$('productionForm');f.reset();f.elements.opportunity_id.value=o.opportunity_id;if(o.production_stage)f.elements.stage.value=o.production_stage;openDlg('productionDlg')}
async function saveProduction(ev){ev.preventDefault();if(busy)return;const f=ev.currentTarget;if(!f.reportValidity())return;const fd=new FormData(f);setBusy(true);formStatus(f,'AGGIORNAMENTO PRODUZIONE…');try{const r=await F1CashEngine.production(fd.get('opportunity_id'),fd.get('stage'),iso(fd.get('due_at')),fd.get('note'));formStatus(f,'✓ '+F1CashEngine.human(r.production_stage)+' · prossima: '+F1CashEngine.human(r.next_action));await refresh(true);setTimeout(()=>closeDlg('productionDlg'),500)}catch(e){formStatus(f,'ERRORE · '+String(e?.message||e),true)}finally{setBusy(false)}}
function prepareGoal(){const f=$('goalForm');f.elements.amount.value=model?.state?.goal||10000;f.elements.target_date.value=model?.state?.target_date||'';openDlg('goalDlg')}
async function saveGoal(ev){ev.preventDefault();if(busy)return;const f=ev.currentTarget;if(!f.reportValidity())return;const fd=new FormData(f);setBusy(true);formStatus(f,'SALVATAGGIO…');try{await F1CashEngine.updateGoal(fd.get('amount'),fd.get('target_date'));formStatus(f,'✓ OBIETTIVO AGGIORNATO');await refresh(true);setTimeout(()=>closeDlg('goalDlg'),400)}catch(e){formStatus(f,'ERRORE · '+String(e?.message||e),true)}finally{setBusy(false)}}
async function showProducts(){try{const rows=await F1CashEngine.allProducts();$('productList').innerHTML=rows.map(p=>`<div class="opp"><div><strong>${esc(p.name)}</strong><small>Target ${esc(F1CashEngine.money(p.target_price))} · ${esc(p.duration||'')}</small><small>${esc(p.pricing_note||'')}</small></div><button class="btn" data-edit-product="${esc(p.product_id)}">MODIFICA</button></div>`).join('');document.querySelectorAll('[data-edit-product]').forEach(b=>b.onclick=()=>editProduct(rows.find(p=>p.product_id===b.dataset.editProduct)));openDlg('productsDlg')}catch(e){status($('dayStatus'),'PRODOTTI NON DISPONIBILI · '+String(e?.message||e),true)}}
function editProduct(p={}){const f=$('productForm');f.reset();['product_id','name','target_price','price_min','price_max','estimated_margin','content','duration','payment_terms','delivery_time','sort_order'].forEach(k=>{if(f.elements[k])f.elements[k].value=p[k]??(k==='sort_order'?100:'')});f.elements.active.checked=p.active!==false;openDlg('productEditDlg')}
async function saveProduct(ev){ev.preventDefault();if(busy)return;const f=ev.currentTarget;if(!f.reportValidity())return;const fd=new FormData(f),p=Object.fromEntries(fd.entries());p.active=f.elements.active.checked;setBusy(true);formStatus(f,'SALVATAGGIO PRODOTTO…');try{await F1CashEngine.upsertProduct(p);formStatus(f,'✓ PRODOTTO SALVATO');await refresh(true);setTimeout(()=>{closeDlg('productEditDlg');showProducts()},450)}catch(e){formStatus(f,'ERRORE · '+String(e?.message||e),true)}finally{setBusy(false)}}
async function closeDay(){if(busy)return;setBusy(true);status($('dayStatus'),'CHIUSURA GIORNATA…');try{const r=await F1CashEngine.closeDay(),s=r?.snapshot?.state||{};status($('dayStatus'),`✓ GIORNATA CHIUSA · prospect ${s.today?.new_prospects||0} · conversazioni ${s.today?.conversations||0} · appuntamenti ${s.today?.appointments||0} · incassato oggi ${F1CashEngine.money(s.collected_today)} · totale ${F1CashEngine.money(s.collected)} · mancano ${F1CashEngine.money(s.missing)}.`)}catch(e){status($('dayStatus'),'ERRORE · '+String(e?.message||e),true)}finally{setBusy(false)}}
function wire(){document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeDlg(b.dataset.close));$('newProspectBtn').onclick=()=>prepareProspect(false);$('mobileNewBtn').onclick=()=>prepareProspect(false);$('refreshBtn').onclick=()=>refresh(true);$('stageFilter').onchange=renderOpportunities;$('closeDayBtn').onclick=closeDay;$('goalBtn').onclick=prepareGoal;$('productsBtn').onclick=showProducts;$('newProductBtn').onclick=()=>editProduct({});$('prospectForm').addEventListener('submit',saveProspect);$('outcomeForm').addEventListener('submit',saveOutcome);$('offerForm').addEventListener('submit',saveOffer);$('paymentForm').addEventListener('submit',savePayment);$('productionForm').addEventListener('submit',saveProduction);$('goalForm').addEventListener('submit',saveGoal);$('productForm').addEventListener('submit',saveProduct);$('outcomeForm').elements.outcome.onchange=e=>{$('outcomeDateWrap').hidden=!F1CashEngine.nextNeedsDate(e.target.value)};$('offerProduct').onchange=e=>{const opt=e.target.selectedOptions[0],f=$('offerForm');if(opt?.dataset.target&&!f.elements.proposed_value.value)f.elements.proposed_value.value=opt.dataset.target};window.addEventListener('focus',()=>refresh(false))}
wire();boot();
})();