(function(){
'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const state={me:null,cfg:null,leads:[],tasks:[],interactions:[],roles:[],properties:[],view:'today',selectedLead:'',pendingLead:null,duplicateCandidates:[]};
const todayRome=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Rome',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const dtRome=v=>{if(!v)return'';try{return new Intl.DateTimeFormat('it-IT',{timeZone:'Europe/Rome',day:'2-digit',month:'2-digit',year:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch(_){return String(v)}};
const dayOnly=v=>String(v||'').slice(0,10);
const upper=v=>String(v||'').toUpperCase();
const visibleName=l=>String([l?.nome,l?.cognome].filter(Boolean).join(' ')||l?.azienda||'Contatto senza nome');
const activeTask=t=>!['DONE','CANCELLED','CANCELED','CLOSED'].includes(upper(t.status));
const isDue=t=>!t.due_date||dayOnly(t.due_date)<=todayRome();
function setStatus(msg,kind='ok'){const n=$('#appStatus');if(!n)return;n.textContent=msg||'';n.className='app-status '+kind}
async function loadConfig(){const r=await fetch('config/crm-os.json?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error('Configurazione CRM OS non disponibile');return r.json()}
async function auth(){if(!window.F1Sync?.configured?.())throw new Error('Supabase non configurato');const ok=await F1Sync.ensureSession();if(!ok){location.replace('setup-cloud.html?return='+encodeURIComponent('f1-crm-os.html'+location.search));return false}state.me=await F1StaffData.me();return true}
async function loadData(){
  const [leads,tasks,interactions,roles,properties]=await Promise.all([
    F1StaffData.rest('leads?deleted=eq.false&select=*&order=updated_at.desc&limit=1200'),
    F1StaffData.rest('tasks?select=*&order=priority.desc,due_date.asc&limit=1200'),
    F1StaffData.rest('interactions?select=*&order=occurred_at.desc&limit=1200'),
    F1StaffData.rest('f1_contact_roles?role_status=eq.ACTIVE&select=*&order=updated_at.desc&limit=1200'),
    F1StaffData.rest('properties?deleted=eq.false&select=*&order=updated_at.desc&limit=1200')
  ]);
  state.leads=leads||[];state.tasks=tasks||[];state.interactions=interactions||[];state.roles=roles||[];state.properties=properties||[];
}
function renderIdentity(){
  const m=state.me||{};$('#whoName').textContent=[m.first_name,m.last_name].filter(Boolean).join(' ')||'Utente F1';
  $('#whoRole').textContent=m.role||'STAFF';
  $('#todayLabel').textContent=new Intl.DateTimeFormat('it-IT',{timeZone:'Europe/Rome',weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date());
}
function taskStats(){const d=todayRome(),open=state.tasks.filter(activeTask),calls=open.filter(t=>upper(t.task_type)==='CALL'&&isDue(t)),callbacks=open.filter(t=>upper(t.task_type)==='FOLLOW_UP'&&isDue(t)),newLeads=state.leads.filter(l=>dayOnly(l.created_at)===d),appts=open.filter(t=>['APPOINTMENT','MEETING','APPUNTAMENTO'].includes(upper(t.task_type))&&isDue(t)),owners=new Set(state.roles.filter(r=>['PROPRIETARIO','VENDITORE'].includes(upper(r.role_type))).map(r=>r.lead_id));return{calls,callbacks,newLeads,appts,owners}}
function leadById(id){return state.leads.find(x=>String(x.lead_id)===String(id))||null}
function rolesFor(id){return state.roles.filter(r=>String(r.lead_id)===String(id)&&upper(r.role_status)==='ACTIVE')}
function taskForLead(id){return state.tasks.filter(t=>String(t.lead_id)===String(id))}
function interactionsFor(id){return state.interactions.filter(i=>String(i.lead_id)===String(id))}
function taskSubject(t){const l=leadById(t.lead_id);return l?visibleName(l):(t.reason||t.task_type||'Attività')}
function nextTask(){return state.tasks.filter(t=>activeTask(t)&&isDue(t)).sort((a,b)=>(Number(b.priority)||0)-(Number(a.priority)||0)||String(a.due_date||'').localeCompare(String(b.due_date||'')))[0]||null}
function renderToday(){
  const s=taskStats(),n=nextTask();
  $('#mainTitle').textContent='OGGI';
  $('#mainBody').innerHTML=`
    <section class="hero-grid">
      ${metric('TELEFONATE',s.calls.length,'CALL')}${metric('RICHIAMI',s.callbacks.length,'FOLLOW-UP')}${metric('NUOVI LEAD',s.newLeads.length,'OGGI')}${metric('APPUNTAMENTI',s.appts.length,'AGENDA')}${metric('PROPRIETARI',s.owners.size,'DA LAVORARE')}${metric('MATCH',state.cfg.featureFlags.newMatchingEngine?'ATTIVO':'—','P2')}
    </section>
    <section class="panel next-action"><div class="ey">PROSSIMA AZIONE</div>${n?nextTaskCard(n):'<div class="empty">Nessun task dovuto. Apri la coda completa o crea una nuova attività.</div>'}</section>
    <section class="two-col"><div class="panel"><div class="ey">CODA PRIORITARIA</div><h2>Da eseguire adesso</h2><div>${state.tasks.filter(t=>activeTask(t)&&isDue(t)).slice(0,10).map(taskRow).join('')||'<div class="empty">Nessuna attività dovuta.</div>'}</div></div>
    <div class="panel"><div class="ey">CRM QUALITY</div><h2>Igiene operativa</h2>${qualitySummary()}</div></section>`;
}
function metric(label,value,sub){return `<article class="metric"><b>${esc(value)}</b><span>${esc(label)}</span><small>${esc(sub)}</small></article>`}
function nextTaskCard(t){const l=leadById(t.lead_id);return `<div class="next-card"><div class="next-time">${esc(timeOf(t.due_date))}</div><div><h2>${esc(taskSubject(t))}</h2><p>${esc(l?.comune||t.reason||'')}</p><p class="muted">${esc(t.reason||t.task_type)} · priorità ${esc(t.priority||0)}</p><div class="actions">${l?`<button data-open-contact="${esc(l.lead_id)}">APRI SCHEDA</button>`:''}${l?.telefono?`<a class="button" href="tel:${esc(l.telefono)}">CHIAMA</a>`:''}<button data-complete-task="${esc(t.task_id)}" class="primary">COMPLETATO</button><button data-reschedule-task="${esc(t.task_id)}">RIPROGRAMMA +1G</button></div></div></div>`}
function taskRow(t){const l=leadById(t.lead_id);return `<div class="task-row"><div><b>${esc(taskSubject(t))}</b><span>${esc(t.task_type)} · ${esc(t.reason||'')}</span></div><div class="task-meta"><span>${esc(timeOf(t.due_date))}</span><span class="priority">${esc(t.priority||0)}</span>${l?`<button data-open-contact="${esc(l.lead_id)}">APRI</button>`:''}</div></div>`}
function qualitySummary(){const incomplete=state.leads.filter(l=>!l.telefono&&!l.email).length,withoutNext=state.leads.filter(l=>!l.next_action_date&&!['INCARICO','ACQUISITO','PERSO','ARCHIVIATO'].includes(upper(l.status))).length,dupeRisk=duplicateRiskCount();return `<div class="quality-grid">${metric('SENZA RECAPITO',incomplete,'DA COMPLETARE')}${metric('SENZA PROSSIMA AZIONE',withoutNext,'WORKFLOW')}${metric('RISCHI DUPLICATO',dupeRisk,'CONTROLLO')}</div><p class="muted">Questi indicatori non sostituiscono il Work Quality Score: mostrano anomalie operative direttamente verificabili.</p>`}
function duplicateRiskCount(){const phones=new Map(),emails=new Map();let n=0;for(const l of state.leads){const p=String(l.telefono||'').replace(/\D/g,''),e=String(l.email||'').trim().toLowerCase();if(p){n+=phones.has(p)?1:0;phones.set(p,1)}if(e){n+=emails.has(e)?1:0;emails.set(e,1)}}return n}
function timeOf(v){if(!v)return'—';try{return new Intl.DateTimeFormat('it-IT',{timeZone:'Europe/Rome',hour:'2-digit',minute:'2-digit'}).format(new Date(v))}catch(_){return'—'}}
function renderContacts(filterRole=''){
  $('#mainTitle').textContent=filterRole||'CONTATTI';
  let leads=state.leads;if(filterRole){const ids=new Set(state.roles.filter(r=>upper(r.role_type)===filterRole).map(r=>r.lead_id));leads=leads.filter(l=>ids.has(l.lead_id))}
  $('#mainBody').innerHTML=`<section class="panel"><div class="section-head"><div><div class="ey">SCHEDA MASTER</div><h2>${esc(filterRole||'Tutti i contatti')}</h2></div><button class="primary" data-quick="CONTATTO">+ NUOVO</button></div><div class="contact-list">${leads.slice(0,250).map(contactRow).join('')||'<div class="empty">Nessun contatto visibile.</div>'}</div></section>`;
}
function contactRow(l){const roles=rolesFor(l.lead_id);const t=taskForLead(l.lead_id).filter(activeTask).sort((a,b)=>String(a.due_date||'').localeCompare(String(b.due_date||'')))[0];return `<article class="contact-row" data-open-contact="${esc(l.lead_id)}"><div><b>${esc(visibleName(l))}</b><span>${esc(l.comune||'')} ${l.telefono?'· '+esc(l.telefono):''}</span><div class="role-line">${roles.length?roles.map(r=>`<em>${esc(r.role_type)}</em>`).join(''):`<em>${esc(l.source_type||'PROSPECT')}</em>`}</div></div><div class="contact-next"><strong>${esc(l.status||'')}</strong><span>${t?esc(t.reason||t.task_type):'Nessun task aperto'}</span></div></article>`}
async function openContact(id){state.selectedLead=id;history.replaceState(null,'','f1-crm-os.html?contact='+encodeURIComponent(id));const l=leadById(id);if(!l){setStatus('Contatto non disponibile','err');return}renderContact(l)}
function renderContact(l){
  $('#mainTitle').textContent=visibleName(l);
  const roles=rolesFor(l.lead_id),ints=interactionsFor(l.lead_id),tasks=taskForLead(l.lead_id),property=state.properties.find(p=>String(p.property_id)===String(l.immobile_id));
  $('#mainBody').innerHTML=`<section class="panel contact-master">
    <div class="contact-header"><div><div class="ey">SCHEDA CONTATTO 360°</div><h2>${esc(visibleName(l))}</h2><p>${esc(l.telefono||'—')} · ${esc(l.email||'—')} · ${esc(l.comune||'—')}</p><div class="role-line">${roles.map(r=>`<em>${esc(r.role_type)}${r.pipeline_stage?' · '+esc(r.pipeline_stage):''}</em>`).join('')||'<em>RUOLO DA DEFINIRE</em>'}</div></div><div class="contact-score"><span>LEAD SCORE</span><b>${esc(l.lead_score||0)}</b></div></div>
    <div class="actions">${l.telefono?`<a class="button primary" href="tel:${esc(l.telefono)}">CHIAMA</a>`:''}${l.telefono?`<a class="button" href="https://wa.me/${esc(String(l.telefono).replace(/\D/g,''))}" target="_blank" rel="noopener">WHATSAPP</a>`:''}<button data-role-add="${esc(l.lead_id)}">+ RUOLO</button><a class="button" href="crm.html">VISTA CRM CLASSICA</a></div>
    <div class="contact-facts"><div><span>ULTIMO CONTATTO</span><b>${esc(l.last_contact?dtRome(l.last_contact):'MAI REGISTRATO')}</b></div><div><span>PROSSIMA AZIONE</span><b>${esc(l.next_action||'DA DEFINIRE')}</b></div><div><span>DATA</span><b>${esc(l.next_action_date?dtRome(l.next_action_date):'—')}</b></div><div><span>STATO</span><b>${esc(l.status||'—')}</b></div></div>
  </section>
  <nav class="tabs"><button class="active" data-tab="overview">PANORAMICA</button><button data-tab="timeline">TIMELINE</button><button data-tab="property">IMMOBILI</button><button data-tab="tasks">ATTIVITÀ</button><button data-tab="notes">NOTE</button></nav>
  <section id="contactTab" class="panel">${contactOverview(l,roles,tasks,ints,property)}</section>`;
  $$('.tabs [data-tab]').forEach(b=>b.addEventListener('click',()=>{ $$('.tabs [data-tab]').forEach(x=>x.classList.toggle('active',x===b)); const tab=b.dataset.tab; $('#contactTab').innerHTML=tab==='timeline'?timelineHtml(ints,tasks):tab==='property'?propertyHtml(property):tab==='tasks'?tasksHtml(tasks):tab==='notes'?notesHtml(l):contactOverview(l,roles,tasks,ints,property); bindDynamic(); }));
  bindDynamic();
}
function contactOverview(l,roles,tasks,ints,property){return `<div class="detail-grid"><div><span>COMUNE</span><b>${esc(l.comune||'—')}</b></div><div><span>VIA</span><b>${esc([l.via,l.civico].filter(Boolean).join(' ')||'—')}</b></div><div><span>FONTE</span><b>${esc(l.source||l.source_type||'—')}</b></div><div><span>AGENTE</span><b>${esc(l.assigned_to||'—')}</b></div></div><h3>RUOLI E PIPELINE</h3><div class="pipeline-role-list">${roles.map(roleEditor).join('')||'<div class="empty">Aggiungi almeno un ruolo per usare pipeline multiple.</div>'}</div><h3>ULTIMA ATTIVITÀ</h3>${timelineHtml(ints.slice(0,5),tasks.filter(activeTask).slice(0,5))}${property?`<h3>IMMOBILE COLLEGATO</h3>${propertyHtml(property)}`:''}`}
function roleEditor(r){const pipe=state.cfg.pipelines[r.role_type]||[];return `<div class="role-edit"><b>${esc(r.role_type)}</b><select data-role-stage="${esc(r.role_id)}">${['',...pipe].map(s=>`<option value="${esc(s)}" ${s===r.pipeline_stage?'selected':''}>${esc(s||'STADIO DA DEFINIRE')}</option>`).join('')}</select></div>`}
function timelineHtml(ints,tasks){const all=[...ints.map(i=>({d:i.occurred_at,t:i.interaction_type||'INTERAZIONE',title:i.outcome||i.note||'Interazione',note:i.note||''})),...tasks.map(t=>({d:t.completed_at||t.due_date||t.created_at,t:'TASK '+t.status,title:t.reason||t.task_type,note:t.outcome||''}))].filter(x=>x.d).sort((a,b)=>String(b.d).localeCompare(String(a.d)));return `<div class="timeline">${all.map(x=>`<div class="timeline-item"><time>${esc(dtRome(x.d))}</time><div><b>${esc(x.t)}</b><strong>${esc(x.title)}</strong>${x.note?`<p>${esc(x.note)}</p>`:''}</div></div>`).join('')||'<div class="empty">Nessuna attività registrata.</div>'}</div>`}
function propertyHtml(p){return p?`<article class="property-card"><b>${esc(p.tipologia||'IMMOBILE')}</b><span>${esc([p.via,p.civico,p.comune].filter(Boolean).join(', '))}</span><span>Stato: ${esc(p.status||'—')}</span><a class="button" href="address-intelligence.html?property_id=${encodeURIComponent(p.property_id)}">APRI INTELLIGENCE</a></article>`:'<div class="empty">Nessun immobile direttamente collegato a questa scheda.</div>'}
function tasksHtml(tasks){return tasks.map(taskRow).join('')||'<div class="empty">Nessuna attività.</div>'}
function notesHtml(l){return `<div class="notes-box"><p>${esc(l.notes||'Nessuna nota.')}</p><div class="muted">Le nuove note operative devono essere registrate come interazioni per mantenere la timeline cronologica.</div><button data-quick-note="${esc(l.lead_id)}">+ REGISTRA NOTA</button></div>`}
function renderPipeline(role='PROPRIETARIO'){
  $('#mainTitle').textContent='PIPELINE '+role;
  const stages=state.cfg.pipelines[role]||[],rows=state.roles.filter(r=>r.role_type===role&&r.role_status==='ACTIVE');
  $('#mainBody').innerHTML=`<section class="panel pipeline-panel"><div class="section-head"><div><div class="ey">KANBAN ADDITIVO</div><h2>${esc(role)}</h2></div><div class="seg"><button data-pipeline="PROPRIETARIO" class="${role==='PROPRIETARIO'?'active':''}">PROPRIETARI</button><button data-pipeline="ACQUIRENTE" class="${role==='ACQUIRENTE'?'active':''}">ACQUIRENTI</button></div></div><div class="kanban">${stages.map(s=>`<section class="lane"><header><b>${esc(s)}</b><span>${rows.filter(r=>(r.pipeline_stage||stages[0])===s).length}</span></header>${rows.filter(r=>(r.pipeline_stage||stages[0])===s).map(r=>kanbanCard(r)).join('')}</section>`).join('')}</div></section>`;
}
function kanbanCard(r){const l=leadById(r.lead_id);if(!l)return'';return `<article class="kanban-card" data-open-contact="${esc(l.lead_id)}"><b>${esc(visibleName(l))}</b><span>${esc(l.comune||'')}</span><small>${esc(l.next_action||'Nessuna prossima azione')}</small></article>`}
function renderProperties(){$('#mainTitle').textContent='IMMOBILI';$('#mainBody').innerHTML=`<section class="panel"><div class="section-head"><div><div class="ey">DATABASE IMMOBILIARE</div><h2>Immobili visibili</h2></div><a class="button" href="address-intelligence.html">ADDRESS INTELLIGENCE</a></div><div class="contact-list">${state.properties.slice(0,250).map(p=>`<article class="contact-row"><div><b>${esc(p.tipologia||p.property_id)}</b><span>${esc([p.via,p.civico,p.comune].filter(Boolean).join(', '))}</span></div><div class="contact-next"><strong>${esc(p.status||'')}</strong><span>${esc(p.zona||'')}</span></div></article>`).join('')||'<div class="empty">Nessun immobile visibile.</div>'}</div></section>`}
function renderSearch(q){const s=String(q||'').trim().toLowerCase();if(s.length<2){$('#searchResults').hidden=true;return}const out=[];for(const l of state.leads){const hay=[l.lead_id,l.nome,l.cognome,l.azienda,l.telefono,l.email,l.comune,l.via,l.civico,l.zona,l.source,l.notes].join(' ').toLowerCase();if(hay.includes(s))out.push({type:'CONTATTO',id:l.lead_id,title:visibleName(l),sub:[l.telefono,l.email,l.comune].filter(Boolean).join(' · '),score:100})}for(const p of state.properties){const hay=[p.property_id,p.comune,p.via,p.civico,p.zona,p.frazione,p.tipologia,p.status,p.fingerprint].join(' ').toLowerCase();if(hay.includes(s))out.push({type:'IMMOBILE',id:p.property_id,title:p.tipologia||p.property_id,sub:[p.via,p.comune,p.status].filter(Boolean).join(' · '),score:80})}for(const t of state.tasks){const hay=[t.task_id,t.task_type,t.reason,t.status,t.outcome,t.lead_id,t.property_id].join(' ').toLowerCase();if(hay.includes(s))out.push({type:'ATTIVITÀ',id:t.task_id,title:t.reason||t.task_type,sub:[t.status,t.lead_id].filter(Boolean).join(' · '),score:60,lead:t.lead_id})}for(const i of state.interactions){const hay=[i.interaction_id,i.interaction_type,i.outcome,i.note,i.lead_id,i.property_id].join(' ').toLowerCase();if(hay.includes(s))out.push({type:'INTERAZIONE',id:i.interaction_id,title:i.outcome||i.interaction_type,sub:[i.interaction_type,i.lead_id].filter(Boolean).join(' · '),score:55,lead:i.lead_id})}const items=out.sort((a,b)=>b.score-a.score).slice(0,30);$('#searchResults').innerHTML=items.map(x=>`<button class="search-hit" data-search-type="${esc(x.type)}" data-search-id="${esc(x.id)}" data-search-lead="${esc(x.lead||'')}"><em>${esc(x.type)}</em><b>${esc(x.title)}</b><span>${esc(x.sub)}</span></button>`).join('')||'<div class="empty">Nessun risultato.</div>';$('#searchResults').hidden=false}
function agenda(){const d=todayRome(),rows=state.tasks.filter(t=>activeTask(t)&&dayOnly(t.due_date)===d).sort((a,b)=>String(a.due_date||'').localeCompare(String(b.due_date||'')));$('#agendaList').innerHTML=rows.map(t=>`<article class="agenda-item"><time>${esc(timeOf(t.due_date))}</time><div><b>${esc(taskSubject(t))}</b><span>${esc(t.reason||t.task_type)}</span><button data-open-contact="${esc(t.lead_id||'')}" ${t.lead_id?'':'disabled'}>ESEGUI</button></div></article>`).join('')||'<div class="empty">Nessuna attività con orario registrato oggi.</div>'}
function showView(v){state.view=v;history.replaceState(null,'','f1-crm-os.html');$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===v));if(v==='today')renderToday();else if(v==='contacts')renderContacts();else if(v==='owners')renderContacts('PROPRIETARIO');else if(v==='buyers')renderContacts('ACQUIRENTE');else if(v==='pipeline-owner')renderPipeline('PROPRIETARIO');else if(v==='pipeline-buyer')renderPipeline('ACQUIRENTE');else if(v==='properties')renderProperties();bindDynamic()}
function openQuick(type='CONTATTO',leadId=''){const d=$('#quickDlg');$('#quickType').value=type;$('#quickLeadId').value=leadId||'';$('#quickForm').reset();$('#quickType').value=type;$('#quickLeadId').value=leadId||'';$('#duplicateBox').hidden=true;d.showModal()}
function quickPayload(){return{nome:$('#qNome').value.trim(),cognome:$('#qCognome').value.trim(),telefono:$('#qTelefono').value.trim(),email:$('#qEmail').value.trim(),comune:$('#qComune').value.trim(),via:$('#qVia').value.trim(),source:'CRM_OS',source_type:'NETWORK',status:'DA_ANALIZZARE',notes:$('#qNote').value.trim(),lead_score:50,confidence:'LOW',rpo_status:'DA_VERIFICARE',privacy_basis:'CRM_OS_MANUAL',created_by:'CRM_OS'}}
async function saveQuick(e){e.preventDefault();const type=$('#quickType').value,leadId=$('#quickLeadId').value;if(['TELEFONATA','APPUNTAMENTO','NOTA'].includes(type)){if(!leadId){setStatus('Apri prima una scheda contatto per registrare questa attività.','err');return}await saveInteraction(type,leadId);$('#quickDlg').close();await refresh();openContact(leadId);return}const p=quickPayload();if(!p.nome&&!p.cognome&&!p.telefono&&!p.email){setStatus('Inserisci almeno nome, telefono o email.','err');return}const cand=await F1StaffData.rpc('f1_find_duplicate_candidates',{p_payload:p});if(cand?.length){state.pendingLead={payload:p,type};state.duplicateCandidates=cand;renderDuplicateChoices(cand);return}await createNewLead(p,type,false)}
function renderDuplicateChoices(cand){$('#duplicateBox').hidden=false;$('#duplicateBox').innerHTML=`<div class="dup-alert"><b>POSSIBILE DUPLICATO</b><p>Il sistema non crea automaticamente un secondo record.</p>${cand.map((c,i)=>`<article><strong>${esc(c.display_name||c.lead_id)}</strong><span>${esc(c.comune||'')} · corrispondenza ${esc((c.matched_by||[]).join(', '))}</span><div class="actions"><button type="button" data-dup-open="${esc(c.lead_id)}">APRI ESISTENTE</button><button type="button" class="primary" data-dup-merge="${esc(c.lead_id)}">UNISCI NELL'ESISTENTE</button>${i===0?'<button type="button" data-dup-force="1">CREA COMUNQUE</button>':''}</div></article>`).join('')}</div>`;bindDynamic()}
async function mergeIncoming(id){const p=state.pendingLead?.payload;if(!p)return;const old=leadById(id)||{};const patch={};for(const [k,v] of Object.entries({nome:p.nome,cognome:p.cognome,telefono:p.telefono,email:p.email,comune:p.comune,via:p.via,notes:p.notes})){if(v&&!old[k])patch[k]=v}patch.updated_at=new Date().toISOString();patch.last_modified_by_user_id=state.me.user_id;await F1StaffData.rest('leads?lead_id=eq.'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify(patch),prefer:'return=representation'});await F1StaffData.createOrLinkLead({...p,notes:p.notes||'Dati in ingresso uniti alla scheda esistente'});$('#quickDlg').close();state.pendingLead=null;await refresh();openContact(id);setStatus('Dati collegati al contatto esistente.','ok')}
async function createNewLead(p,type,force){const id=crypto.randomUUID(),row={lead_id:id,user_id:state.me.user_id,pillar:1,source_type:p.source_type,source:p.source,source_url:'',nome:p.nome,cognome:p.cognome,azienda:'',telefono:p.telefono,email:p.email,comune:p.comune,via:p.via,civico:'',zona:'',immobile_id:'',competitor_agency:'',lead_reason:'CRM_OS_MANUAL',lead_score:50,confidence:'LOW',status:'DA_ANALIZZARE',next_action:'',assigned_to:'',notes:p.notes,privacy_basis:'CRM_OS_MANUAL',do_not_contact:false,rpo_status:'DA_VERIFICARE',created_by:'CRM_OS',created_by_user_id:state.me.user_id,last_modified_by_user_id:state.me.user_id,assigned_user_id:state.me.user_id,updated_at:new Date().toISOString(),deleted:false};await F1StaffData.rest('leads',{method:'POST',body:JSON.stringify([row]),prefer:'return=representation'});if(force&&state.duplicateCandidates?.[0])await F1StaffData.rest('f1_duplicate_events',{method:'POST',body:JSON.stringify([{user_id:state.me.user_id,attempted_lead_id:id,existing_lead_id:state.duplicateCandidates[0].lead_id,matched_by:state.duplicateCandidates[0].matched_by||[],source:'CRM_OS_FORCE_CREATE',metadata:{decision:'CREATE_ANYWAY'}}]),prefer:'return=representation'});const role=type==='PROPRIETARIO'?'PROPRIETARIO':type==='ACQUIRENTE'?'ACQUIRENTE':'PROSPECT';await addRole(id,role,true);$('#quickDlg').close();state.pendingLead=null;state.duplicateCandidates=[];await refresh();openContact(id);setStatus(force?'Nuovo record creato dopo conferma duplicato.':'Contatto creato.','ok')}
async function addRole(id,role,isPrimary=false){const current=state.roles.find(r=>r.lead_id===id&&r.role_type===role);if(current)return current;const stage=(state.cfg.pipelines[role]||[])[0]||'';const rows=await F1StaffData.rest('f1_contact_roles',{method:'POST',body:JSON.stringify([{lead_id:id,role_type:role,role_status:'ACTIVE',pipeline_stage:stage,is_primary:isPrimary,created_by_user_id:state.me.user_id,source:'CRM_OS'}]),prefer:'return=representation'});return rows?.[0]}
async function rolePrompt(id){const role=window.prompt('Ruolo: '+state.cfg.roles.join(' / '),'PROPRIETARIO');if(!role)return;const r=upper(role.trim());if(!state.cfg.roles.includes(r)){setStatus('Ruolo non valido.','err');return}await addRole(id,r,false);await refresh();openContact(id)}
async function setRoleStage(roleId,stage){await F1StaffData.rest('f1_contact_roles?role_id=eq.'+encodeURIComponent(roleId),{method:'PATCH',body:JSON.stringify({pipeline_stage:stage,updated_at:new Date().toISOString()}),prefer:'return=representation'});await refresh();if(state.selectedLead)openContact(state.selectedLead)}
async function saveInteraction(type,leadId){const map={TELEFONATA:'CALL',APPUNTAMENTO:'MEETING',NOTA:'NOTE'},out={TELEFONATA:'TELEFONATA_REGISTRATA',APPUNTAMENTO:'APPUNTAMENTO_PROGRAMMATO',NOTA:'NOTA'};await F1StaffData.rest('interactions',{method:'POST',body:JSON.stringify([{user_id:state.me.user_id,lead_id:leadId,property_id:'',interaction_type:map[type]||'NOTE',direction:'OUTBOUND',occurred_at:new Date().toISOString(),outcome:out[type]||type,note:$('#qNote').value.trim(),next_action:'',metadata:{origin:'CRM_OS_QUICK_ACTION'}}]),prefer:'return=representation'})}
async function completeTask(id){await F1StaffData.rest('tasks?task_id=eq.'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify({status:'DONE',completed_at:new Date().toISOString(),updated_at:new Date().toISOString()}),prefer:'return=representation'});await refresh();renderToday();bindDynamic();setStatus('Task completato.','ok')}
async function rescheduleTask(id){const t=state.tasks.find(x=>String(x.task_id)===String(id));if(!t)return;const base=t.due_date?new Date(t.due_date):new Date();base.setDate(base.getDate()+1);await F1StaffData.rest('tasks?task_id=eq.'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify({due_date:base.toISOString(),updated_at:new Date().toISOString()}),prefer:'return=representation'});await refresh();renderToday();bindDynamic();setStatus('Task riprogrammato di 1 giorno.','ok')}
function bindDynamic(){
  $$('[data-open-contact]').forEach(b=>b.onclick=()=>{const id=b.dataset.openContact;if(id)openContact(id)});
  $$('[data-complete-task]').forEach(b=>b.onclick=()=>completeTask(b.dataset.completeTask));
  $$('[data-reschedule-task]').forEach(b=>b.onclick=()=>rescheduleTask(b.dataset.rescheduleTask));
  $$('[data-role-add]').forEach(b=>b.onclick=()=>rolePrompt(b.dataset.roleAdd));
  $$('[data-role-stage]').forEach(s=>s.onchange=()=>setRoleStage(s.dataset.roleStage,s.value));
  $$('[data-pipeline]').forEach(b=>b.onclick=()=>{renderPipeline(b.dataset.pipeline);bindDynamic()});
  $$('[data-quick]').forEach(b=>b.onclick=()=>openQuick(b.dataset.quick));
  $$('[data-quick-note]').forEach(b=>b.onclick=()=>openQuick('NOTA',b.dataset.quickNote));
  $$('[data-dup-open]').forEach(b=>b.onclick=()=>{$('#quickDlg').close();openContact(b.dataset.dupOpen)});
  $$('[data-dup-merge]').forEach(b=>b.onclick=()=>mergeIncoming(b.dataset.dupMerge));
  $$('[data-dup-force]').forEach(b=>b.onclick=()=>createNewLead(state.pendingLead.payload,state.pendingLead.type,true));
  $$('.search-hit').forEach(b=>b.onclick=()=>{const t=b.dataset.searchType,id=b.dataset.searchId,lead=b.dataset.searchLead;$('#searchResults').hidden=true;if(t==='CONTATTO')openContact(id);else if(lead)openContact(lead);else if(t==='IMMOBILE'){const p=state.properties.find(x=>x.property_id===id);$('#mainTitle').textContent=p?.tipologia||'IMMOBILE';$('#mainBody').innerHTML='<section class="panel">'+propertyHtml(p)+'</section>'}});
}
async function refresh(){await loadData();agenda();renderIdentity()}
function staticBindings(){
  $$('[data-view]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();showView(b.dataset.view)}));
  $('#globalSearch').addEventListener('input',e=>renderSearch(e.target.value));
  $('#refreshAll').addEventListener('click',async()=>{setStatus('Aggiornamento…');await refresh();showView(state.view);setStatus('Dati aggiornati.','ok')});
  $('#quickOpen').addEventListener('click',()=>openQuick('CONTATTO'));
  $('#quickForm').addEventListener('submit',saveQuick);
  $('#quickCancel').addEventListener('click',()=>$('#quickDlg').close());
  $('#logoutBtn').addEventListener('click',async()=>{await F1Sync.signOut();location.replace('setup-cloud.html?return=f1-crm-os.html')});
}
async function boot(){try{state.cfg=await loadConfig();if(!(await auth()))return;await loadData();renderIdentity();agenda();staticBindings();const params=new URLSearchParams(location.search),contact=params.get('contact');if(contact)openContact(contact);else showView('today');setStatus('CRM OS connesso a Supabase · fallback crm.html disponibile.','ok')}catch(e){console.error(e);setStatus('ERRORE · '+(e.message||e),'err');$('#mainBody').innerHTML=`<section class="panel error"><h2>CRM OS non disponibile</h2><p>${esc(e.message||e)}</p><a class="button" href="crm.html">APRI CRM CLASSICO</a></section>`}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
