(()=>{'use strict';
const VERSION='20260916-mobile1';
const $=id=>document.getElementById(id),$$=s=>[...document.querySelectorAll(s)],txt=v=>String(v??'').trim(),up=v=>txt(v).toUpperCase();
let state=null,profile=null,progress=null,civic='',busy=false,flushing=false,geo=null;
let observePhotoBlob=null,newsPhotoBlob=null;
const SCRIPT_BY_TYPE={
  RESIDENTE:'Presentati in modo semplice. Spiega che stai conoscendo la zona e chiedi se è a conoscenza di persone che stanno valutando un trasferimento o una vendita. Registra soltanto ciò che ti viene realmente riferito.',
  COMMERCIANTE:'Presentati e spiega che stai aggiornando la conoscenza della zona. Chiedi se ha notato movimenti, cambi di abitazione o persone che potrebbero avere una necessità immobiliare.',
  PORTINAIO:'Spiega che stai facendo attività territoriale. Chiedi soltanto informazioni che la persona è libera di condividere e registra i fatti senza supposizioni.',
  AMMINISTRATORE:'Presentati e chiedi se ci sono situazioni immobiliari per cui qualcuno potrebbe voler essere ricontattato. Non chiedere dati riservati non necessari.',
  PROPRIETARIO:'Ascolta prima la situazione. Chiedi se sta valutando un cambiamento, in quali tempi e se desidera essere ricontattato. Non fare promesse.',
  ALTRO:'Presentati in modo semplice, spiega che stai conoscendo il territorio e chiedi se la persona è a conoscenza di movimenti immobiliari nella zona.'
};
function setText(id,v){const e=$(id);if(e)e.textContent=v}
function setStatus(id,message,kind=''){const e=$(id);if(!e)return;e.textContent=message;e.className='status'+(kind?' '+kind:'')}
function formStatus(form,message,bad=false){const e=form.querySelector('[data-form-status]');if(e){e.textContent=message;e.className='status'+(bad?' err':'')}}
function showSheet(id){const e=$(id);if(e)e.classList.remove('hidden')}
function hideSheet(id){const e=$(id);if(e)e.classList.add('hidden')}
function currentProgress(){return state?.territory?.progress||null}
function currentCivic(p=currentProgress()){return txt(p?.next_civic||p?.civic_start||'')}
function nextAfter(p=currentProgress()){const seq=Array.isArray(p?.civic_sequence)?p.civic_sequence.map(String):[],cur=currentCivic(p),i=seq.indexOf(cur);return i>=0&&i<seq.length-1?seq[i+1]:''}
function address(p=currentProgress(),withCivic=false){if(!p)return'';return[p.comune,p.zona,p.via,withCivic&&currentCivic(p)?'civico '+currentCivic(p):''].map(txt).filter(Boolean).join(' · ')}
function escapeHtml(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function isNetworkError(e){return !navigator.onLine||/fetch|network|connessione|timeout|tempo massimo|offline|failed/i.test(String(e?.message||e))}
function setBusy(on){busy=!!on;['primaryAction','startCivicBtn','pauseBtn','nothingBtn','observeBtn','personBtn','newsBtn','propertyBtn','syncBtn'].forEach(id=>{const e=$(id);if(e)e.disabled=busy})}
function showView(name){$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.view===name));$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));window.scrollTo({top:0,behavior:'smooth'})}
function clock(){setText('clock',new Intl.DateTimeFormat('it-IT',{timeZone:'Europe/Rome',hour:'2-digit',minute:'2-digit'}).format(new Date()))}
async function updateNetworkUI(){
  const pending=await F1MobileStore.pendingCount().catch(()=>0),conflict=await F1MobileStore.getConflict().catch(()=>null),online=navigator.onLine;
  $('offlineBanner').classList.toggle('hidden',online);$('conflictBanner').classList.toggle('hidden',!conflict);
  const live=window.F1Realtime?.status?.()||'IDLE',sync=$('syncState');
  sync.className='sync '+(online&&live==='LIVE'?'live':!online?'offline':'');
  sync.textContent=!online?`OFFLINE${pending?' · '+pending:''}`:conflict?'CONFLITTO':pending?`${pending} IN CODA`:live==='LIVE'?'LIVE':'ONLINE';
  setText('syncDetail',conflict?'CONFLITTO DA VERIFICARE · sincronizzazione automatica sospesa.':!online?`${pending} modifiche in coda locale.`:pending?`${pending} modifiche da sincronizzare.`:live==='LIVE'?'PC e mobile collegati in tempo reale.':'Connessione attiva. Realtime in verifica.');
}
function render(){
  progress=currentProgress();civic=currentCivic(progress);const s=state?.territory?.summary||{},pending=state?.territory?.pending_news||[],i=state?.instruction||window.F1NotiziereEngine?.instructionFrom?.(state)||null;
  const loc=address(progress)||'Nessun giro territoriale assegnato';setText('todayLocation',loc);setText('zoneLocation',loc);setText('zoneStreet',txt(progress?.via)||'—');
  setText('lastCivic',txt(progress?.last_civic)||'—');setText('afterCivic',nextAfter(progress)||'—');setText('zoneCurrent',civic||'—');setText('zoneLast',txt(progress?.last_civic)||'—');
  setText('todayTitle',txt(progress?.via)||'F1 TERRITORY');
  setText('kpiCivics',Number(s.civics||0));setText('kpiContacts',Number(s.contacts||0));setText('kpiNews',Number(s.news||0));setText('kpiCallbacks',Number(s.callbacks||0));
  const primary=$('primaryAction');
  if(i){setText('nowTitle',i.title||'—');setText('nowDetail',i.detail||'Segui l’ordine operativo F1.');setText('todayInstruction',i.nextTitle||'F1 salverà l’esito e calcolerà il passo successivo.');primary.textContent=i.cta||'APRI ATTIVITÀ';primary.disabled=false;primary.dataset.kind=i.kind||'';primary.dataset.href=i.href||''}
  else{setText('nowTitle','NESSUNA ISTRUZIONE');setText('nowDetail','Aggiorna i dati o attendi una nuova assegnazione.');primary.textContent='AGGIORNA';primary.disabled=false;primary.dataset.kind='REFRESH'}
  $('startCivicBtn').disabled=!progress||!civic;$('startCivicBtn').textContent=civic?`INIZIA CIVICO ${civic}`:'NESSUN CIVICO ASSEGNATO';$('pauseBtn').disabled=!progress||!civic;
  if(progress&&civic){$('mapBtn').href=F1NotiziereEngine.mapUrl(progress);$('mapBtn').style.pointerEvents=''}else{$('mapBtn').removeAttribute('href');$('mapBtn').style.pointerEvents='none'}
  setText('civicSheetTitle',`CIVICO ${civic||'—'}`);setText('civicAddress',address(progress));renderNews(pending);updateNetworkUI();
}
function renderNews(rows){const e=$('newsList');if(!e)return;if(!rows?.length){e.innerHTML='<div class="item"><strong>Nessuna notizia pendente</strong><p>Le notizie raccolte compariranno qui e sul PC.</p></div>';return}e.innerHTML=rows.map(r=>`<div class="item"><strong>${escapeHtml(txt(r.news_type||r.observation_type||'NOTIZIA').replaceAll('_',' '))}</strong><p>${escapeHtml([r.via,r.civico&&'civico '+r.civico].filter(Boolean).join(' · '))}<br>${escapeHtml(r.detail||'')}</p><div class="row">${r.next_action?`<span class="chip">ADESSO: ${escapeHtml(r.next_action)}</span>`:''}<a class="btn slim" href="crm.html?territory_observation=${encodeURIComponent(r.observation_id)}#territory-news">APRI</a></div></div>`).join('')}
async function loadCached(){const c=await F1MobileStore.cachedState();if(c){state=c;render();return true}return false}
async function loadRemote(force=true){if(!navigator.onLine)return loadCached();if(!window.F1Sync?.configured?.()||!await F1Sync.ensureSession())return false;profile=profile||await F1StaffData.me();const remote=await F1NotiziereEngine.load({force}),pending=await F1MobileStore.pendingCount();if(pending&&!flushing){const local=await F1MobileStore.cachedState();if(local){state=local;render();return true}}state=remote;await F1MobileStore.cacheState(remote);await F1MobileStore.set('serverProgressUpdatedAt',remote?.territory?.progress?.updated_at||'');await F1MobileStore.setConflict(null);render();return true}
function helpForCurrent(){const i=state?.instruction,p=currentProgress();if(i?.kind==='CIVIC')return`Sei in ${address(p,true)}. Premi INIZIA CIVICO ${currentCivic(p)}, controlla edificio, attività e persone. Registra ciò che succede; se non emerge nulla premi NESSUNA INFORMAZIONE.`;if(i?.kind==='CRM_PENDING')return'Hai dati territoriali già raccolti da verificare. Apri NOTIZIE e completa quelli pendenti prima del consuntivo.';if(i?.kind==='NO_ASSIGNMENT')return'Non hai un giro assegnato. Non inventare una zona: aggiorna i dati o attendi l’assegnazione dal responsabile.';return i?.detail||'Segui il pulsante principale: F1 determina il passo successivo.'}
function openCurrentCivic(){if(!progress||!civic){setStatus('mainStatus','Nessun civico assegnato.','warn');return}setText('civicSheetTitle',`CIVICO ${civic}`);setText('civicAddress',address(progress));showSheet('civicSheet')}
function primaryAction(){const kind=$('primaryAction').dataset.kind,href=$('primaryAction').dataset.href;if(kind==='CIVIC')return openCurrentCivic();if(kind==='CRM_PENDING'){showView('notizie');return}if(kind==='REFRESH'||kind==='NO_ASSIGNMENT')return loadRemote(true);if(href&&href!=='#'){location.href=href;return}loadRemote(true)}
async function coords(){if(!navigator.geolocation)throw new Error('GPS NON DISPONIBILE');if(!isSecureContext)throw new Error('GPS RICHIEDE HTTPS');return new Promise((resolve,reject)=>navigator.geolocation.getCurrentPosition(p=>resolve({latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy}),e=>reject(new Error(({1:'PERMESSO GPS NEGATO',2:'POSIZIONE NON DISPONIBILE',3:'TIMEOUT GPS'})[e.code]||'ERRORE GPS')),{enableHighAccuracy:true,timeout:12000,maximumAge:30000}))}
async function locate(){setStatus('gpsStatus','Rilevamento posizione…');try{geo=await coords();setStatus('gpsStatus',`✓ POSIZIONE RILEVATA · precisione ±${Math.round(geo.accuracy)} m`);heartbeat()}catch(e){setStatus('gpsStatus',String(e.message||e),'err')}}
async function heartbeat(statusOverride=''){if(!navigator.onLine||!profile?.user_id||!window.F1StaffData?.ready?.())return false;const p=currentProgress(),status=statusOverride||(p?.status==='DA_CONSUNTIVARE'?'FINE_GIRO':'OPERATIVO'),c=geo||{};try{await F1StaffData.rest('f1_mobile_presence?on_conflict=user_id',{method:'POST',body:JSON.stringify([{user_id:profile.user_id,device_id:F1Sync.deviceId(),status,progress_id:p?.progress_id||null,current_civic:currentCivic(p),latitude:c.latitude??null,longitude:c.longitude??null,last_seen_at:new Date().toISOString(),updated_at:new Date().toISOString()}]),prefer:'resolution=merge-duplicates,return=representation'});return true}catch(e){console.warn('[F1 presence]',e);return false}}
function deriveNewsAction(v){if(!v.has_location)return{state:'DA_LOCALIZZARE',next:'LOCALIZZA IMMOBILE'};if(!v.knows_owner)return{state:'PROPRIETARIO_DA_IDENTIFICARE',next:'IDENTIFICA PROPRIETARIO'};if(!v.has_name)return{state:'IDENTITA_DA_COMPLETARE',next:'COMPLETA IDENTITÀ PROPRIETARIO'};if(!v.has_contact)return{state:'RECAPITO_DA_TROVARE',next:'CERCA RECAPITO'};if(!v.talked_owner)return{state:'DA_CONTATTARE',next:'CONTATTA PROPRIETARIO'};return{state:'DA_QUALIFICARE',next:'QUALIFICA ESIGENZA'}}
async function runOperation(row){const p=row.payload||{};if(row.type==='OBSERVATION')return F1NotiziereEngine.addObservation(p.progress_id,p.data);if(row.type==='NEWS')return F1StaffData.rpc('f1_territory_mobile_add_news',p.rpc);if(row.type==='PERSON'){if(p.anonymous)return F1NotiziereEngine.addObservation(p.progress_id,p.observation);const saved=await F1StaffData.createOrLinkLead(p.lead);await F1NotiziereEngine.registerContact(p.progress_id);return saved}if(row.type==='COMPLETE'){await F1NotiziereEngine.addObservation(p.progress_id,{observation_type:'ESITO_CIVICO',detail:p.outcome==='NESSUNA_NOVITA'?'Nessuna informazione utile rilevata durante il passaggio al civico.':'Dati registrati durante il lavoro del civico.',source:'NOTIZIERE MOBILE',notes:`ESITO MINIMO: ${p.outcome}`,status:'OSSERVAZIONE'});return F1NotiziereEngine.completeCivic(p.progress_id,p.expected_civic)}if(row.type==='PAUSE')return F1NotiziereEngine.pause(p.progress_id,p.expected_civic);if(row.type==='PHOTO')return uploadPhoto(p);throw new Error('OPERAZIONE MOBILE NON RICONOSCIUTA: '+row.type)}
async function queueOrRun(type,payload,{optimistic}={}){if(navigator.onLine){try{return await runOperation({type,payload})}catch(e){if(!isNetworkError(e))throw e}}const q=await F1MobileStore.enqueue(type,payload);if(optimistic)await optimistic(q);await updateNetworkUI();return{queued:true,id:q.id}}
async function flushOutbox(){if(flushing||!navigator.onLine)return;const conflict=await F1MobileStore.getConflict();if(conflict){setStatus('mainStatus','CONFLITTO DA VERIFICARE · sincronizzazione sospesa.','warn');return}flushing=true;setBusy(true);try{if(!window.F1Sync?.configured?.()||!await F1Sync.ensureSession())throw new Error('ACCESSO CLOUD RICHIESTO');profile=profile||await F1StaffData.me();const rows=await F1MobileStore.listOutbox();for(const r of rows){if(r.status==='SYNCED')continue;await F1MobileStore.patchOutbox(r.id,{status:'SYNCING',attempts:Number(r.attempts||0)+1});try{await runOperation(r);await F1MobileStore.removeOutbox(r.id)}catch(e){await F1MobileStore.patchOutbox(r.id,{status:'ERROR',last_error:String(e?.message||e)});throw e}}await loadRemote(true);setStatus('mainStatus','✓ DATI SINCRONIZZATI CON IL PC.');heartbeat()}catch(e){setStatus('mainStatus','SINCRONIZZAZIONE NON COMPLETATA · '+String(e?.message||e),isNetworkError(e)?'warn':'err')}finally{flushing=false;setBusy(false);updateNetworkUI()}}
async function saveNothing(){if(busy||!progress||!civic)return;setBusy(true);setStatus('civicStatus','SALVATAGGIO CIVICO…');const pid=progress.progress_id,expected=civic;try{const result=await queueOrRun('COMPLETE',{progress_id:pid,expected_civic:expected,outcome:'NESSUNA_NOVITA'},{optimistic:async()=>{state=F1MobileStore.optimisticComplete(state,expected);await F1MobileStore.cacheState(state);render()}});if(!result?.queued)await loadRemote(true);else{progress=currentProgress();civic=currentCivic(progress)}hideSheet('civicSheet');setStatus('mainStatus',`✓ CIVICO ${expected} REGISTRATO · ${currentCivic(progress)?'ORA VAI AL CIVICO '+currentCivic(progress):'GIRO DA CONSUNTIVARE'}.`);showView('oggi');heartbeat(currentCivic(progress)?'OPERATIVO':'FINE_GIRO')}catch(e){setStatus('civicStatus','SALVATAGGIO NON COMPLETATO · '+String(e?.message||e),'err')}finally{setBusy(false)}}
async function compressImage(file){if(!file)return null;if(file.size>8*1024*1024)throw new Error('FOTO TROPPO GRANDE');if(!file.type.startsWith('image/'))throw new Error('FILE NON IMMAGINE');try{const bmp=await createImageBitmap(file),max=1280,scale=Math.min(1,max/Math.max(bmp.width,bmp.height)),w=Math.round(bmp.width*scale),h=Math.round(bmp.height*scale),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;canvas.getContext('2d').drawImage(bmp,0,0,w,h);const blob=await new Promise((res,rej)=>canvas.toBlob(b=>b?res(b):rej(new Error('COMPRESSIONE FOTO FALLITA')),'image/jpeg',.74));bmp.close?.();return blob}catch(_){return file}}
function previewFile(input,imgId,setter){const f=input.files?.[0];if(!f){setter(null);$(imgId).classList.add('hidden');return}compressImage(f).then(blob=>{setter(blob);const img=$(imgId);img.src=URL.createObjectURL(blob);img.classList.remove('hidden')}).catch(e=>setStatus('mainStatus',String(e.message||e),'err'))}
async function uploadPhoto(p){if(!p.blob)throw new Error('FOTO MANCANTE');profile=profile||await F1StaffData.me();const cfg=window.F1_SUPABASE||{},token=await F1Sync.authToken(),ext=p.blob.type==='image/png'?'png':p.blob.type==='image/webp'?'webp':'jpg',path=`${profile.user_id}/${p.progress_id}/${crypto.randomUUID()}.${ext}`,encoded=path.split('/').map(encodeURIComponent).join('/');const res=await fetch(cfg.url.replace(/\/$/,'')+'/storage/v1/object/f1-territory-photos/'+encoded,{method:'POST',headers:{apikey:cfg.anonKey,Authorization:'Bearer '+token,'Content-Type':p.blob.type||'image/jpeg','x-upsert':'false'},body:p.blob});if(!res.ok)throw new Error('UPLOAD FOTO '+res.status+': '+await res.text());const rows=await F1StaffData.rest('f1_territory_photos',{method:'POST',body:JSON.stringify([{user_id:profile.user_id,progress_id:p.progress_id,observation_id:p.observation_id||null,civico:p.civico||'',kind:p.kind||'OSSERVAZIONE',storage_path:path,mime_type:p.blob.type||'image/jpeg',latitude:p.latitude??null,longitude:p.longitude??null}]),prefer:'return=representation'});return rows?.[0]||{storage_path:path}}
async function saveObservation(ev){ev.preventDefault();if(busy||!progress)return;const form=ev.currentTarget;if(!form.reportValidity())return;const fd=new FormData(form),pid=progress.progress_id,cur=civic,data={observation_type:txt(fd.get('observation_type')),detail:txt(fd.get('detail')),source:'NOTIZIERE MOBILE',notes:txt(fd.get('notes')),status:'OSSERVAZIONE'};setBusy(true);formStatus(form,'SALVATAGGIO…');try{const r=await queueOrRun('OBSERVATION',{progress_id:pid,data});if(observePhotoBlob){const c=geo||{};await queueOrRun('PHOTO',{progress_id:pid,observation_id:r?.observation_id||null,civico:cur,kind:'OSSERVAZIONE',blob:observePhotoBlob,latitude:c.latitude??null,longitude:c.longitude??null})}form.reset();observePhotoBlob=null;$('observePreview').classList.add('hidden');hideSheet('observeSheet');setStatus('civicStatus',r?.queued?'✓ OSSERVAZIONE SALVATA SUL TELEFONO · DA SINCRONIZZARE.':'✓ OSSERVAZIONE SALVATA · CONTINUA QUESTO CIVICO.');if(!r?.queued)await loadRemote(true)}catch(e){formStatus(form,'NON SALVATO · '+String(e?.message||e),true)}finally{setBusy(false)}}
function personPayload(form){const fd=new FormData(form),outcome=txt(fd.get('outcome')),rule=F1NotiziereEngine.personRule(outcome,fd.get('callback_date')),nome=txt(fd.get('nome')),cognome=txt(fd.get('cognome')),telefono=txt(fd.get('telefono')),email=txt(fd.get('email')),notes=txt(fd.get('notes')),ptype=txt(fd.get('person_type')||'ALTRO');if(!nome&&!cognome&&!telefono&&!email)return{anonymous:true,progress_id:progress.progress_id,observation:{observation_type:'PERSONA_ANONIMA',detail:`Conversazione al civico. Tipo: ${ptype}. Esito: ${outcome}.${notes?' '+notes:''}`,source:'NOTIZIERE MOBILE',notes:'Nessun identificativo personale raccolto.',status:'OSSERVAZIONE'},rule};return{anonymous:false,progress_id:progress.progress_id,lead:{nome,cognome,telefono,email,comune:txt(progress.comune),zona:txt(progress.zona),via:[txt(progress.via),civic].filter(Boolean).join(' '),source_type:'TERRITORY',source:'NOTIZIERE_MOBILE',lead_reason:`ESITO_GUIDATO_${outcome}`,notes:[`Tipo persona: ${ptype}`,`Esito guidato: ${outcome}`,notes].filter(Boolean).join('\n'),status:rule.status,next_action:rule.next_action,next_action_date:rule.next_action_date||'',do_not_contact:!!rule.do_not_contact,created_by:[profile?.first_name,profile?.last_name].filter(Boolean).join(' ')},rule}}
async function savePerson(ev){ev.preventDefault();if(busy||!progress)return;const form=ev.currentTarget;if(!form.reportValidity())return;setBusy(true);formStatus(form,'REGISTRAZIONE…');try{const p=personPayload(form),r=await queueOrRun('PERSON',p);form.reset();$('callbackDate').classList.add('hidden');hideSheet('personSheet');setStatus('civicStatus',`${r?.queued?'✓ PERSONA SALVATA SUL TELEFONO':'✓ PERSONA REGISTRATA'} · PROSSIMA AZIONE: ${p.rule.next_action}.`);if(!r?.queued)await loadRemote(true)}catch(e){formStatus(form,'NON SALVATO · '+String(e?.message||e),true)}finally{setBusy(false)}}
async function saveNews(ev){ev.preventDefault();if(busy||!progress)return;const form=ev.currentTarget;if(!form.reportValidity())return;const fd=new FormData(form),vals={has_location:fd.get('has_location')==='YES',knows_owner:fd.get('knows_owner')==='YES',has_name:fd.get('has_name')==='YES',has_contact:fd.get('has_contact')==='YES',talked_owner:fd.get('talked_owner')==='YES'},rule=deriveNewsAction(vals),rpc={p_progress_id:progress.progress_id,p_detail:txt(fd.get('detail')),p_source:txt(fd.get('source')||'NOTIZIERE MOBILE'),p_person_name:txt(fd.get('person_name')),p_phone:txt(fd.get('phone')),p_has_location:vals.has_location,p_knows_owner:vals.knows_owner,p_has_name:vals.has_name,p_has_contact:vals.has_contact,p_talked_owner:vals.talked_owner},pid=progress.progress_id,cur=civic;setBusy(true);formStatus(form,'SALVATAGGIO NOTIZIA…');try{const r=await queueOrRun('NEWS',{rpc},{optimistic:async()=>{const fake={observation_id:'local-'+crypto.randomUUID(),progress_id:pid,observed_at:new Date().toISOString(),observation_type:'NOTIZIA_IMMOBILIARE',news_type:'DA_CLASSIFICARE',comune:progress.comune,zona:progress.zona,via:progress.via,civico:cur,detail:rpc.p_detail,source:rpc.p_source,person_name:rpc.p_person_name,status:'DA_INSERIRE_CRM',workflow_state:rule.state,next_action:rule.next,priority:'ALTA'};state.territory.pending_news=[...(state.territory.pending_news||[]),fake];state.territory.summary.news=Number(state.territory.summary.news||0)+1;await F1MobileStore.cacheState(state);render()}});if(newsPhotoBlob){const c=geo||{};await queueOrRun('PHOTO',{progress_id:pid,observation_id:r?.observation_id||null,civico:cur,kind:'NOTIZIA',blob:newsPhotoBlob,latitude:c.latitude??null,longitude:c.longitude??null})}form.reset();newsPhotoBlob=null;$('newsPreview').classList.add('hidden');hideSheet('newsSheet');setStatus('civicStatus',`${r?.queued?'✓ NOTIZIA SALVATA SUL TELEFONO':'✓ NOTIZIA SALVATA'} · PROSSIMA AZIONE: ${r?.next_action||rule.next}.`);if(!r?.queued)await loadRemote(true)}catch(e){formStatus(form,'NON SALVATO · '+String(e?.message||e),true)}finally{setBusy(false)}}
async function pauseTour(){if(busy||!progress||!civic)return;setBusy(true);try{const r=await queueOrRun('PAUSE',{progress_id:progress.progress_id,expected_civic:civic});hideSheet('civicSheet');setStatus('mainStatus',r?.queued?`✓ PAUSA SALVATA SUL TELEFONO · RIPARTI DAL CIVICO ${civic}.`:`✓ GIRO IN PAUSA · RIPARTI DAL CIVICO ${civic}.`);showView('oggi');heartbeat('IN_PAUSA');if(!r?.queued)await loadRemote(true)}catch(e){setStatus('mainStatus','PAUSA NON SALVATA · '+String(e?.message||e),'err')}finally{setBusy(false)}}
function dictate(targetId){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){setStatus('mainStatus','DETTATURA NON SUPPORTATA SU QUESTO BROWSER · usa la tastiera.','warn');return}const r=new SR();r.lang='it-IT';r.interimResults=false;r.maxAlternatives=1;r.onresult=e=>{const field=$(targetId);field.value=(field.value?field.value+' ':'')+e.results[0][0].transcript};r.onerror=e=>setStatus('mainStatus','DETTATURA NON DISPONIBILE · '+e.error,'warn');r.start()}
function updatePhoneActions(){const form=$('personForm'),phone=txt(form.elements.telefono.value),old=$('phoneActions');old?.remove();if(!phone)return;const clean=phone.replace(/[^0-9+]/g,''),wa=phone.replace(/\D/g,''),d=document.createElement('div');d.id='phoneActions';d.className='grid2';d.innerHTML=`<a class="btn slim" href="tel:${escapeHtml(clean)}">☎ CHIAMA</a><a class="btn slim" target="_blank" rel="noopener" href="https://wa.me/${escapeHtml(wa)}">WHATSAPP</a>`;form.elements.telefono.closest('.grid2').after(d)}
function wire(){
  $$('.tab').forEach(b=>b.onclick=()=>showView(b.dataset.tab));$$('[data-close]').forEach(b=>b.onclick=()=>hideSheet(b.dataset.close));
  $('primaryAction').onclick=primaryAction;$('startCivicBtn').onclick=openCurrentCivic;$('gpsBtn').onclick=locate;$('helpBtn').onclick=()=>setText('helpText',helpForCurrent());$('syncBtn').onclick=flushOutbox;
  $('nothingBtn').onclick=saveNothing;$('observeBtn').onclick=()=>showSheet('observeSheet');$('personBtn').onclick=()=>showSheet('personSheet');$('newsBtn').onclick=()=>showSheet('newsSheet');$('propertyBtn').onclick=()=>{const f=$('observeForm');f.elements.observation_type.value='POSSIBILE_IMMOBILE';$('observeText').placeholder='Descrivi perché questo immobile richiede attenzione';showSheet('observeSheet')};$('pauseBtn').onclick=pauseTour;
  $('observeForm').onsubmit=saveObservation;$('personForm').onsubmit=savePerson;$('newsForm').onsubmit=saveNews;
  $('personForm').elements.outcome.onchange=e=>{$('callbackDate').classList.toggle('hidden',e.target.value!=='CALLBACK');if(e.target.value!=='CALLBACK')$('callbackDate').value=''};$('personForm').elements.telefono.oninput=updatePhoneActions;
  $('scriptBtn').onclick=()=>{const t=up($('personForm').elements.person_type.value)||'ALTRO';setText('scriptText',SCRIPT_BY_TYPE[t]||SCRIPT_BY_TYPE.ALTRO);showSheet('scriptSheet')};$$('[data-dictate]').forEach(b=>b.onclick=()=>dictate(b.dataset.dictate));
  $('observePhoto').onchange=e=>previewFile(e.target,'observePreview',b=>observePhotoBlob=b);$('newsPhoto').onchange=e=>previewFile(e.target,'newsPreview',b=>newsPhotoBlob=b);
  addEventListener('online',async()=>{updateNetworkUI();await flushOutbox();window.F1Realtime?.start?.()});addEventListener('offline',updateNetworkUI);addEventListener('f1:outbox-change',updateNetworkUI);addEventListener('f1:realtime-status',updateNetworkUI);
  addEventListener('f1:realtime-change',async ev=>{if(flushing)return;const pending=await F1MobileStore.pendingCount();if(pending){const cached=await F1MobileStore.cachedState(),rp=ev.detail?.new;if(ev.detail?.table==='f1_territory_progress'&&rp?.progress_id&&cached?.territory?.progress?.progress_id===rp.progress_id){await F1MobileStore.setConflict({table:ev.detail.table,remote:rp,local:cached.territory.progress,detected_at:new Date().toISOString()});updateNetworkUI()}return}await loadRemote(true)});
  addEventListener('focus',()=>{if(navigator.onLine&&!flushing)loadRemote(true)});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&navigator.onLine&&!flushing)loadRemote(true)});
}
async function boot(){wire();clock();setInterval(clock,1000);await F1MobileStore.openDB();try{const cached=await loadCached();if(navigator.onLine){if(!window.F1Sync?.configured?.()||!await F1Sync.ensureSession()){document.documentElement.classList.remove('f1-auth-pending');location.replace('setup-cloud.html?return='+encodeURIComponent('notiziere-mobile.html'));return}profile=await F1StaffData.me();await loadRemote(true);await flushOutbox();window.F1Realtime?.start?.();heartbeat()}else if(!cached){setStatus('mainStatus','OFFLINE · nessuna sessione territoriale disponibile sul telefono. Collegati almeno una volta per caricare l’assegnazione.','warn')}}catch(e){console.error(e);if(!state)await loadCached();setStatus('mainStatus','AVVIO PARZIALE · '+String(e?.message||e),isNetworkError(e)?'warn':'err')}finally{document.documentElement.classList.remove('f1-auth-pending');render();updateNetworkUI()}}
setInterval(()=>heartbeat(),45000);boot();
})();
