(()=>{
'use strict';
const $=id=>document.getElementById(id),C=()=>window.F1AcquisitionCore,D=()=>window.F1AcquisitionData;
const PROGRAM='F1_90_DAY_PROGRAM',DAY='F1_90_DAY_DAY',ORIGIN='F1_90_DAY';
const BLOCKS={
  script:{label:'1h SCRIPT / ROLE-PLAY',target:60},
  prospecting:{label:'2–3h PROSPECTING',target:150,min:120,max:180},
  preview:{label:'2h MARKET PREVIEW',target:120},
  followup:{label:'1h FOLLOW-UP',target:60}
};
const state={program:null,weekly:null,day:null,campaigns:[],events:[],leads:[],tasks:[],interactions:[],timer:null};
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const now=()=>new Date().toISOString(),today=()=>C().todayRome();
const dateKey=x=>x?new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Rome',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(x)):'';
const dayMs=d=>Date.parse(String(d).slice(0,10)+'T12:00:00Z');
const daysBetween=(a,b)=>Math.floor((dayMs(b)-dayMs(a))/86400000);
const addDays=(d,n)=>new Date(dayMs(d)+n*86400000).toISOString().slice(0,10);
const dayNumber=()=>state.program?.starts_at?Math.max(1,daysBetween(dateKey(state.program.starts_at),today())+1):0;
const phase=n=>n<=30?{id:1,title:'GIORNI 1–30 · COSTRUZIONE DELLA DISCIPLINA',text:'Imparare gli script, aumentare progressivamente i contatti, costruire il database, conoscere il territorio, avviare Just Listed / Just Sold e mantenere il follow-up quotidiano.'}:n<=60?{id:2,title:'GIORNI 31–60 · CONSISTENZA',text:'Mantenere stabilmente 20 contatti al giorno, 5–7 preview, role-play quotidiano e follow-up sistematico; aumentare appuntamenti e opportunità qualificate.'}:{id:3,title:'GIORNI 61–90 · OTTIMIZZAZIONE',text:'Analizzare script, fonti, zone, attività e follow-up che producono risultati migliori senza ridurre le attività fondamentali.'};
const contactGoal=n=>n<=10?10:n<=20?15:20;
const fmtSec=s=>{s=Math.max(0,Math.floor(Number(s)||0));const h=Math.floor(s/3600),m=Math.floor((s%3600)/60);return h?`${h}h ${String(m).padStart(2,'0')}m`:`${m}m`};
const fmtMin=m=>fmtSec(Number(m||0)*60);
function defaultBlocks(){return Object.fromEntries(Object.entries(BLOCKS).map(([k,v])=>[k,{target_minutes:v.target,elapsed_seconds:0,started_at:null,completed_at:null,status:'PENDING'}]))}
function normalizedBlocks(meta={}){const src=meta.blocks||{},out=defaultBlocks();for(const k of Object.keys(out))out[k]={...out[k],...(src[k]||{})};return out}
function elapsed(b){let s=Number(b?.elapsed_seconds)||0;if(b?.started_at)s+=Math.max(0,(Date.now()-Date.parse(b.started_at))/1000);return Math.round(s)}
function setNotice(text,kind=''){$('cloudStatus').className='notice '+kind;$('cloudStatus').innerHTML=text}
async function auth(){if(!window.F1Sync||!D())throw Error('Motore CRM non disponibile');if(!F1Sync.ready()||!await F1Sync.ensureSession())throw Error('ACCESSO CRM RICHIESTO');D().requireCloud()}
async function patchCampaign(id,patch){const rows=await D().rest('campaigns?campaign_id=eq.'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify({...patch,updated_at:now()}),prefer:'return=representation'});if(!rows?.[0])throw Error('Aggiornamento programma non confermato dal backend');const saved=rows[0],i=state.campaigns.findIndex(c=>String(c.campaign_id)===String(id));if(i>=0)state.campaigns[i]=saved;if(state.program?.campaign_id===id)state.program=saved;if(state.day?.campaign_id===id)state.day=saved;return saved}
async function appendEvent(type,evidence={}){const row={event_id:crypto.randomUUID(),event_type:type,pillar:1,lead_id:'',property_id:'',source_id:ORIGIN,evidence_url:'',evidence_type:ORIGIN,evidence,confidence:'OPERATOR_VERIFIED',occurred_at:now(),created_at:now()},rows=await D().rest('events?on_conflict=event_id',{method:'POST',body:JSON.stringify([row]),prefer:'resolution=merge-duplicates,return=representation'}),saved=rows?.[0]||row;state.events.push(saved);return saved}
async function ensureDay(){const n=dayNumber();if(!state.program||n<1||n>90)return null;const key=today();let row=state.campaigns.find(c=>c.campaign_type===DAY&&c.territory_key===key);if(row){state.day=row;return row}const created={campaign_id:crypto.randomUUID(),campaign_type:DAY,property_id:'',territory_key:key,name:`PROGRAMMA 90 GIORNI · GIORNO ${n}`,status:'ACTIVE',starts_at:now(),metadata:{day_number:n,phase:phase(n).id,blocks:defaultBlocks(),close_status:'',closed_at:null,missing:[]},created_at:now(),updated_at:now()},rows=await D().rest('campaigns?on_conflict=campaign_id',{method:'POST',body:JSON.stringify([created]),prefer:'resolution=merge-duplicates,return=representation'});state.day=rows?.[0]||created;state.campaigns.push(state.day);return state.day}
async function load(){await auth();const [campaigns,events,leads,tasks,interactions]=await Promise.all([
  D().rest('campaigns?select=*&order=created_at.desc&limit=1000'),
  D().rest('events?select=*&order=occurred_at.desc&limit=6000'),
  D().pullLeads(),D().pullTasks(),D().pullInteractions()
]);state.campaigns=campaigns||[];state.events=events||[];state.leads=leads||[];state.tasks=tasks||[];state.interactions=interactions||[];state.program=state.campaigns.find(c=>c.campaign_type===PROGRAM&&String(c.status||'').toUpperCase()==='ACTIVE')||null;state.weekly=state.campaigns.find(c=>c.campaign_type==='F1_WEEKLY_PROGRESSION'&&String(c.status||'').toUpperCase()!=='CANCELLED')||null;if(state.program)await ensureDay();render()}
async function startProgram(){try{await auth();const v=$('programStart').value;if(!v)throw Error('Seleziona la data reale di inizio');if(dayMs(v)>dayMs(today()))throw Error('La data di inizio non può essere futura');const row={campaign_id:crypto.randomUUID(),campaign_type:PROGRAM,property_id:'',territory_key:'90_DAYS',name:'F1 PROGRAMMA OPERATIVO 90 GIORNI',status:'ACTIVE',starts_at:new Date(v+'T12:00:00Z').toISOString(),ends_at:null,metadata:{daily_blocks:{script_minutes:60,prospecting_minutes:150,preview_minutes:120,followup_minutes:60},preview_goal_min:5,preview_goal_max:7,followup_goal:10,created_from:state.weekly?'F1_WEEKLY_PROGRESSION':'MANUAL_START'},created_at:now(),updated_at:now()},rows=await D().rest('campaigns?on_conflict=campaign_id',{method:'POST',body:JSON.stringify([row]),prefer:'resolution=merge-duplicates,return=representation'});state.program=rows?.[0]||row;state.campaigns.push(state.program);await ensureDay();render();setNotice('PROGRAMMA 90 GIORNI ATTIVO · stato operativo salvato in campaigns. I risultati commerciali restano nel CRM UNIFICATO.','ok')}catch(e){setNotice('ERRORE · '+esc(e.message),'err')}}
function settle(blocks,key,status){const b={...blocks[key]};if(b.started_at){b.elapsed_seconds=(Number(b.elapsed_seconds)||0)+Math.max(0,Math.round((Date.now()-Date.parse(b.started_at))/1000));b.started_at=null}if(status)b.status=status;blocks[key]=b}
async function patchBlocks(blocks){const metadata={...(state.day.metadata||{}),blocks};await patchCampaign(state.day.campaign_id,{metadata});render()}
async function startBlock(key){try{if(!state.day||String(state.day.status).toUpperCase()==='CLOSED')throw Error('Giornata già chiusa');const blocks=normalizedBlocks(state.day.metadata);for(const k of Object.keys(blocks))if(k!==key&&blocks[k].started_at)settle(blocks,k,'PAUSED');if(blocks[key].status==='COMPLETED')throw Error('Blocco già completato');blocks[key]={...blocks[key],started_at:blocks[key].started_at||now(),status:'RUNNING'};await patchBlocks(blocks)}catch(e){setNotice('ERRORE · '+esc(e.message),'err')}}
async function pauseBlock(key){try{const blocks=normalizedBlocks(state.day.metadata);if(!blocks[key].started_at)throw Error('Timer non attivo');settle(blocks,key,'PAUSED');await patchBlocks(blocks)}catch(e){setNotice('ERRORE · '+esc(e.message),'err')}}
async function completeBlock(key){try{const blocks=normalizedBlocks(state.day.metadata);settle(blocks,key,'COMPLETED');blocks[key].completed_at=now();await patchBlocks(blocks)}catch(e){setNotice('ERRORE · '+esc(e.message),'err')}}
function isOpenTask(t){return!['DONE','CANCELLED'].includes(String(t.status||'OPEN').toUpperCase())}
function taskMap(){return new Map(state.tasks.map(t=>[String(t.task_id||''),t]))}
function metricsFor(date=today()){
  const ints=state.interactions.filter(i=>dateKey(i.occurred_at)===date),tm=taskMap(),followIds=new Set(state.tasks.filter(t=>String(t.task_type||'').toUpperCase()==='FOLLOW_UP').map(t=>String(t.task_id))),pros=ints.filter(i=>String(i.interaction_type||'').toUpperCase()==='CALL'&&String(i.direction||'OUTBOUND').toUpperCase()==='OUTBOUND'&&!followIds.has(String(i.task_id||''))),noTalk=/NON[ _-]?RISPONDE|NO[ _-]?ANSWER|SEGRETERIA|VOICEMAIL|NESSUNA[ _-]?RISPOSTA/i,conversations=pros.filter(i=>i.outcome&&!noTalk.test(String(i.outcome))),previewEvents=state.events.filter(e=>e.event_type==='MARKET_PREVIEW_VISIONED'&&dateKey(e.occurred_at)===date),preview=new Set(previewEvents.map(e=>e.property_id).filter(Boolean)).size,marketOpp=state.events.filter(e=>e.event_type==='MARKET_PREVIEW_OPPORTUNITY_CREATED'&&dateKey(e.occurred_at)===date).length,interesting=ints.filter(i=>/POTENZIALE[ _-]?VENDITORE|INTERESSATO|SEGNALAZIONE/i.test(String(i.outcome||''))).length,fuInts=ints.filter(i=>followIds.has(String(i.task_id||''))),followups=new Set(fuInts.map(i=>String(i.task_id))).size,appointments=ints.filter(i=>/APPUNT/i.test(String(i.outcome||''))).length,newLeads=state.leads.filter(l=>dateKey(l.created_at)===date).length,roleEvents=state.events.filter(e=>e.event_type==='F1_90_ROLEPLAY_COMPLETED'&&dateKey(e.occurred_at)===date).length,weeklyRole=state.weekly?.metadata?.last_roleplay_at&&dateKey(state.weekly.metadata.last_roleplay_at)===date?1:0;
  return{interactions:ints.length,prospecting:pros.length,conversations:conversations.length,preview,opportunities:marketOpp+interesting,followups,appointments,newLeads,roleplays:roleEvents||weeklyRole};
}
function tomorrowTasks(){const d=addDays(today(),1);return state.tasks.filter(t=>isOpenTask(t)&&dateKey(t.due_date)===d)}
function dueFollowups(){return state.tasks.filter(t=>isOpenTask(t)&&(/FOLLOW_UP/i.test(String(t.task_type||''))||/FOLLOW.?UP|RICHIAM|INVIA|CONFERM|AGGIORN|SEGNAL/i.test(String(t.reason||'')))&&(!t.due_date||dateKey(t.due_date)<=today())).sort((a,b)=>String(a.due_date||'').localeCompare(String(b.due_date||''))||(+b.priority||0)-(+a.priority||0))}
function productiveSeconds(){if(!state.day)return 0;return Object.values(normalizedBlocks(state.day.metadata)).reduce((s,b)=>s+elapsed(b),0)}
function completionCount(){if(!state.day)return 0;return Object.values(normalizedBlocks(state.day.metadata)).filter(b=>b.status==='COMPLETED').length}
function renderSetup(){const setup=$('setupPanel'),op=$('operational');if(state.program){setup.hidden=true;op.hidden=false;return}setup.hidden=false;op.hidden=true;$('programStart').value=state.weekly?.starts_at?dateKey(state.weekly.starts_at):today();$('setupHint').textContent=state.weekly?.starts_at?'Data proposta dal percorso F1 già esistente.':'Imposta la data reale di inizio del percorso; nessun risultato viene retroattivamente inventato.'}
function renderHeader(){if(!state.program)return;const n=dayNumber(),p=phase(n),m=metricsFor(),goal=contactGoal(n);$('dayNumber').textContent=`GIORNO ${Math.min(n,90)} / 90`;$('phaseTitle').textContent=p.title;$('phaseText').textContent=p.text;$('headCompleted').textContent=`${completionCount()} / 4`;$('headTime').textContent=`${fmtSec(productiveSeconds())} / 6h 30m`;$('headProspecting').textContent=`${m.prospecting} / ${goal}`;$('headPreview').textContent=`${m.preview} / 5–7`;$('headFollowup').textContent=`${m.followups} / 10`;$('programProgress').style.width=Math.min(100,n/90*100)+'%';$('programProgressText').textContent=`Progressione: giorno ${Math.min(n,90)} di 90`}
function renderBlocks(){if(!state.day)return;const blocks=normalizedBlocks(state.day.metadata),closed=String(state.day.status).toUpperCase()==='CLOSED';for(const [k,def] of Object.entries(BLOCKS)){const b=blocks[k],sec=elapsed(b),card=document.querySelector(`[data-block="${k}"]`);if(!card)continue;card.classList.toggle('done',b.status==='COMPLETED');card.classList.toggle('running',!!b.started_at);card.querySelector('.blockStatus').textContent=b.status;card.querySelector('.blockTime').textContent=`${fmtSec(sec)} / ${fmtMin(def.target)}`;card.querySelector('.blockProgress > div').style.width=Math.min(100,sec/(def.target*60)*100)+'%';card.querySelector('[data-act="start"]').disabled=closed||b.status==='COMPLETED'||!!b.started_at;card.querySelector('[data-act="pause"]').disabled=closed||!b.started_at;card.querySelector('[data-act="complete"]').disabled=closed||b.status==='COMPLETED'} }
function renderKpis(){const n=dayNumber(),m=metricsFor(),blocks=state.day?normalizedBlocks(state.day.metadata):defaultBlocks();$('kScriptMin').textContent=Math.floor(elapsed(blocks.script)/60);$('kRoleplay').textContent=m.roleplays;$('kProspecting').textContent=m.prospecting;$('kConversations').textContent=m.conversations;$('kPreview').textContent=m.preview;$('kOpportunities').textContent=m.opportunities;$('kFollowup').textContent=m.followups;$('kAppointments').textContent=m.appointments;$('kLeads').textContent=m.newLeads;$('prospectingGoal').textContent=`Obiettivo progressivo oggi: ${contactGoal(n)} contatti reali registrati come CALL OUTBOUND nel CRM.`}
function renderFollowups(){const rows=dueFollowups(),box=$('followupQueue');$('dueFollowupCount').textContent=rows.length;box.innerHTML=rows.length?rows.slice(0,30).map(t=>`<article class="task"><b>${esc(t.reason||'Follow-up')}</b><span>${esc(dateKey(t.due_date)||'senza data')} · ${esc(t.status||'OPEN')}</span><a href="crm.html">APRI CRM</a></article>`).join(''):'<div class="empty">Nessun follow-up dovuto o scaduto.</div>'}
function monday(date=today()){const d=new Date(date+'T12:00:00Z'),dow=d.getUTCDay();return addDays(date,-((dow+6)%7))}
function weeklyMinutes(){const mon=monday(),sun=addDays(mon,6),sum={script:0,prospecting:0,preview:0,followup:0};for(const c of state.campaigns.filter(x=>x.campaign_type===DAY&&x.territory_key>=mon&&x.territory_key<=sun)){const blocks=normalizedBlocks(c.metadata);for(const k of Object.keys(sum)){const b=blocks[k],s=(c.campaign_id===state.day?.campaign_id)?elapsed(b):Number(b.elapsed_seconds)||0;sum[k]+=s/60}}return sum}
function weekMetrics(){const mon=monday(),dates=new Set(Array.from({length:7},(_,i)=>addDays(mon,i))),allInts=state.interactions.filter(i=>dates.has(dateKey(i.occurred_at))),followIds=new Set(state.tasks.filter(t=>String(t.task_type||'').toUpperCase()==='FOLLOW_UP').map(t=>String(t.task_id))),pros=allInts.filter(i=>String(i.interaction_type||'').toUpperCase()==='CALL'&&String(i.direction||'OUTBOUND').toUpperCase()==='OUTBOUND'&&!followIds.has(String(i.task_id||''))),preview=new Set(state.events.filter(e=>e.event_type==='MARKET_PREVIEW_VISIONED'&&dates.has(dateKey(e.occurred_at))).map(e=>e.property_id).filter(Boolean)).size,follow=new Set(allInts.filter(i=>followIds.has(String(i.task_id||''))).map(i=>String(i.task_id))).size,appt=allInts.filter(i=>/APPUNT/i.test(String(i.outcome||''))).length,leads=state.leads.filter(l=>dates.has(dateKey(l.created_at))).length;return{prospecting:pros.length,preview,followups:follow,appointments:appt,newLeads:leads}}
function renderWeekly(){const w=weeklyMinutes(),m=weekMetrics();$('wScript').textContent=`${Math.round(w.script)} / 300 min`;$('wProspecting').textContent=`${Math.round(w.prospecting)} / 600–900 min`;$('wPreview').textContent=`${Math.round(w.preview)} / 600 min`;$('wFollowup').textContent=`${Math.round(w.followup)} / 300 min`;$('wResults').textContent=`Contatti ${m.prospecting} · Preview ${m.preview} · Follow-up ${m.followups} · Appuntamenti ${m.appointments} · Nuovi lead ${m.newLeads}`}
function reviewActual(){const w=weeklyMinutes(),m=weekMetrics(),goal=contactGoal(dayNumber())*5;return{actual:`Script ${Math.round(w.script)}m · Prospecting ${m.prospecting} contatti · Preview ${m.preview} · Follow-up ${m.followups} · Appuntamenti ${m.appointments} · Lead ${m.newLeads}`,deviation:`Script ${Math.round(w.script-300)}m · Contatti ${m.prospecting-goal} · Preview ${m.preview-25} · Follow-up ${m.followups-50}`}}
function renderReview(){const mon=monday(),last=state.events.filter(e=>e.event_type==='F1_90_GOAL_REVIEW'&&e.evidence?.week_start===mon).sort((a,b)=>String(b.occurred_at).localeCompare(String(a.occurred_at)))[0],a=reviewActual();$('reviewActual').value=a.actual;$('reviewDeviation').value=a.deviation;$('reviewStatus').textContent=last?`REVISIONE SETTIMANALE REGISTRATA · ${dateKey(last.occurred_at)}`:'REVISIONE SETTIMANALE DA ESEGUIRE';if(last){$('goal90').value=last.evidence?.goal_90||'';$('goalMonth').value=last.evidence?.goal_month||'';$('goalWeek').value=last.evidence?.goal_week||'';$('correctiveAction').value=last.evidence?.corrective_action||''}}
function topCount(rows,key){const m=new Map();for(const r of rows){const v=key(r);if(v)m.set(v,(m.get(v)||0)+1)}return[...m.entries()].sort((a,b)=>b[1]-a[1])[0]||null}
function renderOptimization(){const box=$('optimizationPanel'),n=dayNumber();box.hidden=n<61;if(n<61)return;const start=dateKey(state.program.starts_at),ints=state.interactions.filter(i=>dateKey(i.occurred_at)>=start),leads=state.leads.filter(l=>dateKey(l.created_at)>=start),scripts=topCount(ints.filter(i=>i.outcome&&!/NON[ _-]?RISPONDE/i.test(i.outcome)),i=>i.metadata?.script_id||''),sources=topCount(leads,l=>l.source||l.source_type),zones=topCount(leads,l=>l.comune||l.zona),appt=topCount(ints.filter(i=>/APPUNT/i.test(String(i.outcome||''))),i=>i.metadata?.origin||'CRM'),followIds=new Set(state.tasks.filter(t=>String(t.task_type).toUpperCase()==='FOLLOW_UP').map(t=>String(t.task_id))),fu=ints.filter(i=>followIds.has(String(i.task_id))),conv=fu.filter(i=>/INTERESS|APPUNT|POTENZIALE/i.test(String(i.outcome||''))).length;$('optScript').textContent=scripts?`${scripts[0]} · ${scripts[1]} conversazioni`:'Dati script insufficienti';$('optSource').textContent=sources?`${sources[0]} · ${sources[1]} lead`:'Dati fonte insufficienti';$('optZone').textContent=zones?`${zones[0]} · ${zones[1]} lead`:'Dati zona insufficienti';$('optActivity').textContent=appt?`${appt[0]} · ${appt[1]} appuntamenti`:'Dati appuntamenti insufficienti';$('optFollowup').textContent=fu.length?`${conv}/${fu.length} follow-up con esito qualificato`:'Dati follow-up insufficienti'}
function closeChecks(){const blocks=normalizedBlocks(state.day.metadata),m=metricsFor(),n=dayNumber(),missing=[];for(const [k,def] of Object.entries(BLOCKS)){if(blocks[k].status!=='COMPLETED')missing.push(`${def.label}: blocco non completato`);if(elapsed(blocks[k])<def.target*60)missing.push(`${def.label}: ${fmtSec(elapsed(blocks[k]))} / ${fmtMin(def.target)}`)}if(m.prospecting<contactGoal(n))missing.push(`PROSPECTING: ${m.prospecting}/${contactGoal(n)} contatti reali`);if(m.preview<5)missing.push(`MARKET PREVIEW: ${m.preview}/5 minimi`);if(m.followups<10)missing.push(`FOLLOW-UP: ${m.followups}/10`);if(!m.interactions)missing.push('INTERAZIONI CRM: nessuna interazione registrata oggi');if(!tomorrowTasks().length)missing.push('TASK DOMANI: nessun task aperto con scadenza domani');return missing}
async function closeDay(){try{if(!state.day)throw Error('Giornata non inizializzata');if(String(state.day.status).toUpperCase()==='CLOSED')throw Error('Giornata già chiusa');const blocks=normalizedBlocks(state.day.metadata);for(const k of Object.keys(blocks))if(blocks[k].started_at)settle(blocks,k,blocks[k].status==='RUNNING'?'PAUSED':blocks[k].status);await patchCampaign(state.day.campaign_id,{metadata:{...(state.day.metadata||{}),blocks}});const missing=closeChecks(),status=missing.length?'NON_COMPLETATA':'COMPLETATA',snapshot={...metricsFor(),productive_seconds:productiveSeconds(),day_number:dayNumber(),block_status:Object.fromEntries(Object.entries(blocks).map(([k,b])=>[k,b.status]))};await patchCampaign(state.day.campaign_id,{status:'CLOSED',ends_at:now(),metadata:{...(state.day.metadata||{}),blocks,close_status:status,closed_at:now(),missing,snapshot}});await appendEvent('F1_90_DAY_CLOSED',{origin:ORIGIN,date:today(),day_number:dayNumber(),close_status:status,missing,snapshot});render();$('closeResult').className='closeResult '+(missing.length?'warn':'ok');$('closeResult').innerHTML=missing.length?`<b>GIORNATA ${status}</b><br>${missing.map(x=>'• '+esc(x)).join('<br>')}`:'<b>GIORNATA COMPLETATA</b><br>Tutti i controlli operativi e i minimi giornalieri risultano registrati.'}catch(e){setNotice('ERRORE · '+esc(e.message),'err')}}
async function logRoleplay(){try{await appendEvent('F1_90_ROLEPLAY_COMPLETED',{origin:ORIGIN,date:today(),script_ref:$('roleplayType').value||'ALLENAMENTO_SCRIPT_F1'});render();setNotice('ROLE-PLAY REGISTRATO · il conteggio aumenta solo dopo questa registrazione esplicita o un role-play già registrato dal modulo Just Listed/Just Sold.','ok')}catch(e){setNotice('ERRORE · '+esc(e.message),'err')}}
async function saveReview(){try{const corrective=$('correctiveAction').value.trim();if(!corrective)throw Error('Inserisci l’azione correttiva');const a=reviewActual();await appendEvent('F1_90_GOAL_REVIEW',{origin:ORIGIN,week_start:monday(),goal_90:$('goal90').value.trim(),goal_month:$('goalMonth').value.trim(),goal_week:$('goalWeek').value.trim(),actual:a.actual,deviation:a.deviation,corrective_action:corrective});renderReview();setNotice('REVISIONE OBIETTIVI REGISTRATA · nessun KPI commerciale è stato modificato.','ok')}catch(e){setNotice('ERRORE · '+esc(e.message),'err')}}
function renderClosed(){if(!state.day)return;const status=state.day.metadata?.close_status||'';$('dayState').textContent=String(state.day.status).toUpperCase()==='CLOSED'?`GIORNATA CHIUSA · ${status}`:'GIORNATA ATTIVA';if(String(state.day.status).toUpperCase()==='CLOSED'){$('closeResult').className='closeResult '+(status==='COMPLETATA'?'ok':'warn');$('closeResult').innerHTML=`<b>${esc(status)}</b>${(state.day.metadata?.missing||[]).length?'<br>'+state.day.metadata.missing.map(x=>'• '+esc(x)).join('<br>'):''}`}}
function render(){renderSetup();if(!state.program)return;const n=dayNumber();if(n>90){$('operational').hidden=false;$('dayState').textContent='PROGRAMMA 90 GIORNI CONCLUSO';$('closeDay').disabled=true}renderHeader();renderBlocks();renderKpis();renderFollowups();renderWeekly();renderReview();renderOptimization();renderClosed()}
function bind(){
  $('startProgram').onclick=startProgram;$('closeDay').onclick=closeDay;$('logRoleplay').onclick=logRoleplay;$('saveReview').onclick=saveReview;
  document.querySelectorAll('[data-block]').forEach(card=>{const k=card.dataset.block;card.querySelector('[data-act="start"]').onclick=()=>startBlock(k);card.querySelector('[data-act="pause"]').onclick=()=>pauseBlock(k);card.querySelector('[data-act="complete"]').onclick=()=>completeBlock(k)});
  state.timer=setInterval(()=>{if(state.day&&Object.values(normalizedBlocks(state.day.metadata)).some(b=>b.started_at)){renderHeader();renderBlocks();renderKpis();renderWeekly()}},1000)
}
window.F190={state,PROGRAM,DAY,BLOCKS,load,metricsFor,dayNumber,contactGoal,closeChecks};
window.addEventListener('load',async()=>{bind();try{await load();setNotice('CRM UNIFICATO CONNESSO · Programma 90 giorni usa campaigns/events solo per orchestrazione. LEAD · INTERAZIONI · TASK restano nel CRM unico.','ok')}catch(e){setNotice('ACCESSO CRM RICHIESTO · '+esc(e.message),'err');$('setupPanel').hidden=true;$('operational').hidden=true}});
})();