const SCRIPTS=window.F1_SCRIPTS||[];
const CATEGORIES=['TUTTI','ACQUIRENTI','VENDITORI','PROSPECTING','TERRITORIO','PRIVATI','INCARICHI SCADUTI','RELAZIONI','PRESENTAZIONI','OBIEZIONI'];
let activeCategory='TUTTI';
let readerKey=null;
const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const mark=s=>esc(s).replace(/\[[^\]]+\]/g,m=>`<span class="placeholder">${m}</span>`);
function allText(s){return [s.id,s.shortTitle,s.title,...s.categories,...Object.values(s.meta),...s.sections.flatMap(sec=>[sec.heading,...sec.items.flatMap(it=>it.kind==='dialogue'?[it.client,it.response]:[it.text])])].join(' ').toLocaleLowerCase('it');}
function itemHTML(it){if(it.kind==='bullet')return `<li>${mark(it.text)}</li>`;if(it.kind==='dialogue')return `<div class="dialogue"><div class="client">${mark(it.client)}</div><div class="reply">${mark(it.response)}</div></div>`;return `<p>${mark(it.text)}</p>`}
function sectionHTML(sec){const bullets=sec.items.filter(x=>x.kind==='bullet');const others=sec.items.filter(x=>x.kind!=='bullet');return `<section class="section"><h3>${esc(sec.heading)}</h3>${others.map(itemHTML).join('')}${bullets.length?`<ul>${bullets.map(itemHTML).join('')}</ul>`:''}</section>`}
function metaHTML(s){const order=['AREA','UTILIZZATO DA','OBIETTIVO','QUANDO UTILIZZARLO'];const rows=order.filter(k=>s.meta[k]).map(k=>`<div class="meta"><b>${esc(k)}</b><span>${mark(s.meta[k])}</span></div>`).join('');return rows?`<div class="meta-grid">${rows}</div>`:''}
function trainingActions(s){if(!['f1-004','f1-005'].includes(s.key))return'';const type=s.key==='f1-005'?'JUST_SOLD':'JUST_LISTED',label=type==='JUST_SOLD'?'JUST SOLD':'JUST LISTED';return `<a class="btn" href="just-listed-sold.html?mode=roleplay&type=${type}">ROLE-PLAY ${label}</a><a class="btn" href="just-listed-sold.html">CONTATTI DI OGGI</a>`}
function cardHTML(s){const badge=s.id||s.label;const variant=s.label==='VARIANTE'?' variant':'';return `<article class="script-card" data-key="${esc(s.key)}" id="${esc(s.key)}"><div class="script-head"><div class="script-id${variant}">${esc(badge)}</div><div class="script-title"><h2>${esc(s.shortTitle||s.title)}</h2><p>${esc(s.title)}</p><div class="tags">${s.categories.map(c=>`<span class="tag">${esc(c)}</span>`).join('')}</div></div></div><div class="actions"><button class="btn red" data-action="toggle" data-key="${esc(s.key)}" type="button">APRI</button><button class="btn" data-action="copy" data-key="${esc(s.key)}" type="button">COPIA SCRIPT</button><button class="btn" data-action="print" data-key="${esc(s.key)}" type="button">STAMPA</button><button class="btn" data-action="read" data-key="${esc(s.key)}" type="button">LETTURA</button>${trainingActions(s)}</div><div class="script-body">${metaHTML(s)}${s.sections.map(sectionHTML).join('')}<a class="to-index" href="#top">↑ TORNA ALL’INDICE</a></div></article>`}
function render(){const q=$('#search').value.trim().toLocaleLowerCase('it');let visible=0;document.querySelectorAll('.script-card').forEach(card=>{const s=SCRIPTS.find(x=>x.key===card.dataset.key);const okCat=activeCategory==='TUTTI'||s.categories.includes(activeCategory);const okSearch=!q||allText(s).includes(q);card.classList.toggle('hidden',!(okCat&&okSearch));if(okCat&&okSearch)visible++});$('#count').textContent=`${visible} script visualizzati su ${SCRIPTS.length}`;let empty=$('#empty');if(!visible&&!empty){empty=document.createElement('div');empty.id='empty';empty.className='empty';empty.textContent='Nessuno script corrisponde alla ricerca.';$('#archive').appendChild(empty)}else if(visible&&empty)empty.remove()}
function plain(s){const lines=[];lines.push(s.id?`${s.id} — ${s.shortTitle||s.title}`:(s.shortTitle||s.title));if(s.title&&s.title!==s.shortTitle)lines.push(s.title);for(const k of ['AREA','UTILIZZATO DA','OBIETTIVO','QUANDO UTILIZZARLO'])if(s.meta[k])lines.push(`\n${k}\n${s.meta[k]}`);for(const sec of s.sections){lines.push(`\n${sec.heading}`);for(const it of sec.items){if(it.kind==='dialogue'){lines.push(it.client);lines.push(it.response)}else if(it.kind==='bullet')lines.push(`• ${it.text}`);else lines.push(it.text)}}return lines.join('\n').trim()}
async function copyScript(key){const s=SCRIPTS.find(x=>x.key===key);if(!s)return;const text=plain(s);try{await navigator.clipboard.writeText(text)}catch(e){const ta=document.createElement('textarea');ta.value=text;ta.style.position='fixed';ta.style.opacity='0';document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove()}toast('Script copiato')}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),1400)}
function printOne(key){document.body.classList.remove('print-all');document.body.classList.add('print-single');document.querySelectorAll('.script-card').forEach(c=>c.classList.toggle('print-target',c.dataset.key===key));window.print()}
function printAll(){document.body.classList.remove('print-single');document.body.classList.add('print-all');document.querySelectorAll('.script-card').forEach(c=>c.classList.remove('print-target'));window.print()}
function openReader(key){const s=SCRIPTS.find(x=>x.key===key);if(!s)return;readerKey=key;$('#readerTitle').textContent=s.id?`${s.id} · ${s.shortTitle}`:s.shortTitle;$('#readerContent').innerHTML=`<h2>${esc(s.shortTitle||s.title)}</h2>${metaHTML(s)}${s.sections.map(sectionHTML).join('')}`;$('#reader').classList.add('open');document.body.style.overflow='hidden';$('#reader').scrollTop=0}
function closeReader(){$('#reader').classList.remove('open');document.body.style.overflow='';readerKey=null}
function buildFilters(){$('#filters').innerHTML=CATEGORIES.map(c=>`<button type="button" class="chip${c==='TUTTI'?' active':''}" data-cat="${esc(c)}">${esc(c)}</button>`).join('')}
$('#archive').innerHTML=SCRIPTS.map(cardHTML).join('');buildFilters();render();
$('#search').addEventListener('input',render);$('#clearBtn').addEventListener('click',()=>{$('#search').value='';activeCategory='TUTTI';document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x.dataset.cat==='TUTTI'));render();$('#search').focus()});$('#filters').addEventListener('click',e=>{const b=e.target.closest('[data-cat]');if(!b)return;activeCategory=b.dataset.cat;document.querySelectorAll('.chip').forEach(x=>x.classList.toggle('active',x===b));render()});$('#archive').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const key=b.dataset.key;const card=document.querySelector(`.script-card[data-key="${CSS.escape(key)}"]`);if(b.dataset.action==='toggle'){card.classList.toggle('open');b.textContent=card.classList.contains('open')?'CHIUDI':'APRI';if(card.classList.contains('open'))card.scrollIntoView({behavior:'smooth',block:'start'})}if(b.dataset.action==='copy')copyScript(key);if(b.dataset.action==='print')printOne(key);if(b.dataset.action==='read')openReader(key)});$('#printAllBtn').addEventListener('click',printAll);$('#readerClose').addEventListener('click',closeReader);$('#readerCopy').addEventListener('click',()=>readerKey&&copyScript(readerKey));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&$('#reader').classList.contains('open'))closeReader()});window.addEventListener('afterprint',()=>{document.body.classList.remove('print-single','print-all');document.querySelectorAll('.print-target').forEach(c=>c.classList.remove('print-target'))});
