const S=window.F1_SCRIPTS||[];
const $=s=>document.querySelector(s); let current=null, filter='TUTTI', favOnly=false, sentenceIdx=0, hidden=false, lastUtterance=null, playing=false;
const state=JSON.parse(localStorage.getItem('f1-script-state')||'{}');
state.favorites=state.favorites||[]; state.learned=state.learned||[]; state.review=state.review||[]; state.listenCount=state.listenCount||{};
function save(){localStorage.setItem('f1-script-state',JSON.stringify(state));}
const cats=['TUTTI',...new Set(S.map(x=>x.category))];
function renderChips(){ $('#chips').innerHTML=cats.map(c=>`<button class="chip ${filter===c?'active':''}" data-c="${c}">${c}</button>`).join(''); document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{filter=b.dataset.c;favOnly=false;renderChips();render();}); }
function render(){ const q=$('#search').value.trim().toLowerCase(); let rows=S.filter(x=>(filter==='TUTTI'||x.category===filter)&&(!favOnly||state.favorites.includes(x.id))&&(!q||[x.title,x.category,x.subcategory,x.tags.join(' '),x.purpose].join(' ').toLowerCase().includes(q))); $('#stats').textContent=`${rows.length} script · ${state.learned.length} memorizzati · ${state.review.length} da ripassare`; $('#list').innerHTML=rows.length?rows.map(x=>`<article class="card"><div class="row"><div><h3>${x.title}</h3><div class="meta">${x.category} · ${x.subcategory}</div></div><button class="fav ${state.favorites.includes(x.id)?'on':''}" data-f="${x.id}">★</button></div><div class="goal">${x.purpose}</div><div class="row"><span class="badge">${x.verificationStatus}</span><button class="btn small primary" data-open="${x.id}">Apri</button></div></article>`).join(''):'<div class="empty">Nessuno script trovato.</div>'; document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openScript(b.dataset.open)); document.querySelectorAll('[data-f]').forEach(b=>b.onclick=()=>toggleFav(b.dataset.f)); }
function toggleFav(id){ const i=state.favorites.indexOf(id); if(i>=0)state.favorites.splice(i,1); else state.favorites.push(id); save();render(); if(current&&current.id===id)updateDlgFav(); }
function splitSentences(t){return t.replace(/\n+/g,' ').match(/[^.!?]+[.!?]+|[^.!?]+$/g)?.map(s=>s.trim()).filter(Boolean)||[t];}
function openScript(id){current=S.find(x=>x.id===id); sentenceIdx=0; hidden=false; $('#dCategory').textContent=`${current.category} · ${current.subcategory}`; $('#dTitle').textContent=current.title; $('#dGoal').textContent=`Scopo: ${current.purpose} Quando usarlo: ${current.usage}`; $('#dScript').textContent=current.italianAdapted; $('#dMemory').innerHTML=current.memory.map(m=>`<li>${m}</li>`).join(''); $('#dClient').textContent=current.roleplayClient; $('#dAgent').textContent=current.roleplayAgent; $('#dSource').innerHTML=`${current.verificationStatus}<br><a style="color:#8fe0aa" target="_blank" rel="noopener" href="${current.sourceUrl}">${current.source}</a>`; updateDlgFav(); updateSentence(); $('#dlg').showModal(); }
function updateDlgFav(){ $('#favDlg').textContent=state.favorites.includes(current.id)?'★ Preferito':'☆ Preferito'; $('#learned').textContent=state.learned.includes(current.id)?'✓ Memorizzato':'So a memoria'; $('#review').textContent=state.review.includes(current.id)?'✓ Da ripassare':'Da ripassare'; }
let voices=[];
function italianVoices(){voices=speechSynthesis.getVoices();return voices.filter(v=>/^it(-|_)/i.test(v.lang));}
function defaultVoice(list){const preferred=['elsa','alice','federica','isabella','female','italiana'];return preferred.map(p=>list.find(v=>v.name.toLowerCase().includes(p))).find(Boolean)||list[0]||voices[0];}
function pickVoice(){const list=italianVoices();if(state.voiceName){const saved=voices.find(v=>v.name===state.voiceName);if(saved)return saved;}return defaultVoice(list);}
function voiceInfo(){
 const list=italianVoices(), sel=$('#voiceSelect'), chosen=pickVoice();
 if(sel){
   const current=state.voiceName||chosen?.name||'';
   sel.innerHTML=(list.length?list:voices).map(v=>`<option value="${v.name.replace(/"/g,'&quot;')}">${v.name} · ${v.lang}</option>`).join('');
   if(current)sel.value=current;
 }
 $('#voiceStatus').textContent=chosen?`Voce attiva: ${chosen.name} (${chosen.lang}) · sintesi nativa dispositivo`:'Voce italiana non ancora disponibile: verifica le voci installate sul dispositivo.';
}
speechSynthesis.onvoiceschanged=voiceInfo; setTimeout(voiceInfo,200);
$('#voiceSelect').onchange=()=>{state.voiceName=$('#voiceSelect').value;save();voiceInfo();};
function speak(text,rate=1,onend){speechSynthesis.cancel(); const u=new SpeechSynthesisUtterance(text.replace(/F1/g,'effe uno').replace(/FSBO/g,'effe esse bi o').replace(/Mike Ferry/g,'Maik Ferri')); u.lang='it-IT'; u.rate=rate; const v=pickVoice(); if(v)u.voice=v; u.onend=()=>{playing=false;if(onend)onend();}; u.onerror=()=>{playing=false}; lastUtterance={text,rate}; playing=true; speechSynthesis.speak(u); if(current){state.listenCount[current.id]=(state.listenCount[current.id]||0)+1; save();}}
function playLoops(text,n){let c=0; const rate=Number($('#speed').value); const run=()=>{if(c>=n)return;c++;speak(text,rate,()=>{if(n===999||c<n)setTimeout(run,550)});};run();}
function updateSentence(){if(!current)return; const arr=splitSentences(current.italianAdapted); sentenceIdx=Math.max(0,Math.min(sentenceIdx,arr.length-1)); $('#sentenceBox').textContent=hidden?'••••••••••••••••••••••':arr[sentenceIdx]; $('#sentenceProgress').style.width=`${((sentenceIdx+1)/arr.length)*100}%`; $('#hideText').textContent=hidden?'Mostra testo':'Nascondi testo';}
$('#search').oninput=render; $('#closeDlg').onclick=()=>{speechSynthesis.cancel();$('#dlg').close();}; $('#play').onclick=()=>playLoops(current.italianAdapted,Number($('#loops').value)); $('#pause').onclick=()=>{if(speechSynthesis.speaking&&!speechSynthesis.paused)speechSynthesis.pause();else if(speechSynthesis.paused)speechSynthesis.resume();}; $('#repeat').onclick=()=>lastUtterance&&speak(lastUtterance.text,lastUtterance.rate); $('#playSentence').onclick=()=>{const a=splitSentences(current.italianAdapted);speak(a[sentenceIdx],Number($('#speed').value));}; $('#prevSentence').onclick=()=>{sentenceIdx--;updateSentence();}; $('#nextSentence').onclick=()=>{sentenceIdx++;updateSentence();}; $('#hideText').onclick=()=>{hidden=!hidden;updateSentence();}; $('#roleplay').onclick=()=>speak(`Proprietario. ${current.roleplayClient}. Agente. ${current.roleplayAgent}`,Number($('#speed').value)); $('#testMemory').onclick=()=>{const a=splitSentences(current.italianAdapted); const s=a[Math.floor(Math.random()*a.length)]; const first=s.split(' ').slice(0,Math.min(5,s.split(' ').length)).join(' '); $('#sentenceBox').textContent=first+' …'; hidden=true;}; $('#favDlg').onclick=()=>toggleFav(current.id); $('#learned').onclick=()=>{const i=state.learned.indexOf(current.id);if(i>=0)state.learned.splice(i,1);else{state.learned.push(current.id);state.review=state.review.filter(x=>x!==current.id);}save();updateDlgFav();render();}; $('#review').onclick=()=>{const i=state.review.indexOf(current.id);if(i>=0)state.review.splice(i,1);else{state.review.push(current.id);state.learned=state.learned.filter(x=>x!==current.id);}save();updateDlgFav();render();}; $('#downloadTxt').onclick=()=>{const blob=new Blob([`${current.title}\n\n${current.italianAdapted}\n\nFonte: ${current.sourceUrl}\nStato: ${current.verificationStatus}`],{type:'text/plain;charset=utf-8'}); const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=current.id+'.txt';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);};
$('#favoritesBtn').onclick=()=>{favOnly=true;filter='TUTTI';renderChips();render();}; $('#allBtn').onclick=()=>{favOnly=false;filter='TUTTI';renderChips();render();}; $('#progressBtn').onclick=()=>{const total=S.length,l=state.learned.length,r=state.review.length,listen=Object.values(state.listenCount).reduce((a,b)=>a+b,0); alert(`Progressi F1 Script Trainer\n\nScript totali: ${total}\nMemorizzati: ${l}\nDa ripassare: ${r}\nAscolti: ${listen}\nCompletamento: ${Math.round(l/total*100)}%`);}; $('#todayBtn').onclick=()=>{favOnly=false; const ids=[...state.review,...S.filter(x=>!state.learned.includes(x.id)).map(x=>x.id)].slice(0,5); $('#list').innerHTML=ids.map(id=>{const x=S.find(s=>s.id===id);return `<article class="card"><h3>${x.title}</h3><div class="meta">TRAINING DI OGGI · ${x.category}</div><div class="goal">${x.purpose}</div><button class="btn small primary" data-open="${x.id}">Allenati</button></article>`}).join(''); document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>openScript(b.dataset.open)); $('#stats').textContent=`Training di oggi · ${ids.length} script`;};
renderChips();render(); if('serviceWorker' in navigator)navigator.serviceWorker.register('./service-worker.js');