(()=>{const ALL=window.F1_SCRIPTS||[],$=q=>document.querySelector(q),KEY='f1-script-state-v2';let state=JSON.parse(localStorage.getItem(KEY)||'{}');for(const k of ['memory','listenCount','repeatCount','roleplayCount','attemptCount','lastAttempt','passedCount'])state[k]=state[k]||{};const save=()=>localStorage.setItem(KEY,JSON.stringify(state));let current=null,voices=[],recognition=null,micStream=null,audioRecorder=null,audioChunks=[],cameraStream=null,sessionRecorder=null,sessionChunks=[],sessionBlob=null,timerStart=0,timerInt=null,faceTimer=null,faceStats={frames:0,detected:0,centered:0,movement:0,last:null},fullMode=false,fullSeq=[],fullIndex=0,fullResults=[];
const eligible=ALL.filter(s=>s.roleplayClient&&s.roleplayAgent);const primary=ALL.filter(s=>s.category==='PERCORSO ACQUISIZIONE').sort((a,b)=>a.workflowOrder-b.workflowOrder);
function norm(t){return (t||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9àèéìòù\s]/g,' ').replace(/\s+/g,' ').trim()}
function loadVoices(){voices=speechSynthesis.getVoices().filter(v=>/^it([_-]|$)/i.test(v.lang));if(!voices.length)voices=speechSynthesis.getVoices()}speechSynthesis.onvoiceschanged=loadVoices;loadVoices();
function chooseClientVoice(){const female=['elsa','alice','federica','isabella','female','paola','silvia'];const male=['luca','diego','paolo','male','cosimo','giovanni'];const want=$('#clientGender').value==='female'?female:male;return want.map(n=>voices.find(v=>v.name.toLowerCase().includes(n))).find(Boolean)||voices[$('#clientGender').value==='female'?1:0]||voices[0]}
function speakClient(){if(!current)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(current.roleplayClient);u.lang='it-IT';u.rate=+$('#clientRate').value;const v=chooseClientVoice();if(v)u.voice=v;speechSynthesis.speak(u)}
function optionLabel(s){return (s.workflowPhase?'F'+String(s.workflowPhase).padStart(2,'0')+' · ':'')+s.title}
function populate(){const ordered=[...ALL].sort((a,b)=>(a.workflowOrder||99999)-(b.workflowOrder||99999));$('#scriptSelect').innerHTML=ordered.filter(s=>s.roleplayClient||s.category==='PERCORSO ACQUISIZIONE').map(s=>'<option value="'+s.id+'">'+optionLabel(s)+'</option>').join('')}
function setCurrent(id){current=ALL.find(s=>s.id===id)||eligible[0]||ALL[0];if(!current)return;$('#scriptSelect').value=current.id;$('#clientQuote').textContent=current.roleplayClient||'Questo modulo non prevede una battuta cliente. Usa la modalità specchio per ripeterlo.';$('#scenarioLabel').textContent=current.subcategory||current.category;renderPrompt();$('#transcript').value='';$('#feedback').className='feedback hidden-ui';state.lastAttempt[current.id]=new Date().toISOString();save();if(current.roleplayClient)setTimeout(speakClient,250)}
function renderPrompt(){if(!current)return;const mode=$('#mode').value,box=$('#operatorPrompt'),kw=$('#keywords');kw.innerHTML=(current.keywords||[]).map(x=>'<span class="keyword">'+x+'</span>').join('');if(mode==='guided')box.textContent=current.roleplayAgent||current.italianAdapted;else if(mode==='assisted')box.textContent='Parole chiave → '+(current.keywords||[]).join(' · ');else box.textContent=mode==='exam'?'ESAME: nessun aiuto. Rispondi e poi valuta.':'MEMORIA: rispondi senza leggere.';box.classList.toggle('hidden-ui',false);if(mode==='memory'||mode==='exam')kw.classList.add('hidden-ui');else kw.classList.remove('hidden-ui')}
function conceptTokens(){const stop=new Set('capisco perfetto allora anche della delle della con per che come questo questa quello essere avere farlo fare oggi solo prima dopo molto bene puo può nel nella dei degli una uno suo sua lei noi voi sono'.split(' '));const words=norm(current.roleplayAgent||current.italianAdapted).split(' ').filter(w=>w.length>=5&&!stop.has(w));const kw=(current.keywords||[]).flatMap(k=>norm(k).split(' ')).filter(w=>w.length>=4&&!stop.has(w));return [...new Set([...kw,...words])].slice(0,10)}
function evaluate(){if(!current)return;const text=norm($('#transcript').value),concepts=conceptTokens();const hit=concepts.filter(c=>text.includes(c)),missing=concepts.filter(c=>!text.includes(c)),coverage=concepts.length?hit.length/concepts.length:0;state.attemptCount[current.id]=(state.attemptCount[current.id]||0)+1;state.roleplayCount[current.id]=(state.roleplayCount[current.id]||0)+1;state.lastAttempt[current.id]=new Date().toISOString();let label,cls;if(coverage>=.78){label='COMPLETO';cls='good';state.passedCount[current.id]=(state.passedCount[current.id]||0)+1;if(state.memory[current.id]!=='MEMORIZZATO')state.memory[current.id]='QUASI MEMORIZZATO';}else if(coverage>=.48){label='QUASI COMPLETO';cls='mid';state.memory[current.id]='DA RIPASSARE';}else{label='MANCANO PASSAGGI';cls='bad';state.memory[current.id]='DA RIPASSARE';}save();const f=$('#feedback');f.className='feedback '+cls;f.innerHTML='<b>'+label+'</b><div class="meta" style="margin-top:4px">Concetti rilevati: '+hit.length+' / '+concepts.length+'. Il confronto serve a ricordare i passaggi, non richiede una recitazione parola per parola.</div>'+(missing.length?'<ul class="missing">'+missing.map(x=>'<li>'+x+'</li>').join('')+'</ul>':'')+'<div class="privacy">Ordine: il browser verifica la presenza dei concetti chiave; la coerenza conversazionale va riascoltata nella registrazione.</div>';if(fullMode){fullResults.push({id:current.id,label,coverage});$('#nextFull').disabled=coverage<.48;updateFullProgress()}return coverage}
function startTimer(){timerStart=Date.now();clearInterval(timerInt);timerInt=setInterval(()=>{const s=Math.floor((Date.now()-timerStart)/1000);$('#timer').textContent=String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')},250)}
function stopTimer(){clearInterval(timerInt)}
function speechSupport(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;$('#speechSupport').textContent=SR?'Riconoscimento vocale disponibile in questo browser.':'Riconoscimento vocale non disponibile: registrazione audio + trascrizione manuale.';return SR}
async function startAnswer(){startTimer();$('#startAnswer').disabled=true;$('#stopAnswer').disabled=false;try{micStream=await navigator.mediaDevices.getUserMedia({audio:true});audioChunks=[];if(window.MediaRecorder){audioRecorder=new MediaRecorder(micStream);audioRecorder.ondataavailable=e=>{if(e.data.size)audioChunks.push(e.data)};audioRecorder.onstop=()=>{const b=new Blob(audioChunks,{type:audioRecorder.mimeType||'audio/webm'});$('#audioPlayback').src=URL.createObjectURL(b);$('#audioPlayback').classList.remove('hidden-ui')};audioRecorder.start()}const SR=speechSupport();if(SR){recognition=new SR();recognition.lang='it-IT';recognition.continuous=true;recognition.interimResults=true;let final='';recognition.onresult=e=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0].transcript;if(e.results[i].isFinal)final+=t+' ';else interim+=t}$('#transcript').value=(final+interim).trim()};recognition.onerror=()=>{};recognition.start()}}catch(e){$('#speechSupport').textContent='Microfono non disponibile o permesso negato. Puoi comunque scrivere la risposta e valutarla.'}}
function stopAnswer(){stopTimer();try{recognition&&recognition.stop()}catch{}try{audioRecorder&&audioRecorder.state!=='inactive'&&audioRecorder.stop()}catch{}if(micStream){micStream.getTracks().forEach(t=>t.stop());micStream=null}$('#startAnswer').disabled=false;$('#stopAnswer').disabled=true}
async function cameraOn(){try{cameraStream=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user'},audio:false});$('#preview').srcObject=cameraStream;$('#cameraBtn').disabled=true;$('#stopCameraBtn').disabled=false;startFaceAnalysis()}catch(e){$('#visualInfo').textContent='Telecamera non disponibile o permesso negato. Il simulatore continua senza video.'}}
function cameraOff(){if(cameraStream){cameraStream.getTracks().forEach(t=>t.stop());cameraStream=null}$('#preview').srcObject=null;$('#cameraBtn').disabled=false;$('#stopCameraBtn').disabled=true;stopFaceAnalysis();renderVisualSummary()}
async function startFaceAnalysis(){faceStats={frames:0,detected:0,centered:0,movement:0,last:null};if(!('FaceDetector'in window)){ $('#visualInfo').textContent='Anteprima attiva. FaceDetector non è disponibile in questo browser: usa il video come specchio e la registrazione per l’autovalutazione.';return}const det=new FaceDetector({fastMode:true,maxDetectedFaces:1});faceTimer=setInterval(async()=>{try{const v=$('#preview');if(v.readyState<2)return;faceStats.frames++;const faces=await det.detect(v);if(!faces.length)return;faceStats.detected++;const b=faces[0].boundingBox,cx=(b.x+b.width/2)/v.videoWidth,cy=(b.y+b.height/2)/v.videoHeight;if(Math.abs(cx-.5)<.18&&Math.abs(cy-.46)<.22)faceStats.centered++;if(faceStats.last)faceStats.movement+=Math.hypot(cx-faceStats.last.x,cy-faceStats.last.y);faceStats.last={x:cx,y:cy}}catch{}},700)}
function stopFaceAnalysis(){clearInterval(faceTimer)}
function renderVisualSummary(){if(!faceStats.frames){$('#visualSummary').textContent='Nessun dato automatico di inquadratura disponibile.';return}const seen=Math.round(faceStats.detected/faceStats.frames*100),center=faceStats.detected?Math.round(faceStats.centered/faceStats.detected*100):0,mov=faceStats.detected>1?(faceStats.movement/(faceStats.detected-1)).toFixed(3):'n/d';$('#visualSummary').textContent='Feedback osservabile locale: volto rilevato nel '+seen+'% dei campioni; volto nell’area centrale nel '+center+'%; movimento medio del centro volto '+mov+'. Rivedi il video per postura, gesti, pause ed espressività. Nessuna inferenza emotiva.'}
async function startSessionRecord(){if(sessionRecorder&&sessionRecorder.state==='recording'){return}try{if(!cameraStream)await cameraOn();const audio=await navigator.mediaDevices.getUserMedia({audio:true});const tracks=[...(cameraStream?cameraStream.getVideoTracks():[]),...audio.getAudioTracks()];const combined=new MediaStream(tracks);sessionChunks=[];sessionRecorder=new MediaRecorder(combined);sessionRecorder.ondataavailable=e=>{if(e.data.size)sessionChunks.push(e.data)};sessionRecorder.onstop=()=>{sessionBlob=new Blob(sessionChunks,{type:sessionRecorder.mimeType||'video/webm'});$('#recordedVideo').src=URL.createObjectURL(sessionBlob);$('#recordedVideo').classList.remove('hidden-ui');$('#downloadSession').disabled=false;$('#deleteSession').disabled=false;combined.getTracks().filter(t=>t.kind==='audio').forEach(t=>t.stop());renderVisualSummary()};sessionRecorder.start();$('#recordSessionBtn').disabled=true;$('#stopSessionRecord').disabled=false;startTimer()}catch(e){$('#visualSummary').textContent='Registrazione non avviata: permesso o supporto browser non disponibile.'}}
function stopSessionRecord(){if(sessionRecorder&&sessionRecorder.state!=='inactive')sessionRecorder.stop();$('#recordSessionBtn').disabled=false;$('#stopSessionRecord').disabled=true;stopTimer()}
function downloadSession(){if(!sessionBlob)return;const a=document.createElement('a');a.href=URL.createObjectURL(sessionBlob);a.download='F1_roleplay_'+current.id+'_'+new Date().toISOString().slice(0,10)+'.webm';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function deleteSession(){sessionBlob=null;$('#recordedVideo').removeAttribute('src');$('#recordedVideo').load();$('#recordedVideo').classList.add('hidden-ui');$('#downloadSession').disabled=true;$('#deleteSession').disabled=true;$('#visualSummary').textContent='Registrazione eliminata dalla sessione locale.'}
function randomScenario(){fullMode=false;$('#fullProgressWrap').classList.add('hidden-ui');const pool=ALL.filter(s=>s.category==='OBIEZIONI'&&s.roleplayClient);setCurrent(pool[Math.floor(Math.random()*pool.length)]?.id||eligible[Math.floor(Math.random()*eligible.length)].id)}
function startFull(){fullSeq=primary.filter(s=>s.workflowPhase>=6&&s.roleplayClient);fullIndex=0;fullResults=[];fullMode=true;$('#mode').value='exam';renderPrompt();$('#fullProgressWrap').classList.remove('hidden-ui');$('#nextFull').disabled=true;setCurrent(fullSeq[0].id);updateFullProgress()}
function updateFullProgress(){const pct=fullSeq.length?Math.round(fullIndex/fullSeq.length*100):0;$('#fullProgress').style.width=pct+'%';$('#fullProgressLabel').textContent=(fullIndex+1)+' / '+fullSeq.length}
function nextFull(){if(!fullMode)return;if(fullIndex<fullSeq.length-1){fullIndex++;$('#nextFull').disabled=true;setCurrent(fullSeq[fullIndex].id);updateFullProgress()}else endFull()}
function endFull(){if(!fullMode)return;const passed=fullResults.filter(r=>r.coverage>=.78).length;const weak=fullResults.filter(r=>r.coverage<.78).map(r=>ALL.find(s=>s.id===r.id)?.title).filter(Boolean);const f=$('#feedback');f.className='feedback '+(weak.length?'mid':'good');f.innerHTML='<b>ESAME ACQUISIZIONE</b><div style="margin-top:6px">Passaggi completati: '+passed+' / '+fullResults.length+'</div>'+(weak.length?'<div class="meta" style="margin-top:6px">Da ripassare:</div><ul class="missing">'+weak.map(x=>'<li>'+x+'</li>').join('')+'</ul>':'<div class="meta">Nessun passaggio debole rilevato nelle risposte valutate.</div>');fullMode=false;$('#nextFull').disabled=true}
function mirror(){const cur=current;$('#clientQuote').textContent='MODALITÀ SPECCHIO: nessun cliente. Ripeti il copione osservando postura, sguardo verso la camera, pause e gestualità.';$('#mode').value='guided';renderPrompt();cameraOn();if(cur)current=cur}
populate();speechSupport();$('#scriptSelect').onchange=()=>setCurrent($('#scriptSelect').value);$('#mode').onchange=renderPrompt;$('#speakClient').onclick=speakClient;$('#repeatClient').onclick=speakClient;$('#randomBtn').onclick=randomScenario;$('#fullBtn').onclick=startFull;$('#mirrorBtn').onclick=mirror;$('#startAnswer').onclick=startAnswer;$('#stopAnswer').onclick=stopAnswer;$('#evaluate').onclick=evaluate;$('#retry').onclick=()=>{$('#transcript').value='';$('#feedback').className='feedback hidden-ui';speakClient()};$('#cameraBtn').onclick=cameraOn;$('#stopCameraBtn').onclick=cameraOff;$('#recordSessionBtn').onclick=startSessionRecord;$('#stopSessionRecord').onclick=stopSessionRecord;$('#downloadSession').onclick=downloadSession;$('#deleteSession').onclick=deleteSession;$('#nextFull').onclick=nextFull;$('#endFull').onclick=endFull;window.addEventListener('beforeunload',()=>{speechSynthesis.cancel();cameraOff();if(micStream)micStream.getTracks().forEach(t=>t.stop())});const qp=new URLSearchParams(location.search).get('script');setCurrent(qp&&ALL.some(s=>s.id===qp)?qp:'lp-02-tre-risultati');if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js').catch(()=>{});})();