const {test,expect}=require('@playwright/test');
const BASE='https://nqnmlsmeiynxbdojeyjt.supabase.co',AUTH=BASE+'/auth/v1/',REST=BASE+'/rest/v1/';
const uuid=()=>`00000000-0000-4000-8000-${Math.random().toString().slice(2,14).padEnd(12,'0')}`;
const isoAgo=n=>new Date(Date.now()-n*86400000).toISOString(),datePlus=n=>new Date(Date.now()+n*86400000).toISOString().slice(0,10);
function lead(id,nome,cognome,phone,via,immobile=''){return{lead_id:id,pillar:2,source_type:'COI',source:'QA',source_url:'',created_at:isoAgo(40),first_seen:isoAgo(40),last_seen:isoAgo(1),nome,cognome,azienda:'',telefono:phone,email:'',comune:'Villar Dora',via,civico:'',zona:'Centro',immobile_id:immobile,competitor_agency:'',lead_reason:'QA TERRITORIO',lead_score:70,confidence:'HIGH',status:'DA_CONTATTARE',last_contact:null,next_action:'',next_action_date:null,assigned_to:'',notes:'',privacy_basis:'QA',do_not_contact:false,rpo_status:'NON_APPLICABILE',created_by:'qa',updated_at:isoAgo(1),deleted:false}}
function idField(t){return({leads:'lead_id',tasks:'task_id',interactions:'interaction_id',campaigns:'campaign_id',properties:'property_id',events:'event_id',referrals:'referral_id'}[t]||t+'_id')}
async function backend(context,db){
  await context.addInitScript(()=>sessionStorage.setItem('f1SupabaseSession',JSON.stringify({access_token:'qa-access',refresh_token:'qa-refresh',expires_at:Date.now()+3600000,user:{id:'00000000-0000-4000-8000-000000000001'}})));
  await context.route(AUTH+'user',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({id:'00000000-0000-4000-8000-000000000001',role:'authenticated'})}));
  await context.route(REST+'**',async route=>{const req=route.request(),u=new URL(req.url()),table=u.pathname.split('/').pop(),method=req.method();if(!(table in db))return route.fulfill({status:200,contentType:'application/json',body:'[]'});if(method==='GET')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(db[table])});if(method==='POST'){const raw=JSON.parse(req.postData()||'[]'),rows=Array.isArray(raw)?raw:[raw],field=idField(table);for(const row of rows){row[field]=row[field]||uuid();row.user_id=row.user_id||'00000000-0000-4000-8000-000000000001';const i=db[table].findIndex(x=>String(x[field])===String(row[field]));i>=0?db[table][i]={...db[table][i],...row}:db[table].push({...row})}return route.fulfill({status:201,contentType:'application/json',body:JSON.stringify(rows)});}if(method==='PATCH'){const patch=JSON.parse(req.postData()||'{}'),field=idField(table),filter=u.searchParams.get(field),value=filter?.replace(/^eq\./,'');const changed=[];for(let i=0;i<db[table].length;i++)if(!value||String(db[table][i][field])===String(value)){db[table][i]={...db[table][i],...patch};changed.push(db[table][i])}return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(changed)});}if(method==='DELETE'){const field=idField(table),value=(u.searchParams.get(field)||'').replace(/^eq\./,'');db[table]=db[table].filter(x=>String(x[field])!==String(value));return route.fulfill({status:204,body:''})}return route.fulfill({status:405,body:'[]'})});
}
test('Dashboard -> F1-004/F1-005 -> role-play -> real property -> call outcome -> CRM lead interaction task',async({browser})=>{
  const db={
    campaigns:[{campaign_id:'program',user_id:'00000000-0000-4000-8000-000000000001',campaign_type:'F1_WEEKLY_PROGRESSION',property_id:'',territory_key:'',name:'F1 PROGRESSIONE SETTIMANALE',status:'ACTIVE',starts_at:isoAgo(10),ends_at:null,metadata:{training_started_at:isoAgo(3),roleplay_count:1},created_at:isoAgo(10),updated_at:isoAgo(1)}],
    properties:[{property_id:'prop-1',user_id:'00000000-0000-4000-8000-000000000001',comune:'Villar Dora',via:'Via Roma',civico:'10',zona:'Centro',frazione:'',tipologia:'Casa indipendente',caratteristiche:{},status:'OSSERVATO',created_at:isoAgo(30),updated_at:isoAgo(1),deleted:false}],
    leads:[lead('source-owner','Proprietario','Sorgente','3330000000','Via Roma','prop-1'),lead('lead-1','Mario','Rossi','3330000001','Via Roma'),lead('lead-2','Anna','Verdi','3330000002','Via Roma')],
    interactions:[],tasks:[],events:[],referrals:[]
  };
  const context=await browser.newContext();await backend(context,db);const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(String(e)));

  // Dashboard: il motore settimana 2 è visibile ma non inventa campagne immobiliari.
  await page.goto('/index.html');await expect(page.locator('#jlsWidget')).toContainText('JUST LISTED / JUST SOLD');await expect(page.locator('#jlsStage')).toContainText('NESSUN IMMOBILE REALE ATTIVO');await expect(page.locator('#jlsProgressText')).toContainText('0 / 10');

  // Archivio: gli script ufficiali esistono e hanno azioni role-play senza duplicazione.
  await page.goto('/script.html');await expect(page.locator('#f1-004')).toContainText('Immobile appena acquisito');await expect(page.locator('#f1-005')).toContainText('Immobile appena venduto');await expect(page.locator('#f1-004')).toContainText('ROLE-PLAY JUST LISTED');await expect(page.locator('#f1-005')).toContainText('ROLE-PLAY JUST SOLD');

  // F1-004 role-play: nessun feedback prima della risposta; feedback solo dopo.
  await page.locator('#f1-004 a').filter({hasText:'ROLE-PLAY JUST LISTED'}).click();await page.waitForURL('**/just-listed-sold.html?mode=roleplay&type=JUST_LISTED');await expect(page.locator('#roleArea')).toBeVisible();await expect(page.locator('#roleScriptRef')).toContainText('F1-004');await expect(page.locator('#roleFeedback')).not.toHaveClass(/show/);await page.fill('#roleAnswer','Capisco, grazie. Se conoscesse qualcuno interessato in zona posso lasciare il mio contatto, senza insistere.');await page.click('#roleSubmit');await expect(page.locator('#roleFeedback')).toHaveClass(/show/);expect(db.campaigns[0].metadata.roleplay_count).toBeGreaterThanOrEqual(2);

  // Nessun contatto può partire da OSSERVATO: prima si conferma il fatto reale sul property_id esistente.
  await expect(page.locator('#campaignList')).toContainText('Nessuna campagna reale attiva');await page.selectOption('#propertySelect','prop-1');await page.selectOption('#campaignMode','JUST_LISTED');await page.check('#realConfirm');await page.click('#activateProperty');await expect.poll(()=>db.properties[0].status).toBe('F1_ACQUISITO');expect(db.events.some(e=>e.event_type==='F1_JUST_LISTED_CONFIRMED'&&e.property_id==='prop-1')).toBeTruthy();expect(db.campaigns.some(c=>c.campaign_type==='JUST_LISTED'&&c.property_id==='prop-1'&&c.metadata?.verified_real)).toBeTruthy();await expect(page.locator('#contacts')).toContainText('Mario Rossi');await expect(page.locator('#contacts')).toContainText('Anna Verdi');await expect(page.locator('#contacts')).not.toContainText('Proprietario Sorgente');

  // Un contatto conta solo dopo l'esito CRM. Potenziale venditore -> Interaction + Task.
  await expect(page.locator('#kDone')).toHaveText('0');const mario=page.locator('.call').filter({hasText:'Mario Rossi'});await mario.getByRole('button',{name:'REGISTRA ESITO'}).click();await page.selectOption('#outcome','POTENZIALE VENDITORE');await page.fill('#nextDate',datePlus(1));await page.fill('#outcomeNote','Possibile progetto di vendita emerso in chiamata QA');await page.click('#saveOutcome');await expect.poll(()=>db.interactions.filter(i=>i.metadata?.origin==='JUST_LISTED_SOLD'&&i.outcome==='POTENZIALE VENDITORE').length).toBe(1);expect(db.tasks.some(t=>t.lead_id==='lead-1'&&t.task_type==='FOLLOW_UP'&&t.metadata?.origin==='JUST_LISTED_SOLD')).toBeTruthy();await expect(page.locator('#kDone')).toHaveText('1');await expect(page.locator('#kSeller')).toHaveText('1');

  // Segnalazione acquirente -> Interaction -> controllo duplicati -> nuovo Lead collegato alla fonte -> Task.
  const anna=page.locator('.call').filter({hasText:'Anna Verdi'});await anna.getByRole('button',{name:'REGISTRA ESITO'}).click();await page.selectOption('#outcome','SEGNALAZIONE ACQUIRENTE');await page.fill('#outcomeNote','Segnalazione QA');await page.click('#saveOutcome');await expect(page.locator('#referralDlg')).toBeVisible();await page.fill('#rNome','Luca');await page.fill('#rCognome','Bianchi');await page.fill('#rTelefono','3330000099');await page.fill('#rComune','Villar Dora');await page.fill('#rTaskDate',datePlus(2));await page.click('#convertReferral');await expect.poll(()=>db.leads.some(l=>l.nome==='Luca'&&l.cognome==='Bianchi'&&l.created_by==='just_listed_sold_referral')).toBeTruthy();const referred=db.leads.find(l=>l.nome==='Luca'&&l.cognome==='Bianchi');expect(db.referrals.some(r=>r.lead_id==='lead-2'&&String(r.outcome).includes(referred.lead_id))).toBeTruthy();expect(db.tasks.some(t=>t.lead_id===referred.lead_id&&t.metadata?.source_lead_id==='lead-2')).toBeTruthy();expect(db.interactions.some(i=>i.lead_id===referred.lead_id&&i.metadata?.source_lead_id==='lead-2')).toBeTruthy();await expect(page.locator('#kDone')).toHaveText('2');await expect(page.locator('#kReferral')).toHaveText('1');await expect(page.locator('#progressText')).toContainText('2 / 10');

  // F1-005 usa lo stesso motore role-play e resta lo script ufficiale Just Sold.
  await page.goto('/script.html#f1-005');await page.locator('#f1-005 a').filter({hasText:'ROLE-PLAY JUST SOLD'}).click();await expect(page).toHaveURL(/just-listed-sold\.html\?mode=roleplay&type=JUST_SOLD$/);await expect(page.locator('#roleArea')).toBeVisible();await expect(page.locator('#roleScriptRef')).toContainText('F1-005');await expect(page.locator('#roleResident')).toContainText('Quanto avete venduto?');await page.fill('#roleAnswer','Posso comunicare solo dati corretti e divulgabili; per il valore della sua casa servono dati comparabili verificati.');await page.click('#roleSubmit');await expect(page.locator('#roleFeedback')).toHaveClass(/show/);

  expect(errors).toEqual([]);await context.close();
});
