const {test,expect}=require('@playwright/test');
const BASE='https://nqnmlsmeiynxbdojeyjt.supabase.co',AUTH=BASE+'/auth/v1/',REST=BASE+'/rest/v1/';
const uuid=()=>`00000000-0000-4000-8000-${Math.random().toString().slice(2,14).padEnd(12,'0')}`;
const idField=t=>({leads:'lead_id',tasks:'task_id',interactions:'interaction_id',campaigns:'campaign_id',properties:'property_id',events:'event_id'}[t]||t+'_id');
async function backend(context,db){await context.addInitScript(()=>sessionStorage.setItem('f1SupabaseSession',JSON.stringify({access_token:'qa-access',refresh_token:'qa-refresh',expires_at:Date.now()+3600000,user:{id:'00000000-0000-4000-8000-000000000001'}})));await context.route(AUTH+'user',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({id:'00000000-0000-4000-8000-000000000001',role:'authenticated'})}));await context.route(REST+'**',async route=>{const req=route.request(),u=new URL(req.url()),table=u.pathname.split('/').pop(),method=req.method();if(!(table in db))return route.fulfill({status:200,contentType:'application/json',body:'[]'});if(method==='GET')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(db[table])});if(method==='POST'){const raw=JSON.parse(req.postData()||'[]'),rows=Array.isArray(raw)?raw:[raw],field=idField(table);for(const row of rows){row[field]=row[field]||uuid();row.user_id=row.user_id||'00000000-0000-4000-8000-000000000001';const i=db[table].findIndex(x=>String(x[field])===String(row[field]));i>=0?db[table][i]={...db[table][i],...row}:db[table].push({...row})}return route.fulfill({status:201,contentType:'application/json',body:JSON.stringify(rows)})}if(method==='PATCH'){const patch=JSON.parse(req.postData()||'{}'),field=idField(table),value=(u.searchParams.get(field)||'').replace(/^eq\./,'');const changed=[];for(let i=0;i<db[table].length;i++)if(!value||String(db[table][i][field])===String(value)){db[table][i]={...db[table][i],...patch};changed.push(db[table][i])}return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(changed)})}return route.fulfill({status:204,body:''})})}
function prop(i,via,price,mq){return{property_id:'prop-'+i,user_id:'00000000-0000-4000-8000-000000000001',comune:'Villar Dora',via,civico:String(i),zona:'Centro',frazione:'',latitude:null,longitude:null,tipologia:i%2?'appartamento':'villa',caratteristiche:{prezzo:price,mq,source:'Immobiliare.it',source_url:'https://example.com/annuncio-'+i,market_party:'DA_VERIFICARE'},first_seen:new Date(Date.now()-i*86400000).toISOString(),last_seen:new Date().toISOString(),status:'OSSERVATO',fingerprint:'qa-'+i,created_at:new Date().toISOString(),updated_at:new Date().toISOString(),deleted:false}}
test('Dashboard -> Market Preview -> 5 immobili -> FSBO -> duplicati -> Lead -> F1-006 -> Task',async({browser})=>{const db={properties:[prop(1,'Via Roma',220000,100),prop(2,'Via Celle',205000,95),prop(3,'Via Cuminie',310000,150),prop(4,'Via San Vincenzo',185000,85),prop(5,'Via Borgionera',260000,120)],leads:[],events:[],campaigns:[],interactions:[],tasks:[]};const context=await browser.newContext();await backend(context,db);const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(String(e)));
await page.goto('/index.html');await expect(page.locator('#marketPreviewWidget')).toContainText('MARKET PREVIEW');await expect(page.locator('#mpVisionText')).toContainText('0 / 5–7');
await page.goto('/market-preview.html');await expect(page.locator('#cloudStatus')).toContainText('CRM UNIFICATO CONNESSO');await expect(page.locator('.item')).toHaveCount(5);for(const box of await page.locator('.pick').all())await box.check();await page.click('#savePlan');await expect(page.locator('#planStatus')).toContainText('PIANO SALVATO');expect(db.campaigns.some(c=>c.campaign_type==='MARKET_PREVIEW_DAY'&&c.metadata.selected_property_ids.length===5)).toBeTruthy();
for(let i=0;i<5;i++){const card=page.locator('.item').nth(i);await card.getByRole('button',{name:'APRI PREVIEW'}).click();await expect(page.locator('#previewDlg')).toBeVisible();await page.fill('#pMinutes','20');if(i===0)await page.locator('#signalGrid input[value="VENDITA_DA_PRIVATO"]').check();await page.click('#markVisioned');await expect(page.locator('#previewStatus')).toContainText('VISIONATO REGISTRATO');await page.click('#closePreview')}
await expect(page.locator('#kVisioned')).toHaveText('5');await expect(page.locator('#kTime')).toHaveText('100');expect(db.events.filter(e=>e.event_type==='MARKET_PREVIEW_VISIONED').length).toBe(5);
await page.locator('.item').first().getByRole('button',{name:'APRI PREVIEW'}).click();await page.click('#newOpportunity');await expect(page.locator('#oppDlg')).toBeVisible();await page.fill('#oName','Mario');await page.fill('#oSurname','Rossi');await page.fill('#oPhone','3330000099');await page.check('#oRpoVerified');await expect(page.locator('#createCrm')).toBeDisabled();await page.click('#checkDuplicates');await expect(page.locator('#duplicateResult')).toContainText('Nessun duplicato');await expect(page.locator('#createCrm')).toBeEnabled();await page.click('#createCrm');await expect(page.locator('#oppResult')).toContainText('CRM UNIFICATO AGGIORNATO');const lead=db.leads.find(l=>l.nome==='Mario'&&l.cognome==='Rossi');expect(lead).toBeTruthy();expect(lead.source_type).toBe('FSBO');expect(lead.created_by).toBe('market_preview');expect(db.interactions.some(i=>i.lead_id===lead.lead_id&&i.metadata?.origin==='MARKET_PREVIEW')).toBeTruthy();expect(db.tasks.some(t=>t.lead_id===lead.lead_id&&t.task_type==='CALL'&&t.metadata?.script_id==='F1-006')).toBeTruthy();expect(db.events.some(e=>e.event_type==='MARKET_PREVIEW_OPPORTUNITY_CREATED'&&e.evidence?.lead_id===lead.lead_id)).toBeTruthy();await expect(page.locator('#oppResult a')).toHaveAttribute('href','script.html#f1-006');
await page.goto('/script.html#f1-006');await expect(page.locator('#f1-006')).toContainText('Venditore privato');expect(errors).toEqual([]);await context.close()});