const {test,expect}=require('@playwright/test');
const LIVE='https://josephsocialmedia2-spec.github.io/launcher-dashboard';
const BASE='https://nqnmlsmeiynxbdojeyjt.supabase.co',AUTH=BASE+'/auth/v1/',REST=BASE+'/rest/v1/';
const uuid=()=>`00000000-0000-4000-8000-${Math.random().toString().slice(2,14).padEnd(12,'0')}`;
const idField=t=>({leads:'lead_id',tasks:'task_id',interactions:'interaction_id',campaigns:'campaign_id',properties:'property_id',events:'event_id'}[t]||t+'_id');
async function backend(context,db){await context.addInitScript(()=>sessionStorage.setItem('f1SupabaseSession',JSON.stringify({access_token:'qa-live-access',refresh_token:'qa-live-refresh',expires_at:Date.now()+3600000,user:{id:'00000000-0000-4000-8000-000000000001'}})));await context.route(AUTH+'user',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({id:'00000000-0000-4000-8000-000000000001',role:'authenticated'})}));await context.route(REST+'**',async route=>{const req=route.request(),u=new URL(req.url()),table=u.pathname.split('/').pop(),method=req.method();if(!(table in db))return route.fulfill({status:200,contentType:'application/json',body:'[]'});if(method==='GET')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(db[table])});if(method==='POST'){const raw=JSON.parse(req.postData()||'[]'),rows=Array.isArray(raw)?raw:[raw],field=idField(table);for(const row of rows){row[field]=row[field]||uuid();row.user_id=row.user_id||'00000000-0000-4000-8000-000000000001';const i=db[table].findIndex(x=>String(x[field])===String(row[field]));i>=0?db[table][i]={...db[table][i],...row}:db[table].push({...row})}return route.fulfill({status:201,contentType:'application/json',body:JSON.stringify(rows)})}if(method==='PATCH'){const patch=JSON.parse(req.postData()||'{}'),field=idField(table),value=(u.searchParams.get(field)||'').replace(/^eq\./,'');const changed=[];for(let i=0;i<db[table].length;i++)if(!value||String(db[table][i][field])===String(value)){db[table][i]={...db[table][i],...patch};changed.push(db[table][i])}return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(changed)})}return route.fulfill({status:204,body:''})})}
test('LIVE Dashboard -> Market Preview -> modifica -> PATCH -> S.props -> refresh -> persistenza',async({browser})=>{const now=new Date().toISOString(),db={properties:[{property_id:'live-prop',user_id:'00000000-0000-4000-8000-000000000001',comune:'Villar Dora',via:'Via Roma',civico:'1',zona:'Centro',frazione:'',latitude:null,longitude:null,tipologia:'appartamento',caratteristiche:{prezzo:220000,mq:100,source:'QA LIVE',source_url:'https://example.com/live-prop',market_party:'DA_VERIFICARE'},first_seen:now,last_seen:now,status:'OSSERVATO',fingerprint:'qa-live-prop',created_at:now,updated_at:now,deleted:false}],leads:[],events:[],campaigns:[],interactions:[],tasks:[]};const context=await browser.newContext();await backend(context,db);const page=await context.newPage(),patchStatuses=[];page.on('response',r=>{if(r.request().method()==='PATCH'&&r.url().includes('/rest/v1/properties?'))patchStatuses.push(r.status())});
await page.goto(LIVE+'/index.html?qa='+Date.now(),{waitUntil:'domcontentloaded'});await expect(page.locator('#marketPreviewWidget')).toContainText('MARKET PREVIEW');
await page.goto(LIVE+'/market-preview.html?qa='+Date.now(),{waitUntil:'domcontentloaded'});await expect(page.locator('#cloudStatus')).toContainText('CRM UNIFICATO CONNESSO');await expect(page.locator('.item[data-id="live-prop"] .price')).toContainText('220.000');await page.locator('.item[data-id="live-prop"]').getByRole('button',{name:'APRI PREVIEW'}).click();await page.fill('#pPrice','199000');await page.click('#saveAnalysis');await expect(page.locator('#previewStatus')).toContainText('ANALISI SALVATA');expect(patchStatuses).toEqual([200]);expect(Number(db.properties[0].caratteristiche.prezzo)).toBe(199000);expect(await page.evaluate(()=>Number(window.F1MarketPreview.state.props.find(p=>p.property_id==='live-prop')?.caratteristiche?.prezzo))).toBe(199000);await expect(page.locator('.item[data-id="live-prop"] .price')).toContainText('199.000');await page.click('#closePreview');
await page.reload({waitUntil:'domcontentloaded'});await expect(page.locator('#cloudStatus')).toContainText('CRM UNIFICATO CONNESSO');expect(await page.evaluate(()=>Number(window.F1MarketPreview.state.props.find(p=>p.property_id==='live-prop')?.caratteristiche?.prezzo))).toBe(199000);await expect(page.locator('.item[data-id="live-prop"] .price')).toContainText('199.000');await context.close()});