const {test,expect}=require('@playwright/test');
const BASE='https://nqnmlsmeiynxbdojeyjt.supabase.co',AUTH=BASE+'/auth/v1/',REST=BASE+'/rest/v1/';
const USER='00000000-0000-4000-8000-000000000001';
const uuid=()=>`00000000-0000-4000-8000-${Math.random().toString().slice(2,14).padEnd(12,'0')}`;
function key(table,row){if(table==='network_contacts')return String(row.contact_id||'');if(table==='network_contact_sources')return `${row.user_id||USER}|${row.contact_id}|${row.source_id}`;if(table==='network_source_progress')return `${row.user_id||USER}|${row.source_id}`;if(table==='network_reconstruction_state')return String(row.user_id||USER);return String(row.id||'')}
async function backend(context,db){await context.addInitScript(()=>sessionStorage.setItem('f1SupabaseSession',JSON.stringify({access_token:'qa-network',refresh_token:'qa-refresh',expires_at:4102444800000,user:{id:'00000000-0000-4000-8000-000000000001'}})));await context.route(AUTH+'**',route=>route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({id:USER,role:'authenticated',access_token:'qa-network',refresh_token:'qa-refresh',expires_in:3600,user:{id:USER}})}));await context.route(REST+'**',async route=>{const req=route.request(),u=new URL(req.url()),table=u.pathname.split('/').pop(),method=req.method();if(!(table in db))return route.fulfill({status:200,contentType:'application/json',body:'[]'});if(method==='GET')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(db[table])});if(method==='POST'){const raw=JSON.parse(req.postData()||'[]'),rows=Array.isArray(raw)?raw:[raw],saved=[];for(const src of rows){const row={...src,user_id:src.user_id||USER};if(table==='network_contacts')row.contact_id=row.contact_id||uuid();if(table==='network_contact_sources')row.contact_source_id=row.contact_source_id||uuid();const k=key(table,row),i=db[table].findIndex(x=>key(table,x)===k);if(i>=0)db[table][i]={...db[table][i],...row};else db[table].push(row);saved.push(i>=0?db[table][i]:row)}return route.fulfill({status:201,contentType:'application/json',body:JSON.stringify(saved)})}return route.fulfill({status:204,body:''})})}
function emptyDb(){return{network_contacts:[],network_contact_sources:[],network_source_progress:[],network_reconstruction_state:[],campaigns:[],events:[],leads:[],interactions:[],tasks:[],properties:[]}}
async function ready(page){await expect(page.locator('#cloudStatus')).toHaveText('RETE CLOUD CONNESSA');await expect.poll(()=>page.evaluate(()=>window.F1_NETWORK_250?.length||0)).toBe(250);await expect.poll(()=>page.evaluate(()=>!!window.F1Network250)).toBeTruthy()}

test('catalogo 250 e ripresa guidata',async({browser})=>{const db=emptyDb(),context=await browser.newContext();await backend(context,db);const page=await context.newPage();await page.goto('/network-reconstruction.html');await ready(page);await expect(page.locator('#sourceList .source-row')).toHaveCount(250);await page.click('#startGuided');await expect(page.locator('#guidedState')).toContainText('FONTE #1');expect(db.network_reconstruction_state[0].current_source_id).toBe(1);expect(db.network_source_progress.find(x=>x.source_id===1)?.status).toBe('IN LAVORAZIONE');await page.reload();await ready(page);await expect(page.locator('#guidedState')).toContainText('FONTE #1');await context.close()});

test('deduplica e storico multi-fonte',async({browser})=>{const db=emptyDb(),context=await browser.newContext();await backend(context,db);const page=await context.newPage();await page.goto('/network-reconstruction.html');await ready(page);await page.click('[data-view="contactView"]');await page.fill('#fNome','QA Persona');await page.fill('#fCognome','Uno');await page.fill('#fTelefono','000 000 0000');await page.fill('#fEmail','qa@example.invalid');await page.fill('#fComune','QA Comune');await page.selectOption('#fFonte','1');await page.click('#saveContact');await expect(page.locator('#contactNotice')).toContainText('Persona unica salvata');expect(db.network_contacts).toHaveLength(1);await page.fill('#fNome','QA Persona');await page.fill('#fCognome','Uno');await page.fill('#fTelefono','0000000000');await page.fill('#fComune','QA Comune');await page.selectOption('#fFonte','2');await page.click('#saveContact');await expect(page.locator('#contactNotice')).toContainText('Duplicato intercettato');expect(db.network_contacts).toHaveLength(1);expect(db.network_contact_sources).toHaveLength(2);expect(db.network_source_progress.find(x=>x.source_id===2)?.duplicates).toBe(1);await context.close()});

test('dashboard mostra la card blu',async({browser})=>{const db=emptyDb(),context=await browser.newContext();await backend(context,db);const page=await context.newPage();await page.goto('/index.html');await expect(page.locator('#network250Widget')).toBeVisible();await expect(page.locator('#network250Widget')).toContainText('RICOSTRUZIONE RETE 250');await expect(page.locator('#network250Widget a.net-open')).toHaveAttribute('href','network-reconstruction.html');await context.close()});