const assert=require('assert');
global.window=global;
global.document={readyState:'loading',addEventListener(){},getElementById(){return null},querySelector(){return null},createElement(){return{}},head:{appendChild(){}},body:{appendChild(){}}};
global.localStorage=(()=>{const m=new Map();return{getItem:k=>m.has(k)?m.get(k):null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k)}})();
require('../f1-priority-zero.js');
const P=global.F1PriorityZero;
assert(P,'F1PriorityZero non esposto');
assert.equal(P.classifyContact({tipo_rapporto:['PARENTE'],come_lo_conosco:'zio materno'}),'FAMILY');
assert.equal(P.classifyContact({tipo_rapporto:['AMICO']}),'FRIENDS');
assert.equal(P.classifyContact({tipo_rapporto:['PROFESSIONISTA']}),'NETWORK');
const family={contact_id:'fam-1',nome:'Mario',cognome:'Rossi',tipo_rapporto:['PARENTE'],come_lo_conosco:'zio materno',priorita:'A'};
const friend={contact_id:'fr-1',nome:'Anna',cognome:'Verdi',tipo_rapporto:['AMICO'],come_lo_conosco:'amica storica',priorita:'A'};
const network={contact_id:'net-1',nome:'Paolo',cognome:'Bianchi',tipo_rapporto:['PROFESSIONISTA'],come_lo_conosco:'geometra',priorita:'A'};
P._testSetCache({contacts:[family,friend,network]});
const base={loaded:true,profile:{daily_objectives:{news:3}},news:[],interactions:[]};
let a=P.nextAction(base);assert.equal(a.kind,'priority-zero-contact');assert.equal(a.circle,'FAMILY');assert(a.search.includes('Mario Rossi'));
const interaction=(id,circle)=>({occurred_at:'2026-09-14T08:00:00Z',metadata:{origin:'PRIORITY_ZERO_NEWS',network_contact_id:id,circle}});
a=P.nextAction({...base,interactions:[interaction('fam-1','FAMILY')]});assert.equal(a.circle,'FRIENDS');
a=P.nextAction({...base,interactions:[interaction('fam-1','FAMILY'),interaction('fr-1','FRIENDS')]});assert.equal(a.circle,'NETWORK');
a=P.nextAction({...base,interactions:[interaction('fam-1','FAMILY'),interaction('fr-1','FRIENDS'),interaction('net-1','NETWORK')]});assert.equal(a.circle,'STRANGERS');
P._testSetCache({contacts:[friend,network]});a=P.nextAction(base);assert.equal(a.kind,'priority-zero-build');assert.equal(a.circle,'FAMILY');
P._testSetCache({contacts:[family,friend,network]});a=P.nextAction({...base,news:[{created_at:new Date().toISOString()},{created_at:new Date().toISOString()},{created_at:new Date().toISOString()}]});assert.equal(a,null);
console.log('priority-zero hierarchy OK');
