const {test,expect}=require('@playwright/test');
const BASE='https://nqnmlsmeiynxbdojeyjt.supabase.co',AUTH=BASE+'/auth/v1/',REST=BASE+'/rest/v1/';
const USER='00000000-0000-4000-8000-000000000001';
const uuid=()=>`00000000-0000-4000-8000-${Math.random().toString().slice(2,14).padEnd(12,'0')}`;
const idField=t=>({leads:'lead_id',tasks:'task_id',interactions:'interaction_id',campaigns:'campaign_id',properties:'property_id',events:'event_id',referrals:'referral_id'}[t]||t+'_id');
const romeToday=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Rome'}).format(new Date());
const addDays=(d,n)=>new Date(Date.parse(d+'T12:00:00Z')+n*86400000).toISOString().slice(0,10);
const isoDay=d=>new Date(d+'T12:00:00Z').toISOString();
function lead(id,nome,sourceType,reason,via,phone){const t=romeToday();return{lead_id:id,user_id:USER,pillar:1,source_type:sourceType,source:'QA POINT7',source_url:'',created_at:isoDay(addDays(t,-30)),first_seen:isoDay(addDays(t,-30)),last_seen:isoDay(t),nome,cognome:'QA',azienda:'',telefono:phone,email:'',comune:'Villar Dora',via,civico:'',zona:'Centro',immobile_id:'',competitor_agency:'',lead_reason:reason,lead_score:80,confidence:'HIGH',status:'DA_CONTATTARE',last_contact:null,next_action:'',next_action_date:null,assigned_to:'',notes:'',privacy_basis:'QA',do_not_contact:false,rpo_status:'VERIFICATO_OK',created_by:'qa',updated_at:isoDay(t),deleted:false}}
function task(id,leadId,type,reason,date){return{task_id:id,user_id:USER,lead_id:leadId,property_id:'',event_id:null,pillar:1,task_type:type,reason,priority:80,due_date:isoDay(date),assigned_to:'',status:'OPEN',created_at:isoDay(romeToday()),completed_at:null,outcome:'',metadata:{origin:'QA_POINT7'},updated_at:isoDay(romeToday())}}
function dbForDay8(withAppointment=false){const t=romeToday(),start=addDays(t,-7),yesterday=addDays(t,-1),tomorrow=addDays(t,1),fsbo=lead('fsbo-owner','Privato','FSBO','FSBO vendita privata','Via Roma','3330000101'),expired=lead('expired-owner','Scaduto','EXPIRED_VERIFIED','INCARICO_SCADUTO_VERIFICATO','Via Celle','3330000102'),tasks=[task('tomorrow-follow','fsbo-owner','FOLLOW_UP','Follow-up domani QA',tomorrow)],attempt={campaign_id:'p90-attempt-1',user_id:USER,campaign_type:'F1_90_DAY_ATTEMPT',property_id:'',territory_key:'ATTEMPT_1',name:'PROGRAMMA 90 GIORNI · TENTATIVO 1',status:'ACTIVE',starts_at:isoDay(start),ends_at:null,metadata:{attempt_number:1,start_date:start,completed_days:7,next_day_number:8,last_completed_date:yesterday},created_at:isoDay(start),updated_at:isoDay(t)};if(withAppointment)tasks.push(task('future-appointment','expired-owner','APPOINTMENT','Appuntamento acquisizione',tomorrow));return{campaigns:[{campaign_id:'p90-program-8',user_id:USER,campaign_type:'F1_90_DAY_PROGRAM',property_id:'',territory_key:'90_DAYS',name:'F1 PROGRAMMA OPERATIVO 90 GIORNI',status:'ACTIVE',starts_at:isoDay(start),ends_at:null,metadata:{},created_at:isoDay(start),updated_at:isoDay(t)},attempt],properties:[],leads:[fsbo,expired],events:[],interactions:[],tasks,referrals:[]}}
async function backend(context,db){await context.addInitScript(()=>sessionStorage.setItem('f1SupabaseSession',JSON.stringify({access_token:'qa-p90-point7',refresh_token:'qa-refresh',expires_at:4102444800000,user:{id:'00000000-0000-4000-8000-000000000001'}})));await context.route(AUTH+'user',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({id:USER,role:'authenticated'})}));await context.route(REST+'**',async route=>{const req=route.request(),u=new URL(req.url()),table=u.pathname.split('/').pop(),method=req.method();if(!(table in db))return route.fulfill({status:200,contentType:'application/json',body:'[]'});if(method==='GET')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(db[table])});if(method==='POST'){const raw=JSON.parse(req.postData()||'[]'),rows=Array.isArray(raw)?raw:[raw],field=idField(table);for(const row of rows){row[field]=row[field]||uuid();row.user_id=row.user_id||USER;const i=db[table].findIndex(x=>String(x[field])===String(row[field]));i>=0?db[table][i]={...db[table][i],...row}:db[table].push({...row})}return route.fulfill({status:201,contentType:'application/json',body:JSON.stringify(rows)})}if(method==='PATCH'){const patch=JSON.parse(req.postData()||'{}'),field=idField(table),value=(u.searchParams.get(field)||'').replace(/^eq\./,'');const changed=[];for(let i=0;i<db[table].length;i++)if(!value||String(db[table][i][field])===String(value)){db[table][i]={...db[table][i],...patch};changed.push(db[table][i])}return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(changed)})}if(method==='DELETE'){const field=idField(table),value=(u.searchParams.get(field)||'').replace(/^eq\./,'');db[table]=db[table].filter(x=>String(x[field])!==String(value));return route.fulfill({status:204,body:''})}return route.fulfill({status:204,body:''})})}
async function ready(page){await expect(page.locator('#cloudStatus')).toContainText('CRM UNIFICATO CONNESSO');await expect.poll(()=>page.evaluate(()=>!!window.F190?.state?.day)).toBeTruthy()}

test('Giorno 8 senza appuntamento -> 2 proprietari FSBO/Expired -> Interazioni CRM reali',async({browser})=>{const db=dbForDay8(false),context=await browser.newContext();await backend(context,db);const page=await context.newPage();await page.goto('/program-90.html');await ready(page);await expect(page.locator('#dayNumber')).toContainText('GIORNO 8 / 90');await expect(page.locator('#noAppointmentPanel')).toBeVisible();await expect(page.locator('#noAppointmentState')).toContainText('NESSUN APPUNTAMENTO PROGRAMMATO');await expect(page.locator('#noAppointmentCount')).toHaveText('0 / 2');await expect(page.locator('[data-noappt-lead]')).toHaveCount(2);await page.locator('[data-noappt-lead="fsbo-owner"]').click();await expect(page.locator('#noAppointmentCount')).toHaveText('1 / 2');await page.locator('[data-noappt-lead="expired-owner"]').click();await expect(page.locator('#noAppointmentCount')).toHaveText('2 / 2');const ints=db.interactions.filter(i=>i.metadata?.origin==='F1_90_NO_APPOINTMENT_FSBO_EXPIRED');expect(ints).toHaveLength(2);expect(ints.some(i=>i.metadata?.script_id==='F1-006'&&i.interaction_type==='IN_PERSON')).toBeTruthy();expect(ints.some(i=>i.metadata?.script_id==='F1-007'&&i.interaction_type==='IN_PERSON')).toBeTruthy();expect(await page.evaluate(()=>F190.closeChecks().some(x=>x.includes('proprietari FSBO/Expired presentati')))).toBeFalsy();await context.close()});

test('Giorno 8 con appuntamento programmato -> missione 2 proprietari non richiesta',async({browser})=>{const db=dbForDay8(true),context=await browser.newContext();await backend(context,db);const page=await context.newPage();await page.goto('/program-90.html');await ready(page);await expect(page.locator('#noAppointmentPanel')).toBeVisible();await expect(page.locator('#noAppointmentState')).toContainText('APPUNTAMENTO PROGRAMMATO');expect(await page.evaluate(()=>F190.noAppointmentRequired())).toBeFalsy();expect(await page.evaluate(()=>F190.closeChecks().some(x=>x.includes('proprietari FSBO/Expired presentati')))).toBeFalsy();await context.close()});

test('Giorno 8 senza appuntamento e senza 2 presentazioni -> chiusura NON_COMPLETATA e tentativo interrotto',async({browser})=>{const db=dbForDay8(false),context=await browser.newContext();await backend(context,db);const page=await context.newPage();await page.goto('/program-90.html');await ready(page);await page.click('#closeDay');await expect(page.locator('#closeResult')).toContainText('PIANO INTERROTTO');const day=db.campaigns.find(c=>c.campaign_type==='F1_90_DAY_DAY');expect(day.status).toBe('CLOSED');expect(day.metadata.close_status).toBe('NON_COMPLETATA');expect(day.metadata.missing.some(x=>x.includes('0/2 proprietari FSBO/Expired'))).toBeTruthy();expect(day.metadata.snapshot.no_appointment_gate).toEqual({required:true,scheduled_appointments:0,presentations:0});const attempt=db.campaigns.find(c=>c.campaign_type==='F1_90_DAY_ATTEMPT');expect(attempt.status).toBe('INTERRUPTED');expect(attempt.metadata.consecutive_days).toBe(7);expect(db.leads).toHaveLength(2);await context.close()});