const {test,expect}=require('@playwright/test');
const BASE='https://nqnmlsmeiynxbdojeyjt.supabase.co',AUTH=BASE+'/auth/v1/',REST=BASE+'/rest/v1/',USER='00000000-0000-4000-8000-000000000001';
const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Rome'}).format(new Date());
const add=(d,n)=>new Date(Date.parse(d+'T12:00:00Z')+n*86400000).toISOString().slice(0,10),iso=d=>new Date(d+'T12:00:00Z').toISOString();
const uuid=()=>`00000000-0000-4000-8000-${Math.random().toString().slice(2,14).padEnd(12,'0')}`;
const ids={campaigns:'campaign_id',events:'event_id',leads:'lead_id',tasks:'task_id',interactions:'interaction_id',properties:'property_id'};
function lead(id,type='COI'){const t=today();return{lead_id:id,user_id:USER,pillar:1,source_type:type,source:type,created_at:iso(add(t,-90)),first_seen:iso(add(t,-90)),last_seen:iso(t),nome:id,cognome:'QA',azienda:'',telefono:'3330000000',email:'',comune:'Villar Dora',via:'Via Roma',civico:'1',zona:'Centro',immobile_id:'',lead_reason:'QA',lead_score:80,confidence:'HIGH',status:'DA_CONTATTARE',last_contact:null,next_action:'',next_action_date:null,assigned_to:'',notes:'',privacy_basis:'QA',do_not_contact:false,rpo_status:'NON_APPLICABILE',created_by:'qa',updated_at:iso(t),deleted:false}}
function interaction(id,leadId,outcome,type='CALL',meta={}){const t=today();return{interaction_id:id,user_id:USER,lead_id:leadId,property_id:'',task_id:null,interaction_type:type,direction:'OUTBOUND',occurred_at:iso(t),outcome,note:'QA',next_action:'',next_action_date:null,metadata:meta,created_at:iso(t)}}
function event(id,type,evidence={}){const t=today();return{event_id:id,user_id:USER,event_type:type,pillar:1,lead_id:'',property_id:'',source_id:'QA',evidence_url:'',evidence_type:'QA',evidence,confidence:'OPERATOR_VERIFIED',occurred_at:iso(t),created_at:iso(t)}}
function program(start,status='ACTIVE'){const t=today();return{campaign_id:'program',user_id:USER,campaign_type:'F1_90_DAY_PROGRAM',property_id:'',territory_key:'90_DAYS',name:'F1 PROGRAMMA OPERATIVO 90 GIORNI',status,starts_at:iso(start),ends_at:status==='COMPLETED'?iso(t):null,metadata:{operational_weekdays:[0,1,2,3,4,5,6]},created_at:iso(start),updated_at:iso(t)}}
function attempt(start,completed,status='ACTIVE'){const t=today();return{campaign_id:'attempt',user_id:USER,campaign_type:'F1_90_DAY_ATTEMPT',property_id:'',territory_key:'ATTEMPT_1',name:'TENTATIVO 1',status,starts_at:iso(start),ends_at:status==='COMPLETED'?iso(t):null,metadata:{attempt_number:1,start_date:start,completed_days:completed,consecutive_days:completed,last_completed_date:add(t,-1)},created_at:iso(start),updated_at:iso(t)}}
function day(n){const t=today();return{campaign_id:'day',user_id:USER,campaign_type:'F1_90_DAY_DAY',property_id:'',territory_key:t,name:'DAY '+n,status:'ACTIVE',starts_at:iso(t),ends_at:null,metadata:{attempt_id:'attempt',attempt_number:1,attempt_day_number:n,phase:n<=30?1:n<=60?2:3,blocks:{script:{status:'COMPLETED',elapsed_seconds:3600},prospecting:{status:'COMPLETED',elapsed_seconds:10800},preview:{status:'COMPLETED',elapsed_seconds:7200},followup:{status:'COMPLETED',elapsed_seconds:3600}},close_status:'',missing:[]},created_at:iso(t),updated_at:iso(t)}}
async function backend(context,db){await context.addInitScript(()=>sessionStorage.setItem('f1SupabaseSession',JSON.stringify({access_token:'qa-phases',refresh_token:'qa',expires_at:4102444800000,user:{id:'00000000-0000-4000-8000-000000000001'}})));await context.route(AUTH+'user',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({id:USER,role:'authenticated'})}));await context.route(REST+'**',async route=>{const req=route.request(),u=new URL(req.url()),table=u.pathname.split('/').pop(),method=req.method();if(!(table in db))return route.fulfill({status:200,contentType:'application/json',body:'[]'});if(method==='GET')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(db[table])});if(method==='POST'){const raw=JSON.parse(req.postData()||'[]'),rows=Array.isArray(raw)?raw:[raw],field=ids[table]||table+'_id';for(const row of rows){row[field]=row[field]||uuid();row.user_id=row.user_id||USER;const i=db[table].findIndex(x=>String(x[field])===String(row[field]));i>=0?db[table][i]={...db[table][i],...row}:db[table].push({...row})}return route.fulfill({status:201,contentType:'application/json',body:JSON.stringify(rows)})}if(method==='PATCH'){const patch=JSON.parse(req.postData()||'{}'),field=ids[table]||table+'_id',value=(u.searchParams.get(field)||'').replace(/^eq\./,'');const changed=[];for(let i=0;i<db[table].length;i++)if(!value||String(db[table][i][field])===String(value)){db[table][i]={...db[table][i],...patch};changed.push(db[table][i])}return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(changed)})}return route.fulfill({status:204,body:''})})}
async function ready(page){await expect(page.locator('#cloudStatus')).toContainText('CRM UNIFICATO CONNESSO');await expect.poll(()=>page.evaluate(()=>!!window.F190Advanced)).toBeTruthy()}

test('GIORNO 30 -> 31 attiva fase 2, doppio role-play e target 6/3',async({browser})=>{const t=today(),start=add(t,-30),leads=[lead('fsbo','FSBO'),lead('db','COI'),lead('jls','COI')],ints=[];for(let i=0;i<5;i++)ints.push(interaction('f'+i,'fsbo','PARLATO'));for(let i=0;i<7;i++)ints.push(interaction('d'+i,'db','PARLATO'));for(let i=0;i<20;i++)ints.push(interaction('j'+i,'jls','PARLATO','CALL',{origin:'JUST_LISTED',script_id:'F1-004'}));for(let i=0;i<6;i++)ints.push(interaction('a'+i,'db','APPUNTAMENTO_SVOLTO','APPOINTMENT',{result_type:'APPOINTMENT',result_status:'SVOLTO'}));for(let i=0;i<3;i++)ints.push(interaction('c'+i,['fsbo','db','jls'][i],'CONTRATTO_FIRMATO','CONTRACT',{result_type:'CONTRACT',result_status:'FIRMATO'}));const db={campaigns:[program(start),attempt(start,30),day(31)],events:[],leads,interactions:ints,tasks:[],properties:[]},context=await browser.newContext();await backend(context,db);const page=await context.newPage();await page.goto('/program-90.html');await ready(page);await expect(page.locator('#advPhaseTitle')).toContainText('GIORNI 31–60');await expect(page.locator('#advPeriodTarget')).toHaveText('6 APPUNTAMENTI / 3 CONTRATTI');await expect(page.locator('#advTrainingPanel')).toBeVisible();await expect(page.locator('#advProspectingStats')).toContainText('5 / 5');await expect(page.locator('#advProspectingStats')).toContainText('7 / 7');await expect(page.locator('#advProspectingStats')).toContainText('20 / 20');await expect(page.locator('#advTrainingPanel')).toContainText('F1-006');await expect(page.locator('#advTrainingPanel')).toContainText('F1-007');await context.close()});

test('GIORNO 60 -> 61 attiva 30 contatti reali, KPI qualità, accountability e target 8/4',async({browser})=>{const t=today(),start=add(t,-60),leads=[lead('l1','COI'),lead('l2','FSBO')],ints=[];for(let i=0;i<30;i++)ints.push(interaction('p'+i,i%2?'l1':'l2',i<5?'INTERESSATO':'PARLATO'));for(let i=0;i<8;i++)ints.push(interaction('a'+i,'l1','APPUNTAMENTO_SVOLTO','APPOINTMENT',{result_type:'APPOINTMENT',result_status:'SVOLTO'}));for(let i=0;i<4;i++)ints.push(interaction('c'+i,i%2?'l1':'l2','CONTRATTO_FIRMATO','CONTRACT',{result_type:'CONTRACT',result_status:'FIRMATO'}));const ev=[event('ap1','F1_90_ACCOUNTABILITY_PARTNER',{partner_id:'ap1',name:'Partner A',active:true}),event('ap2','F1_90_ACCOUNTABILITY_PARTNER',{partner_id:'ap2',name:'Partner B',active:true})],db={campaigns:[program(start),attempt(start,60),day(61)],events:ev,leads,interactions:ints,tasks:[],properties:[]},context=await browser.newContext();await backend(context,db);const page=await context.newPage();await page.goto('/program-90.html');await ready(page);await expect(page.locator('#advPhaseTitle')).toContainText('GIORNI 61–90');await expect(page.locator('#advPeriodTarget')).toHaveText('8 APPUNTAMENTI / 4 CONTRATTI');await expect(page.locator('#advProspectingStats')).toContainText('30 / 30');await expect(page.locator('#advProspectingStats')).toContainText('TENTATIVI');await expect(page.locator('#advProspectingStats')).toContainText('CONVERSAZIONI');await expect(page.locator('#advProspectingStats')).toContainText('LEAD QUALIFICATI');await expect(page.locator('#advAccountPanel')).toBeVisible();await expect(page.locator('#advAccountState')).toContainText('2/2');await expect(page.locator('#advFullKpiPanel')).toBeVisible();await expect(page.locator('#advFullKpiPanel')).toContainText('30 / 30');await expect(page.locator('#advFullKpiPanel')).toContainText('APPUNTAMENTI SETTIMANA');await context.close()});

test('fase 3 blocca chiusura sotto 30 contatti reali',async({browser})=>{const t=today(),start=add(t,-60),leads=[lead('l1','COI')],ints=[];for(let i=0;i<29;i++)ints.push(interaction('p'+i,'l1','PARLATO'));const ev=[event('ap1','F1_90_ACCOUNTABILITY_PARTNER',{partner_id:'ap1',name:'A',active:true}),event('ap2','F1_90_ACCOUNTABILITY_PARTNER',{partner_id:'ap2',name:'B',active:true}),event('check','F1_90_ACCOUNTABILITY_CHECK',{partner_id:'ap1'}),event('ref','F1_90_DAY_REFLECTION',{good:'x',improve:'y'})],db={campaigns:[program(start),attempt(start,60),day(61)],events:ev,leads,interactions:ints,tasks:[],properties:[]},context=await browser.newContext();await backend(context,db);const page=await context.newPage();await page.goto('/program-90.html');await ready(page);await page.click('#closeDay');await expect(page.locator('#cloudStatus')).toContainText('CHIUSURA BLOCCATA');await expect(page.locator('#closeResult')).toContainText('CONTATTI REALI: 29/30');expect(db.campaigns.find(c=>c.campaign_id==='day').status).toBe('ACTIVE');await context.close()});

test('GIORNO 90 completato mostra revisione e crea piano 18 mesi senza cancellare storico',async({browser})=>{const t=today(),start=add(t,-89),p=program(start,'COMPLETED'),a=attempt(start,90,'COMPLETED');a.ends_at=iso(t);const db={campaigns:[p,a],events:[],leads:[lead('l1','COI')],interactions:[interaction('a1','l1','APPUNTAMENTO_SVOLTO','APPOINTMENT',{result_type:'APPOINTMENT',result_status:'SVOLTO'}),interaction('c1','l1','CONTRATTO_FIRMATO','CONTRACT',{result_type:'CONTRACT',result_status:'FIRMATO'})],tasks:[],properties:[]},context=await browser.newContext();await backend(context,db);const page=await context.newPage();await page.goto('/program-90.html');await ready(page);await expect(page.locator('#adv90Panel')).toBeVisible();await expect(page.locator('#adv90Panel')).toContainText('90 GIORNI COMPLETATI');await page.click('#advCreate18');await expect(page.locator('#adv18State')).toContainText('PIANO 18 MESI CREATO');expect(db.campaigns.some(c=>c.campaign_type==='F1_18_MONTH_PLAN'&&c.metadata?.created_from_real_90_day_results)).toBeTruthy();expect(db.campaigns.some(c=>c.campaign_type==='F1_90_DAY_PROGRAM'&&c.status==='COMPLETED')).toBeTruthy();await context.close()});