const {test,expect}=require('@playwright/test');
const BASE='https://nqnmlsmeiynxbdojeyjt.supabase.co',AUTH=BASE+'/auth/v1/',REST=BASE+'/rest/v1/';
const USER='00000000-0000-4000-8000-000000000001';
const idField=t=>({campaigns:'campaign_id',events:'event_id',leads:'lead_id',tasks:'task_id',interactions:'interaction_id',properties:'property_id',referrals:'referral_id'}[t]||t+'_id');
const iso=d=>new Date(d+'T12:00:00Z').toISOString();
function fixture(lastCompleted){return{campaigns:[{campaign_id:'program',user_id:USER,campaign_type:'F1_90_DAY_PROGRAM',property_id:'',territory_key:'90_DAYS',name:'F1 PROGRAMMA OPERATIVO 90 GIORNI',status:'ACTIVE',starts_at:iso('2026-09-01'),ends_at:null,metadata:{operational_weekdays:[1,2,3,4,5]},created_at:iso('2026-09-01'),updated_at:iso(lastCompleted)},{campaign_id:'attempt-1',user_id:USER,campaign_type:'F1_90_DAY_ATTEMPT',property_id:'',territory_key:'ATTEMPT_1',name:'TENTATIVO 1',status:'ACTIVE',starts_at:iso('2026-09-07'),ends_at:null,metadata:{attempt_number:1,start_date:'2026-09-07',completed_days:4,next_day_number:5,last_completed_date:lastCompleted},created_at:iso('2026-09-07'),updated_at:iso(lastCompleted)}],events:[],leads:[],tasks:[],interactions:[],properties:[],referrals:[]}}
async function backend(context,db){await context.addInitScript(()=>sessionStorage.setItem('f1SupabaseSession',JSON.stringify({access_token:'qa-opdays',refresh_token:'qa',expires_at:4102444800000,user:{id:'00000000-0000-4000-8000-000000000001'}})));await context.route(AUTH+'user',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({id:USER,role:'authenticated'})}));await context.route(REST+'**',async route=>{const req=route.request(),u=new URL(req.url()),table=u.pathname.split('/').pop(),method=req.method(),rows=db[table];if(!rows)return route.fulfill({status:200,contentType:'application/json',body:'[]'});if(method==='GET')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(rows)});if(method==='POST'){const raw=JSON.parse(req.postData()||'[]'),items=Array.isArray(raw)?raw:[raw],field=idField(table);for(const row of items){row[field]=row[field]||crypto.randomUUID();row.user_id=row.user_id||USER;const i=rows.findIndex(x=>String(x[field])===String(row[field]));i>=0?rows[i]={...rows[i],...row}:rows.push({...row})}return route.fulfill({status:201,contentType:'application/json',body:JSON.stringify(items)})}if(method==='PATCH'){const patch=JSON.parse(req.postData()||'{}'),field=idField(table),value=(u.searchParams.get(field)||'').replace(/^eq\./,''),changed=[];for(let i=0;i<rows.length;i++)if(!value||String(rows[i][field])===String(value)){rows[i]={...rows[i],...patch};changed.push(rows[i])}return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(changed)})}return route.fulfill({status:204,body:''})})}
async function ready(page){await expect(page.locator('#cloudStatus')).toContainText('CRM UNIFICATO CONNESSO');await expect.poll(()=>page.evaluate(()=>!!window.F190)).toBeTruthy()}

test('weekend non programmato non resetta la sequenza: venerdì -> lunedì',async({browser})=>{const db=fixture('2026-09-11'),context=await browser.newContext();await backend(context,db);const page=await context.newPage();await page.clock.install({time:new Date('2026-09-14T10:00:00+02:00')});await page.goto('/program-90.html');await ready(page);await expect(page.locator('#dayNumber')).toContainText('GIORNO 5 / 90');expect(db.campaigns.find(c=>c.campaign_id==='attempt-1').status).toBe('ACTIVE');expect(db.campaigns.filter(c=>c.campaign_type==='F1_90_DAY_ATTEMPT')).toHaveLength(1);expect(db.campaigns.some(c=>c.campaign_type==='F1_90_DAY_DAY'&&c.territory_key==='2026-09-14')).toBeTruthy();await context.close()});

test('giornata operativa prevista saltata resetta: giovedì -> sabato rileva venerdì mancante',async({browser})=>{const db=fixture('2026-09-10'),context=await browser.newContext();await backend(context,db);const page=await context.newPage();await page.clock.install({time:new Date('2026-09-12T10:00:00+02:00')});await page.goto('/program-90.html');await ready(page);const old=db.campaigns.find(c=>c.campaign_id==='attempt-1');expect(old.status).toBe('INTERRUPTED');expect(old.metadata.interruption_date).toBe('2026-09-11');await expect(page.locator('#dayState')).toContainText('GIORNATA NON OPERATIVA');expect(db.campaigns.filter(c=>c.campaign_type==='F1_90_DAY_DAY'&&c.territory_key==='2026-09-12')).toHaveLength(0);expect(db.campaigns.filter(c=>c.campaign_type==='F1_90_DAY_ATTEMPT'&&c.status==='ACTIVE')).toHaveLength(0);expect(db.events.some(e=>e.event_type==='F1_90_ATTEMPT_RESET')).toBeTruthy();await context.close()});