const {test,expect}=require('@playwright/test');
const BASE='https://nqnmlsmeiynxbdojeyjt.supabase.co',AUTH=BASE+'/auth/v1/',REST=BASE+'/rest/v1/';
const USER='00000000-0000-4000-8000-000000000001';
const uuid=()=>`00000000-0000-4000-8000-${Math.random().toString().slice(2,14).padEnd(12,'0')}`;
const idField=t=>({leads:'lead_id',tasks:'task_id',interactions:'interaction_id',campaigns:'campaign_id',properties:'property_id',events:'event_id',referrals:'referral_id'}[t]||t+'_id');
const romeToday=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Rome'}).format(new Date());
const addDays=(d,n)=>new Date(Date.parse(d+'T12:00:00Z')+n*86400000).toISOString().slice(0,10);
const isoDay=d=>new Date(d+'T12:00:00Z').toISOString();
function lead(id,nome,phone='3330000000'){const t=romeToday();return{lead_id:id,user_id:USER,pillar:2,source_type:'COI',source:'QA',source_url:'',created_at:isoDay(addDays(t,-30)),first_seen:isoDay(addDays(t,-30)),last_seen:isoDay(t),nome,cognome:'QA',azienda:'',telefono:phone,email:'',comune:'Villar Dora',via:'Via Roma',civico:'',zona:'Centro',immobile_id:'',competitor_agency:'',lead_reason:'QA',lead_score:70,confidence:'HIGH',status:'DA_CONTATTARE',last_contact:null,next_action:'',next_action_date:null,assigned_to:'',notes:'',privacy_basis:'QA',do_not_contact:false,rpo_status:'NON_APPLICABILE',created_by:'qa',updated_at:isoDay(t),deleted:false}}
function task(id,leadId,type,reason,date,status='OPEN'){return{task_id:id,user_id:USER,lead_id:leadId,property_id:'',event_id:null,pillar:2,task_type:type,reason,priority:70,due_date:isoDay(date),assigned_to:'',status,created_at:isoDay(addDays(romeToday(),-1)),completed_at:null,outcome:'',metadata:{origin:'QA'},updated_at:isoDay(romeToday())}}
function prop(i){const t=romeToday();return{property_id:'p90-prop-'+i,user_id:USER,comune:'Villar Dora',via:['Via Roma','Via Celle','Via Cuminie','Via San Vincenzo','Via Borgionera'][i-1],civico:String(i),zona:'Centro',frazione:'',latitude:null,longitude:null,tipologia:i%2?'appartamento':'villa',caratteristiche:{prezzo:180000+i*10000,mq:80+i*5,source:'QA',source_url:'https://example.com/p90-'+i,market_party:'DA_VERIFICARE'},first_seen:isoDay(addDays(t,-i)),last_seen:isoDay(t),status:'OSSERVATO',fingerprint:'p90-'+i,created_at:isoDay(addDays(t,-i)),updated_at:isoDay(t),deleted:false}}
async function backend(context,db){await context.addInitScript(()=>sessionStorage.setItem('f1SupabaseSession',JSON.stringify({access_token:'qa-p90',refresh_token:'qa-refresh',expires_at:4102444800000,user:{id:'00000000-0000-4000-8000-000000000001'}})));await context.route(AUTH+'user',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({id:USER,role:'authenticated'})}));await context.route(REST+'**',async route=>{const req=route.request(),u=new URL(req.url()),table=u.pathname.split('/').pop(),method=req.method();if(!(table in db))return route.fulfill({status:200,contentType:'application/json',body:'[]'});if(method==='GET')return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(db[table])});if(method==='POST'){const raw=JSON.parse(req.postData()||'[]'),rows=Array.isArray(raw)?raw:[raw],field=idField(table);for(const row of rows){row[field]=row[field]||uuid();row.user_id=row.user_id||USER;const i=db[table].findIndex(x=>String(x[field])===String(row[field]));i>=0?db[table][i]={...db[table][i],...row}:db[table].push({...row})}return route.fulfill({status:201,contentType:'application/json',body:JSON.stringify(rows)})}if(method==='PATCH'){const patch=JSON.parse(req.postData()||'{}'),field=idField(table),value=(u.searchParams.get(field)||'').replace(/^eq\./,'');const changed=[];for(let i=0;i<db[table].length;i++)if(!value||String(db[table][i][field])===String(value)){db[table][i]={...db[table][i],...patch};changed.push(db[table][i])}return route.fulfill({status:200,contentType:'application/json',body:JSON.stringify(changed)})}if(method==='DELETE'){const field=idField(table),value=(u.searchParams.get(field)||'').replace(/^eq\./,'');db[table]=db[table].filter(x=>String(x[field])!==String(value));return route.fulfill({status:204,body:''})}return route.fulfill({status:204,body:''})})}
async function readyProgram(page){await expect(page.locator('#cloudStatus')).toContainText('CRM UNIFICATO CONNESSO');await expect.poll(()=>page.evaluate(()=>!!window.F190?.state?.day)).toBeTruthy()}
async function readyCrm(page){await expect(page.locator('body')).toContainText('CRM');await expect.poll(()=>page.evaluate(()=>!!window.F1AcquisitionData?.addInteraction)).toBeTruthy()}
test('Dashboard -> Programma 90 -> giornata completa -> CRM/KPI -> chiusura -> giorno successivo',async({browser})=>{
  const t=romeToday(),start=addDays(t,-11),yesterday=addDays(t,-1),tomorrow=addDays(t,1),program={campaign_id:'p90-program',user_id:USER,campaign_type:'F1_90_DAY_PROGRAM',property_id:'',territory_key:'90_DAYS',name:'F1 PROGRAMMA OPERATIVO 90 GIORNI',status:'ACTIVE',starts_at:isoDay(start),ends_at:null,metadata:{},created_at:isoDay(start),updated_at:isoDay(t)},attempt={campaign_id:'p90-attempt',user_id:USER,campaign_type:'F1_90_DAY_ATTEMPT',property_id:'',territory_key:'ATTEMPT_1',name:'PROGRAMMA 90 GIORNI · TENTATIVO 1',status:'ACTIVE',starts_at:isoDay(start),ends_at:null,metadata:{attempt_number:1,start_date:start,completed_days:11,next_day_number:12,last_completed_date:yesterday},created_at:isoDay(start),updated_at:isoDay(t)},db={campaigns:[program,attempt],properties:[1,2,3,4,5].map(prop),leads:[lead('prospect-lead','Prospect','3330000001'),lead('follow-lead','Follow','3330000002')],events:[],interactions:[],tasks:[],referrals:[]};
  for(let i=1;i<=10;i++)db.tasks.push(task(`00000000-0000-4000-8000-${String(i).padStart(12,'0')}`,'follow-lead','FOLLOW_UP',`Follow-up QA ${i}`,t));
  db.tasks.push(task('00000000-0000-4000-8000-999999999999','follow-lead','FOLLOW_UP','Follow-up domani QA',tomorrow));
  const context=await browser.newContext();await backend(context,db);const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(String(e)));
  await page.goto('/index.html');await expect(page.locator('#program90Widget')).toContainText('PROGRAMMA 90 GIORNI');await page.goto('/program-90.html');await readyProgram(page);await expect(page.locator('#dayNumber')).toContainText('GIORNO 12 / 90');expect(db.campaigns.some(c=>c.campaign_type==='F1_90_DAY_DAY'&&c.territory_key===t)).toBeTruthy();
  const scriptCard=page.locator('[data-block="script"]');await scriptCard.getByRole('button',{name:'AVVIA'}).click();await page.goto('/script.html#allenamento-script');await expect(page.locator('#allenamento-script')).toBeVisible();await page.goto('/program-90.html');await readyProgram(page);await page.evaluate(()=>{window.F190.state.day.metadata.blocks.script.started_at=new Date(Date.now()-3600*1000).toISOString()});await page.click('#logRoleplay');await scriptCard.getByRole('button',{name:'COMPLETA'}).click();await expect(page.locator('#kScriptMin')).toHaveText(/60|61/);await expect(page.locator('#kRoleplay')).toHaveText('1');
  await page.locator('[data-block="prospecting"] [data-act="start"]').click();await page.goto('/crm.html');await readyCrm(page);await page.evaluate(async()=>{for(let i=0;i<15;i++)await F1AcquisitionData.addInteraction({lead_id:'prospect-lead',property_id:'',interaction_type:'CALL',direction:'OUTBOUND',occurred_at:new Date().toISOString(),outcome:i===0?'APPUNTAMENTO_FISSATO':'PARLATO',note:'Prospecting QA '+i,metadata:{origin:'PROGRAM_90_QA'}})});await page.goto('/program-90.html');await readyProgram(page);await page.evaluate(()=>{window.F190.state.day.metadata.blocks.prospecting.started_at=new Date(Date.now()-150*60*1000).toISOString()});await page.locator('[data-block="prospecting"] [data-act="complete"]').click();await expect(page.locator('#kProspecting')).toHaveText('15');await expect(page.locator('#kConversations')).toHaveText('15');await expect(page.locator('#kAppointments')).toHaveText('0');
  await page.locator('[data-block="preview"] [data-act="start"]').click();await page.goto('/market-preview.html');await expect(page.locator('#cloudStatus')).toContainText('CRM UNIFICATO CONNESSO');await expect(page.locator('.item')).toHaveCount(5);for(let i=0;i<5;i++){const card=page.locator('.item').nth(i);await card.getByRole('button',{name:'APRI PREVIEW'}).click();await page.fill('#pMinutes','20');if(i===0)await page.locator('#signalGrid input[value="VENDITA_DA_PRIVATO"]').check();await page.click('#markVisioned');await expect(page.locator('#previewStatus')).toContainText('VISIONATO REGISTRATO');await page.click('#closePreview')}await page.locator('.item').first().getByRole('button',{name:'APRI PREVIEW'}).click();await page.click('#newOpportunity');await page.fill('#oName','Mario');await page.fill('#oSurname','Market');await page.fill('#oPhone','3330000099');await page.check('#oRpoVerified');await page.click('#checkDuplicates');await page.click('#createCrm');await expect(page.locator('#oppResult')).toContainText('CRM UNIFICATO AGGIORNATO');expect(db.leads.some(l=>l.nome==='Mario'&&l.created_by==='market_preview')).toBeTruthy();await page.goto('/program-90.html');await readyProgram(page);await page.evaluate(()=>{window.F190.state.day.metadata.blocks.preview.started_at=new Date(Date.now()-120*60*1000).toISOString()});await page.locator('[data-block="preview"] [data-act="complete"]').click();await expect(page.locator('#kPreview')).toHaveText('5');await expect(page.locator('#kOpportunities')).not.toHaveText('0');
  await expect(page.locator('#dueFollowupCount')).toHaveText('10');await page.locator('[data-block="followup"] [data-act="start"]').click();await page.goto('/crm.html');await readyCrm(page);await page.evaluate(async()=>{const ids=Array.from({length:10},(_,i)=>`00000000-0000-4000-8000-${String(i+1).padStart(12,'0')}`);for(const id of ids)await F1AcquisitionData.recordOutcome({leadId:'follow-lead',taskId:id,interactionType:'CALL',direction:'OUTBOUND',outcome:'PARLATO',note:'Follow-up QA completato',status:'RICHIAMO'})});await page.goto('/program-90.html');await readyProgram(page);await page.evaluate(()=>{window.F190.state.day.metadata.blocks.followup.started_at=new Date(Date.now()-60*60*1000).toISOString()});await page.locator('[data-block="followup"] [data-act="complete"]').click();await expect(page.locator('#kFollowup')).toHaveText('10');await expect(page.locator('#headCompleted')).toHaveText('4 / 4');
  await page.click('#closeDay');await expect(page.locator('#closeResult')).toContainText('GIORNO 12 COMPLETATO');const day=db.campaigns.find(c=>c.campaign_type==='F1_90_DAY_DAY'&&c.territory_key===t);expect(day.status).toBe('CLOSED');expect(day.metadata.close_status).toBe('COMPLETATA');expect(db.events.some(e=>e.event_type==='F1_90_DAY_CLOSED'&&e.evidence?.close_status==='COMPLETATA')).toBeTruthy();expect(db.interactions.length).toBeGreaterThanOrEqual(26);expect(db.campaigns.find(c=>c.campaign_id==='p90-attempt').metadata.completed_days).toBe(12);
  const next=await context.newPage();await next.clock.install({time:new Date(Date.now()+86400000)});await next.goto('/program-90.html');await readyProgram(next);await expect(next.locator('#dayNumber')).toContainText('GIORNO 13 / 90');await expect(next.locator('#followupQueue')).toContainText('Follow-up domani QA');expect(db.campaigns.some(c=>c.campaign_type==='F1_90_DAY_DAY'&&c.territory_key===tomorrow&&c.status==='ACTIVE')).toBeTruthy();expect(db.campaigns.some(c=>c.campaign_type==='F1_90_DAY_DAY'&&c.territory_key===t&&c.status==='CLOSED')).toBeTruthy();
  expect(errors).toEqual([]);await context.close();
});