-- CRM Aziende Real Media Pro
-- Data: 2026-09-30
-- La migrazione crea l'anagrafica aziende e lo storico interazioni aziendali.
create table if not exists public.aziende (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  ragione_sociale text not null,
  partita_iva text, codice_fiscale text,
  settore text not null default '', indirizzo text not null default '', comune text not null default '', cap text not null default '', provincia text not null default '',
  telefono text not null default '', email text not null default '', pec text not null default '', sito_web text not null default '',
  referente_nome text not null default '', referente_cognome text not null default '', referente_telefono text not null default '', referente_email text not null default '', referente_ruolo text not null default '',
  canale_acquisizione text not null default '', stato text not null default 'DA_CONTATTARE', interesse text not null default '',
  budget_stimato numeric(12,2), note text not null default '', data_acquisizione date, ultima_interazione date,
  prossima_azione text not null default '', data_prossima_azione date, lead_score integer not null default 0,
  do_not_contact boolean not null default false, privacy_basis text not null default '',
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  constraint aziende_stato_check check (stato in ('DA_CONTATTARE','CONTATTATA','IN_TRATTATIVA','CLIENTE','PERSO')),
  constraint aziende_lead_score_check check (lead_score between 0 and 100)
);
create index if not exists aziende_user_id_idx on public.aziende(user_id);
create index if not exists aziende_stato_idx on public.aziende(stato);
create index if not exists aziende_comune_idx on public.aziende(comune);
create index if not exists aziende_settore_idx on public.aziende(settore);
create index if not exists aziende_partita_iva_idx on public.aziende(partita_iva);
create index if not exists aziende_email_idx on public.aziende(lower(email));
create index if not exists aziende_telefono_idx on public.aziende(telefono);
alter table public.aziende enable row level security;
drop policy if exists "f1 staff select aziende" on public.aziende;
drop policy if exists "f1 staff insert aziende" on public.aziende;
drop policy if exists "f1 staff update aziende" on public.aziende;
drop policy if exists "f1 admin delete aziende" on public.aziende;
create policy "f1 staff select aziende" on public.aziende for select to authenticated using ((select f1_private.can_access_user(aziende.user_id)));
create policy "f1 staff insert aziende" on public.aziende for insert to authenticated with check ((select f1_private.current_staff_role()) <> '' and (select auth.uid()) = user_id);
create policy "f1 staff update aziende" on public.aziende for update to authenticated using ((select f1_private.can_access_user(aziende.user_id))) with check ((select f1_private.can_access_user(aziende.user_id)));
create policy "f1 admin delete aziende" on public.aziende for delete to authenticated using ((select f1_private.is_titolare()));
grant select,insert,update,delete on public.aziende to authenticated;
create or replace function public.f1_aziende_touch_updated_at() returns trigger language plpgsql as $$
begin new.updated_at=now(); return new; end; $$;
drop trigger if exists aziende_touch_updated_at on public.aziende;
create trigger aziende_touch_updated_at before update on public.aziende for each row execute function public.f1_aziende_touch_updated_at();

create table if not exists public.azienda_interactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null default auth.uid() references auth.users(id) on delete cascade,
  azienda_id bigint not null references public.aziende(id) on delete cascade,
  interaction_type text not null default 'NOTE', direction text not null default 'OUTBOUND',
  occurred_at timestamptz not null default now(), outcome text not null default '', note text not null default '',
  next_action text not null default '', next_action_date date, created_at timestamptz not null default now()
);
create index if not exists azienda_interactions_azienda_idx on public.azienda_interactions(azienda_id,occurred_at desc);
alter table public.azienda_interactions enable row level security;
drop policy if exists "f1 staff select azienda interactions" on public.azienda_interactions;
drop policy if exists "f1 staff insert azienda interactions" on public.azienda_interactions;
drop policy if exists "f1 admin delete azienda interactions" on public.azienda_interactions;
create policy "f1 staff select azienda interactions" on public.azienda_interactions for select to authenticated using ((select f1_private.can_access_user(azienda_interactions.user_id)));
create policy "f1 staff insert azienda interactions" on public.azienda_interactions for insert to authenticated with check ((select f1_private.current_staff_role()) <> '' and (select auth.uid()) = user_id);
create policy "f1 admin delete azienda interactions" on public.azienda_interactions for delete to authenticated using ((select f1_private.is_titolare()));
grant select,insert,delete on public.azienda_interactions to authenticated;

-- Deduplicazione forte: il telefono normalizzato è unico per utente.
create unique index if not exists aziende_user_telefono_unique on public.aziende(user_id, telefono) where telefono is not null and telefono <> '';
