-- F1 CRM AZIENDE — import incrementale, code commerciali e protezione modifiche manuali
-- Produzione applicata 2026-10-05.

alter table public.aziende
  add column if not exists cellulare text not null default '',
  add column if not exists telefono_fisso text not null default '',
  add column if not exists processing_status text not null default 'IMPORTATA',
  add column if not exists source_file text not null default '',
  add column if not exists source_row integer,
  add column if not exists import_batch integer,
  add column if not exists import_job_id uuid,
  add column if not exists source_payload jsonb not null default '{}'::jsonb,
  add column if not exists field_provenance jsonb not null default '{}'::jsonb,
  add column if not exists last_enrichment_at timestamptz,
  add column if not exists enrichment_error text not null default '';

create table if not exists public.azienda_tasks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id),
  azienda_id bigint not null references public.aziende(id) on delete cascade,
  task_type text not null check (task_type in ('CALL','EMAIL','RICERCA_CONTATTO','FOLLOW_UP','APPUNTAMENTO','PROPOSTA')),
  status text not null default 'OPEN' check (status in ('OPEN','IN_PROGRESS','DONE','CANCELLED')),
  destination text not null default '',
  reason text not null default '',
  priority integer not null default 50 check (priority between 0 and 100),
  due_at timestamptz not null default now(),
  completed_at timestamptz,
  outcome text not null default '',
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists azienda_tasks_queue_idx on public.azienda_tasks(status,due_at,priority desc);
create index if not exists azienda_tasks_company_idx on public.azienda_tasks(azienda_id,status);
alter table public.azienda_tasks enable row level security;
revoke all on public.azienda_tasks from anon;
grant select,insert,update,delete on public.azienda_tasks to authenticated;

create table if not exists public.azienda_import_jobs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id),
  source_file text not null,
  total_rows integer not null default 0,
  imported_rows integer not null default 0,
  updated_rows integer not null default 0,
  duplicate_rows integer not null default 0,
  error_rows integer not null default 0,
  current_batch integer not null default 0,
  status text not null default 'RUNNING' check(status in ('RUNNING','PAUSED','DONE','ERROR')),
  started_at timestamptz not null default now(),
  last_batch_at timestamptz,
  completed_at timestamptz,
  metadata jsonb not null default '{}'::jsonb
);
alter table public.azienda_import_jobs enable row level security;
revoke all on public.azienda_import_jobs from anon;
grant select,insert,update on public.azienda_import_jobs to authenticated;

create table if not exists public.azienda_import_errors (
  id bigint generated by default as identity primary key,
  import_job_id uuid not null references public.azienda_import_jobs(id) on delete cascade,
  source_row integer,
  company_name text not null default '',
  error_text text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
alter table public.azienda_import_errors enable row level security;
revoke all on public.azienda_import_errors from anon;
grant select,insert on public.azienda_import_errors to authenticated;

drop policy if exists "f1 staff select azienda tasks" on public.azienda_tasks;
create policy "f1 staff select azienda tasks" on public.azienda_tasks for select to authenticated using ((select f1_private.can_access_user(user_id)));
drop policy if exists "f1 staff insert azienda tasks" on public.azienda_tasks;
create policy "f1 staff insert azienda tasks" on public.azienda_tasks for insert to authenticated with check ((select f1_private.can_access_user(user_id)));
drop policy if exists "f1 staff update azienda tasks" on public.azienda_tasks;
create policy "f1 staff update azienda tasks" on public.azienda_tasks for update to authenticated using ((select f1_private.can_access_user(user_id))) with check ((select f1_private.can_access_user(user_id)));
drop policy if exists "f1 admin delete azienda tasks" on public.azienda_tasks;
create policy "f1 admin delete azienda tasks" on public.azienda_tasks for delete to authenticated using ((select f1_private.is_titolare()));

drop policy if exists "f1 staff select azienda imports" on public.azienda_import_jobs;
create policy "f1 staff select azienda imports" on public.azienda_import_jobs for select to authenticated using ((select f1_private.can_access_user(user_id)));
drop policy if exists "f1 staff insert azienda imports" on public.azienda_import_jobs;
create policy "f1 staff insert azienda imports" on public.azienda_import_jobs for insert to authenticated with check ((select f1_private.can_access_user(user_id)));
drop policy if exists "f1 staff update azienda imports" on public.azienda_import_jobs;
create policy "f1 staff update azienda imports" on public.azienda_import_jobs for update to authenticated using ((select f1_private.can_access_user(user_id))) with check ((select f1_private.can_access_user(user_id)));

drop policy if exists "f1 staff select azienda import errors" on public.azienda_import_errors;
create policy "f1 staff select azienda import errors" on public.azienda_import_errors for select to authenticated
using (exists(select 1 from public.azienda_import_jobs j where j.id=import_job_id and (select f1_private.can_access_user(j.user_id))));
drop policy if exists "f1 staff insert azienda import errors" on public.azienda_import_errors;
create policy "f1 staff insert azienda import errors" on public.azienda_import_errors for insert to authenticated
with check (exists(select 1 from public.azienda_import_jobs j where j.id=import_job_id and (select f1_private.can_access_user(j.user_id))));

drop policy if exists "f1 staff insert azienda interactions" on public.azienda_interactions;
create policy "f1 staff insert azienda interactions" on public.azienda_interactions for insert to authenticated
with check ((select f1_private.can_access_user(user_id)));

create or replace function public.f1_company_import_stats_v1()
returns jsonb language sql stable security invoker set search_path=public,pg_temp as $$
select jsonb_build_object(
  'aziende',count(*),
  'da_arricchire',count(*) filter(where processing_status in ('IMPORTATA','DA_ARRICCHIRE','DATI_PARZIALI','DA_VERIFICARE')),
  'arricchite',count(*) filter(where processing_status='ARRICCHITA'),
  'con_telefono',count(*) filter(where coalesce(nullif(trim(cellulare),''),nullif(trim(telefono_fisso),''),nullif(trim(telefono),'')) is not null),
  'con_email',count(*) filter(where nullif(trim(email),'') is not null),
  'con_pec',count(*) filter(where nullif(trim(pec),'') is not null),
  'con_sito',count(*) filter(where nullif(trim(sito_web),'') is not null),
  'con_referente',count(*) filter(where nullif(trim(concat_ws(' ',referente_nome,referente_cognome)),'') is not null),
  'da_chiamare',(select count(*) from public.azienda_tasks where status='OPEN' and task_type='CALL'),
  'email_da_inviare',(select count(*) from public.azienda_tasks where status='OPEN' and task_type='EMAIL'),
  'richiami',(select count(*) from public.azienda_tasks where status='OPEN' and task_type='FOLLOW_UP'),
  'errori',count(*) filter(where processing_status='ERRORE_ARRICCHIMENTO'),
  'ultimo_aggiornamento',max(updated_at)
) from public.aziende;
$$;
revoke all on function public.f1_company_import_stats_v1() from public,anon;
grant execute on function public.f1_company_import_stats_v1() to authenticated;

create or replace function public.f1_company_apply_enrichment_v1(
  p_azienda_id bigint,p_expected_updated_at timestamptz,p_patch jsonb,p_sources jsonb default '{}'::jsonb
) returns jsonb language plpgsql security invoker set search_path=public,pg_temp as $$
declare a public.aziende%rowtype; prov jsonb;
begin
  select * into a from public.aziende where id=p_azienda_id for update;
  if not found then raise exception 'AZIENDA NON TROVATA'; end if;
  prov:=coalesce(a.field_provenance,'{}'::jsonb);
  update public.aziende x set
    partita_iva=case when trim(coalesce(x.partita_iva,''))='' and coalesce(prov->>'partita_iva','')<>'MANUALE' then coalesce(nullif(trim(p_patch->>'partita_iva'),''),x.partita_iva) else x.partita_iva end,
    codice_fiscale=case when trim(coalesce(x.codice_fiscale,''))='' and coalesce(prov->>'codice_fiscale','')<>'MANUALE' then coalesce(nullif(trim(p_patch->>'codice_fiscale'),''),x.codice_fiscale) else x.codice_fiscale end,
    settore=case when trim(coalesce(x.settore,''))='' and coalesce(prov->>'settore','')<>'MANUALE' then coalesce(nullif(trim(p_patch->>'settore'),''),x.settore) else x.settore end,
    comune=case when trim(coalesce(x.comune,''))='' and coalesce(prov->>'comune','')<>'MANUALE' then coalesce(nullif(trim(p_patch->>'comune'),''),x.comune) else x.comune end,
    cap=case when trim(coalesce(x.cap,''))='' and coalesce(prov->>'cap','')<>'MANUALE' then coalesce(nullif(trim(p_patch->>'cap'),''),x.cap) else x.cap end,
    provincia=case when trim(coalesce(x.provincia,''))='' and coalesce(prov->>'provincia','')<>'MANUALE' then coalesce(nullif(trim(p_patch->>'provincia'),''),x.provincia) else x.provincia end,
    cellulare=case when trim(coalesce(x.cellulare,''))='' and coalesce(prov->>'cellulare','')<>'MANUALE' then coalesce(nullif(trim(p_patch->>'cellulare'),''),x.cellulare) else x.cellulare end,
    telefono_fisso=case when trim(coalesce(x.telefono_fisso,''))='' and coalesce(prov->>'telefono_fisso','')<>'MANUALE' then coalesce(nullif(trim(p_patch->>'telefono_fisso'),''),x.telefono_fisso) else x.telefono_fisso end,
    telefono=case when trim(coalesce(x.telefono,''))='' and coalesce(prov->>'telefono','')<>'MANUALE' then coalesce(nullif(trim(p_patch->>'telefono'),''),x.telefono) else x.telefono end,
    email=case when trim(coalesce(x.email,''))='' and coalesce(prov->>'email','')<>'MANUALE' then coalesce(nullif(trim(p_patch->>'email'),''),x.email) else x.email end,
    pec=case when trim(coalesce(x.pec,''))='' and coalesce(prov->>'pec','')<>'MANUALE' then coalesce(nullif(trim(p_patch->>'pec'),''),x.pec) else x.pec end,
    sito_web=case when trim(coalesce(x.sito_web,''))='' and coalesce(prov->>'sito_web','')<>'MANUALE' then coalesce(nullif(trim(p_patch->>'sito_web'),''),x.sito_web) else x.sito_web end,
    referente_nome=case when trim(coalesce(x.referente_nome,''))='' and coalesce(prov->>'referente_nome','')<>'MANUALE' then coalesce(nullif(trim(p_patch->>'referente_nome'),''),x.referente_nome) else x.referente_nome end,
    referente_cognome=case when trim(coalesce(x.referente_cognome,''))='' and coalesce(prov->>'referente_cognome','')<>'MANUALE' then coalesce(nullif(trim(p_patch->>'referente_cognome'),''),x.referente_cognome) else x.referente_cognome end,
    referente_telefono=case when trim(coalesce(x.referente_telefono,''))='' and coalesce(prov->>'referente_telefono','')<>'MANUALE' then coalesce(nullif(trim(p_patch->>'referente_telefono'),''),x.referente_telefono) else x.referente_telefono end,
    referente_email=case when trim(coalesce(x.referente_email,''))='' and coalesce(prov->>'referente_email','')<>'MANUALE' then coalesce(nullif(trim(p_patch->>'referente_email'),''),x.referente_email) else x.referente_email end,
    referente_ruolo=case when trim(coalesce(x.referente_ruolo,''))='' and coalesce(prov->>'referente_ruolo','')<>'MANUALE' then coalesce(nullif(trim(p_patch->>'referente_ruolo'),''),x.referente_ruolo) else x.referente_ruolo end,
    field_provenance=coalesce(x.field_provenance,'{}'::jsonb)||coalesce(p_sources,'{}'::jsonb),
    processing_status=coalesce(nullif(trim(p_patch->>'processing_status'),''),'DATI_PARZIALI'),
    last_enrichment_at=now(),enrichment_error=''
  where x.id=p_azienda_id;
  return jsonb_build_object('azienda_id',p_azienda_id,'concurrency_unchanged',(a.updated_at=p_expected_updated_at),'updated_at_before',a.updated_at);
end;$$;
revoke all on function public.f1_company_apply_enrichment_v1(bigint,timestamptz,jsonb,jsonb) from public,anon;
grant execute on function public.f1_company_apply_enrichment_v1(bigint,timestamptz,jsonb,jsonb) to authenticated;
