let sectors=[];const imageData=Array(24).fill(null);
const $=id=>document.getElementById(id);
const esc=v=>String(v||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
async function init(){const data=await fetch("./data/sectors.json").then(r=>r.json());sectors=data.sectors;$("sector").innerHTML=sectors.map(s=>"<option value='"+s.id+"'>"+s.label+"</option>").join("");buildImageSlots()}
function buildImageSlots(){$("imageGrid").innerHTML=imageData.map((_,i)=>'<div class="image-slot"><label>IMMAGINE '+(i+1)+'<input type="file" accept="image/*" data-image="'+i+'"></label><img id="preview-'+i+'" class="image-preview" alt="Anteprima '+(i+1)+'"></div>').join("");document.querySelectorAll("[data-image]").forEach(input=>input.onchange=()=>loadImage(input))}
function loadImage(input){const i=Number(input.dataset.image),file=input.files[0];if(!file)return;const reader=new FileReader();reader.onload=e=>{imageData[i]=e.target.result;$("preview-"+i).src=e.target.result};reader.readAsDataURL(file)}
function selected(){return sectors.find(s=>s.id===$("sector").value)||sectors[0]}
function campaignData(){const s=selected(),c=$("company").value.trim()||"La tua attività",o=$("offer").value.trim()||"Offerta del mese",g=$("gift").value.trim()||"Vantaggio riservato",city=$("city").value.trim(),cta=$("cta").value.trim()||"Scopri l'offerta",url=$("registrationUrl").value.trim()||"INSERIRE URL REGISTRAZIONE";
const posts=Array.from({length:12},(_,i)=>"CAMPAGNA "+(i+1)+" — "+o+". "+g+". Registrati tramite QR Code, partecipa e condividi la tua esperienza con #"+c.toLowerCase().replace(/[^a-z0-9]+/g,"")+"."+" "+cta+".");
return{subject:c+" — "+o,email:"Buongiorno,\n\nabbiamo preparato una nuova iniziativa per i clienti di "+c+(city?" a "+city:"")+" .\n\n"+o+".\n\nVantaggio: "+g+".\n\n"+cta+".\n\nTi aspettiamo.\n\n"+c,whatsapp:c+": "+o+". "+g+". "+cta+".",posts,angles:s.angles,url}}
function graphic(){const c=esc($("company").value||"LA TUA ATTIVITÀ"),o=esc($("offer").value||"CAMPAGNA CLIENTI"),g=esc($("gift").value||"VANTAGGIO RISERVATO"),cta=esc($("cta").value||"SCOPRI"),img=imageData.find(Boolean);return '<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="1080"><rect width="1080" height="1080" fill="#111"/>'+(img?'<image href="'+img+'" x="55" y="55" width="970" height="430" preserveAspectRatio="xMidYMid slice"/>':'')+'<rect x="55" y="'+(img?510:55)+'" width="970" height="'+(img?515:970)+'" rx="24" fill="#111" stroke="#d5b46a" stroke-width="3"/><text x="90" y="'+(img?600:150)+'" fill="#d5b46a" font-family="Arial" font-size="28" letter-spacing="5">REALMEDIAPRO · 12 MESI</text><text x="90" y="'+(img?700:330)+'" fill="white" font-family="Arial" font-size="58" font-weight="700">'+c+'</text><text x="90" y="'+(img?805:470)+'" fill="white" font-family="Arial" font-size="42" font-weight="700">'+o+'</text><text x="90" y="'+(img?875:580)+'" fill="#d5b46a" font-family="Arial" font-size="28">'+g+'</text><text x="90" y="'+(img?955:860)+'" fill="white" font-family="Arial" font-size="30">'+cta+'</text></svg>'}
function presentation(){const c=esc($("company").value||"LA TUA ATTIVITÀ"),s=esc(selected().label);return '<!doctype html><html lang="it"><head><meta charset="utf-8"><title>'+c+' — RealMediaPro</title><style>body{font-family:Arial;color:#171717;margin:0}section{min-height:90vh;padding:55px;box-sizing:border-box;page-break-after:always}h1{font-size:46px}h2{font-size:30px}.box{border:1px solid #ccc;padding:22px;margin:18px 0}.price{font-size:36px;font-weight:700}</style></head><body><section><h1>'+c+'</h1><p>'+s+'</p><h2>12 mesi di campagne per acquisire, riattivare e coinvolgere i clienti.</h2><div class="box"><div class="price">€99 attivazione</div><div class="price">€100 / mese</div><p>Eventuali extra vengono consuntivati e fatturati a fine anno.</p></div></section><section><h2>Il percorso</h2><div class="box">Bigliettino + QR Code</div><div class="box">Scansione e registrazione</div><div class="box">Premio/pacco a casa</div><div class="box">Recensione + video + hashtag</div><div class="box">Raccolta UGC e pubblicazione sui canali social</div><div class="box">12 campagne, una ogni mese</div></section><section><h2>Posizionamento</h2><p>Non sei più tu a fare tutta la pubblicità della tua azienda: i clienti possono diventare parte attiva della comunicazione.</p><p>Il sistema punta a generare contenuti, recensioni e presenza online nel tempo.</p></section></body></html>'}
function download(name,data,type){const a=document.createElement("a"),u=URL.createObjectURL(new Blob([data],{type}));a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),500)}
function render(){const c=$("company").value||"La tua attività",d=campaignData();$("output").innerHTML='<h2>Campagna — '+esc(c)+'</h2><div id="qrcode" class="qrbox"></div><div class="actions"><button id="svg">SCARICA GRAFICA</button><button id="pres">SCARICA PRESENTAZIONE A4</button><button id="email">COPIA EMAIL</button><button id="wa">COPIA WHATSAPP</button></div><div class="content"><b>MECCANISMO</b><pre>1. Bigliettino con QR Code\n2. Il cliente scansiona e si registra\n3. Riceve il pacco/promozione a casa\n4. Lascia recensione e, con consenso, video con hashtag del negozio\n5. Il video viene raccolto e pubblicato sui canali social\n6. Il procedimento viene ripetuto con una campagna ogni mese</pre></div><div class="content"><b>12 CAMPAGNE</b><pre>'+esc(d.posts.join("\n\n"))+'</pre></div><div class="content"><b>ANGOLI DEL SETTORE</b><p class="muted">'+esc(d.angles.join(" · "))+'</p></div><div class="content"><b>REGISTRAZIONE</b><p class="muted">'+esc(d.url)+'</p></div>';
if(window.QRCode&&d.url!=="INSERIRE URL REGISTRAZIONE")new QRCode($("qrcode"),{text:d.url,width:180,height:180});
$("svg").onclick=()=>download("campagna-"+c.replace(/\W+/g,"-")+".svg",graphic(),"image/svg+xml");$("pres").onclick=()=>download("presentazione-"+c.replace(/\W+/g,"-")+".html",presentation(),"text/html");$("email").onclick=()=>navigator.clipboard.writeText(d.subject+"\n\n"+d.email);$("wa").onclick=()=>navigator.clipboard.writeText(d.whatsapp)}
$("generate").onclick=render;init();