'use strict';
const VERSION='20260914-companion1';
const SUPABASE_URL='https://nqnmlsmeiynxbdojeyjt.supabase.co';
const ANON_KEY='sb_publishable_Clz5qPTkTtvwV0rqWTcfMQ_sCDSRgnu';
const ALARM_POLL='f1-research-poll',ALARM_NEXT='f1-research-next';
const ACTIVE=new Set(['QUEUED','RUNNING','ANALYZING']);
const PORTAL_DOMAINS=new Set(['immobiliare.it','idealista.it','casa.it','subito.it']);
const SOCIAL_DOMAINS=new Set(['facebook.com','instagram.com','linkedin.com']);
let running=false;
const c=v=>String(v??'').replace(/\s+/g,' ').trim();
const norm=v=>c(v).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const quote=v=>{const x=c(v).replace(/"/g,'');return x?'"'+x+'"':''};
const now=()=>new Date().toISOString();
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function hostOf(value){try{return new URL(value).hostname.toLowerCase().replace(/^www\./,'')}catch(_){return''}}
function canonicalUrl(value){try{const u=new URL(c(value));u.hash='';for(const k of [...u.searchParams.keys()])if(/^utm_|^(fbclid|gclid|ref|source)$/i.test(k))u.searchParams.delete(k);const q=u.searchParams.toString();return(u.origin+u.pathname+(q?'?'+q:'')).replace(/\/$/,'').toLowerCase()}catch(_){return c(value).replace(/#.*$/,'').replace(/\/$/,'').toLowerCase()}}
function normalizePhone(value){let d=c(value).replace(/\D/g,'');if(d.startsWith('0039'))d=d.slice(4);if(d.startsWith('39')&&d.length>10)d=d.slice(2);return /^(?:0\d{5,10}|3\d{8,9})$/.test(d)?d:''}
function normalizeEmail(value){return c(value).toLowerCase()}
function sameHostOrSub(host,base){return host===base||host.endsWith('.'+base)}
async function localGet(keys){return chrome.storage.local.get(keys)}
async function localSet(obj){return chrome.storage.local.set(obj)}
async function session(){return (await localGet('f1Session')).f1Session||null}
async function saveSession(s){await localSet({f1Session:s||null})}
async function deviceId(){let v=(await localGet('f1DeviceId')).f1DeviceId;if(!v){v='comp-'+crypto.randomUUID();await localSet({f1DeviceId:v})}return v}
async function accessToken(){let s=await session();if(!s)throw new Error('SESSIONE_F1_NON_DISPONIBILE');let exp=Number(s.expires_at||0);if(exp&&exp<1e12)exp*=1000;if(s.access_token&&(!exp||Date.now()<exp-60000))return s.access_token;if(!s.refresh_token)throw new Error('SESSIONE_F1_SCADUTA');const res=await fetch(SUPABASE_URL+'/auth/v1/token?grant_type=refresh_token',{method:'POST',headers:{apikey:ANON_KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:s.refresh_token})}),text=await res.text();if(!res.ok)throw new Error('REFRESH_F1_'+res.status);const j=JSON.parse(text);s={...s,...j,refresh_token:j.refresh_token||s.refresh_token};await saveSession(s);return s.access_token}
async function rest(path,opt={}){const token=await accessToken(),res=await fetch(SUPABASE_URL+'/rest/v1/'+path,{...opt,headers:{apikey:ANON_KEY,Authorization:'Bearer '+token,'Content-Type':'application/json',Prefer:opt.prefer||'return=representation',...(opt.headers||{})}}),text=await res.text();if(res.status===401||res.status===403)throw new Error('ACCESSO_SUPABASE_'+res.status);if(!res.ok)throw new Error('SUPABASE_'+res.status+'_'+text.slice(0,240));return text?JSON.parse(text):null}
function scheduleNext(ms=12000){chrome.alarms.create(ALARM_NEXT,{when:Date.now()+ms}).catch(()=>{})}
async function notify(title,message){try{await chrome.notifications.create({type:'basic',iconUrl:'data:image/svg+xml,<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128"><rect width="128" height="128" rx="24" fill="%23070a08"/><text x="64" y="79" text-anchor="middle" font-size="54" fill="%2339f28a">F1</text></svg>',title,message})}catch(_){}}
async function getCandidateJob(){const dev=await deviceId(),rows=await rest('research_jobs?status=in.(QUEUED,RUNNING,ANALYZING)&select=*&order=created_at.asc&limit=10')||[],t=Date.now();for(const j of rows){if(j.status==='QUEUED')return j;if(j.lock_owner===dev)return j;const hb=Date.parse(j.heartbeat_at||j.updated_at||j.created_at||0);if(!hb||t-hb>180000)return j}return null}
async function claimJob(job){const dev=await deviceId(),patch={status:job.status==='QUEUED'?'RUNNING':job.status,started_at:job.started_at||now(),lock_owner:dev,heartbeat_at:now(),updated_at:now(),error:''},rows=await rest('research_jobs?id=eq.'+encodeURIComponent(job.id),{method:'PATCH',body:JSON.stringify(patch),prefer:'return=representation'});return rows?.[0]||{...job,...patch}}
async function patchJob(id,patch){const rows=await rest('research_jobs?id=eq.'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify({...patch,heartbeat_at:now(),updated_at:now()}),prefer:'return=representation'});return rows?.[0]||null}
function completedSet(job){return new Set(Array.isArray(job.completed_queries)?job.completed_queries:[])}
function pendingQuery(job){const done=completedSet(job),plan=Array.isArray(job.query_plan)?job.query_plan:[];return plan.find(q=>q&&q.id&&!done.has(q.id))||null}
async function waitForTab(tabId,timeout=25000){const tab=await chrome.tabs.get(tabId).catch(()=>null);if(tab?.status==='complete')return true;return new Promise(resolve=>{let ended=false;const finish=v=>{if(ended)return;ended=true;clearTimeout(to);chrome.tabs.onUpdated.removeListener(on);resolve(v)},on=(id,info)=>{if(id===tabId&&info.status==='complete')finish(true)},to=setTimeout(()=>finish(false),timeout);chrome.tabs.onUpdated.addListener(on)})}
function scrapeGooglePage(){const body=(document.body?.innerText||'').toLowerCase(),challenge=!!document.querySelector('form[action*="/sorry/"],#captcha-form,iframe[src*="recaptcha"]')||/unusual traffic|not a robot|captcha|verifica.{0,30}(attivit|identit)|traffico insolito/.test(body);const out=[],seen=new Set();for(const h of document.querySelectorAll('a h3')){const a=h.closest('a');if(!a)continue;let href=a.href||'';try{const u=new URL(href,location.href);if(u.hostname.includes('google.')&&u.pathname==='/url')href=u.searchParams.get('q')||u.searchParams.get('url')||href}catch(_){}if(!/^https?:\/\//i.test(href)||/google\.[^/]+\/search/i.test(href)||seen.has(href))continue;seen.add(href);const block=h.closest('div.MjjYud,div.g')||a.parentElement?.parentElement||a.parentElement,snippet=block?.querySelector?.('.VwiC3b,.IsZvec,.aCOpRe')?.innerText||'';out.push({title:(h.innerText||'').trim(),url:href,snippet:snippet.trim()});if(out.length>=10)break}return{challenge,title:document.title,results:out}}
function scoreResult(r,seed){const text=norm([r.title,r.snippet,r.url].join(' ')),person=norm(seed.advertiser_name),municipality=norm(seed.municipality),street=norm(seed.street),listing=norm(seed.external_listing_id||seed.reference_code);let score=0;if(listing&&text.includes(listing))score+=5;if(person&&text.includes(person))score+=3;if(municipality&&text.includes(municipality))score+=2;if(street&&text.includes(street))score+=2;if(/immobiliar|real estate|agenzia|vendita|casa|appartamento|villa|terratetto/.test(text))score++;return score}
async function googleQuery(job,q){const url='https://www.google.com/search?hl=it&num=10&q='+encodeURIComponent(q.query),tab=await chrome.tabs.create({url,active:false});try{await waitForTab(tab.id);const exec=await chrome.scripting.executeScript({target:{tabId:tab.id},func:scrapeGooglePage}),data=exec?.[0]?.result||{challenge:false,results:[]};if(data.challenge){await patchJob(job.id,{status:'GOOGLE_VERIFICATION_REQUIRED',current_query:q.query,error:'GOOGLE_VERIFICATION_REQUIRED'});await notify('F1 · VERIFICA GOOGLE RICHIESTA','Apri il CRM: la ricerca è stata fermata senza tentare di aggirare il controllo.');return{verification:true,results:[]}}return{verification:false,results:(data.results||[]).map(r=>({...r,query:q.query,domain:hostOf(r.url),relevance:scoreResult(r,job.seed||{})>=3?'USEFUL':'TO_REVIEW'}))}}finally{await chrome.tabs.remove(tab.id).catch(()=>{})}}
async function saveResults(job,q,found){const existing=await rest('research_results?job_id=eq.'+encodeURIComponent(job.id)+'&select=*')||[],byUrl=new Map(existing.map(r=>[canonicalUrl(r.canonical_url||r.url),r]));for(const r of found){const url=canonicalUrl(r.url);if(!url)continue;const old=byUrl.get(url),stamp=now();if(old){const evidence=Array.isArray(old.query_evidence)?old.query_evidence:[],next=[...evidence];if(!next.some(x=>x?.query===q.query))next.push({query:q.query,title:r.title,snippet:r.snippet,seen_at:stamp});const rows=await rest('research_results?id=eq.'+encodeURIComponent(old.id),{method:'PATCH',body:JSON.stringify({title:old.title||r.title,snippet:old.snippet||r.snippet,domain:old.domain||r.domain,relevance:old.relevance==='USEFUL'||r.relevance==='USEFUL'?'USEFUL':'TO_REVIEW',query_evidence:next,last_seen_at:stamp,updated_at:stamp}),prefer:'return=representation'});byUrl.set(url,rows?.[0]||old)}else{const row={id:crypto.randomUUID(),job_id:job.id,market_listing_id:job.market_listing_id,query:q.query,title:r.title,url:r.url,canonical_url:url,snippet:r.snippet,domain:r.domain,result_type:'GOOGLE_RESULT',relevance:r.relevance,extracted:{},query_evidence:[{query:q.query,title:r.title,snippet:r.snippet,seen_at:stamp}],first_seen_at:stamp,last_seen_at:stamp,created_at:stamp,updated_at:stamp},rows=await rest('research_results',{method:'POST',body:JSON.stringify([row]),prefer:'return=representation'});byUrl.set(url,rows?.[0]||row)}}return byUrl.size}
async function finishQuery(job,q,resultCount){const done=completedSet(job);done.add(q.id);const count=[...done].length;return patchJob(job.id,{current_query:q.query,completed_queries:[...done],queries_completed:count,results_found:resultCount,status:'RUNNING'})}
function scrapePublicPage(){const text=(document.body?.innerText||'').replace(/\s+/g,' ').trim().slice(0,160000),links=[...document.querySelectorAll('a[href]')].slice(0,600).map(a=>a.href).filter(Boolean);return{title:document.title||'',url:location.href,text,links}}
function emailsFrom(page){const found=new Set(),rx=/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,24}\b/ig;for(const m of page.text.matchAll(rx))found.add(m[0].toLowerCase());for(const u of page.links||[])if(/^mailto:/i.test(u)){const v=u.replace(/^mailto:/i,'').split('?')[0].trim().toLowerCase();if(v)found.add(v)}return[...found].filter(v=>!/@example\.|@example$/i.test(v)).slice(0,12)}
function phonesFrom(text){const found=new Map(),rx=/(?:\+?39[\s.-]*)?(?:0\d{1,3}|3\d{2})(?:[\s./-]*\d{2,4}){2,4}/g;for(const m of String(text||'').matchAll(rx)){const raw=c(m[0]),n=normalizePhone(raw);if(n&&!found.has(n))found.set(n,raw)}return[...found].map(([normalized,raw])=>({raw,normalized})).slice(0,12)}
function socialsFrom(links){const out={facebook_url:'',instagram_url:'',linkedin_url:''};for(const u of links||[]){const h=hostOf(u);if(!out.facebook_url&&sameHostOrSub(h,'facebook.com'))out.facebook_url=u;if(!out.instagram_url&&sameHostOrSub(h,'instagram.com'))out.instagram_url=u;if(!out.linkedin_url&&sameHostOrSub(h,'linkedin.com'))out.linkedin_url=u}return out}
function websiteFrom(page){const h=hostOf(page.url);return h&&!PORTAL_DOMAINS.has(h)&&![...SOCIAL_DOMAINS].some(x=>sameHostOrSub(h,x))?page.url:''}
function nearPersonText(text,name){const n=norm(text),needle=norm(name),i=needle?n.indexOf(needle):-1;if(i<0)return'';return text.slice(Math.max(0,i-500),Math.min(text.length,i+needle.length+700))}
function findAgencyName(page){const title=c(page.title).split(/\s[|·–—-]\s/)[0],candidates=[];const rx=/\b([A-ZÀ-Ý][A-Za-zÀ-ÿ0-9 &'’.-]{1,58}\s+(?:Immobiliare|Real Estate))\b/g;for(const m of page.text.slice(0,30000).matchAll(rx))candidates.push(c(m[1]));if(/immobiliare|real estate|agenzia/i.test(title)&&title.length<=80)candidates.unshift(title);return candidates.find(x=>x.length>3&&x.length<90)||''}
function entityKey(type,name,org,phone,email){const base=[type,norm(name),norm(org),normalizePhone(phone),normalizeEmail(email)].filter(Boolean).join('|');let h=2166136261;for(const ch of base){h^=ch.charCodeAt(0);h=Math.imul(h,16777619)}return type.toLowerCase()+':'+(h>>>0).toString(36)}
function contactNearName(page,name){const chunk=nearPersonText(page.text,name),phones=phonesFrom(chunk),emails=emailsFrom({text:chunk,links:page.links.filter(u=>/^mailto:/i.test(u))});return{phone:phones[0]||null,email:emails[0]||''}}
function parsePublicPage(page,seed,result){const textNorm=norm(page.text),person=c(seed.advertiser_name),personMatch=person&&textNorm.includes(norm(person)),realEstate=/immobiliar|real estate|agenzia immobiliare/.test(textNorm),municipality=c(seed.municipality),street=c(seed.street),locationMatch=(!municipality||textNorm.includes(norm(municipality)))||(!street||textNorm.includes(norm(street))),agency=findAgencyName(page),host=hostOf(page.url),ownDomain=!!host&&!PORTAL_DOMAINS.has(host)&&![...SOCIAL_DOMAINS].some(x=>sameHostOrSub(host,x))&&!sameHostOrSub(host,'google.com')&&!sameHostOrSub(host,'google.it'),verified=!!(agency&&personMatch&&realEstate&&locationMatch&&ownDomain),phones=phonesFrom(page.text),emails=emailsFrom(page),social=socialsFrom(page.links),entities=[];if(personMatch){const near=contactNearName(page,person);entities.push({entity_type:'PERSON',name:person,organization:agency,role:realEstate?'REFERENTE IMMOBILIARE PUBBLICO':'RUOLO DA VERIFICARE',phone_raw:near.phone?.raw||'',phone_normalized:near.phone?.normalized||'',email:near.email,email_normalized:normalizeEmail(near.email),pec:'',website:agency&&ownDomain?page.url:'',...social,verification_status:verified?'VERIFICATO':'DA_VERIFICARE',source_urls:[page.url],evidence:[{type:'PUBLIC_PAGE',url:page.url,query:result.query,signals:{person_match:!!personMatch,real_estate:!!realEstate,location_match:!!locationMatch,own_domain:!!ownDomain}}]})}if(agency){const pec=emails.find(x=>/pec\.|\.pec@|@pec\./i.test(x))||'',email=emails.find(x=>x!==pec)||'';entities.push({entity_type:'AGENCY',name:agency,organization:agency,role:'AGENZIA IMMOBILIARE',phone_raw:phones[0]?.raw||'',phone_normalized:phones[0]?.normalized||'',email,email_normalized:normalizeEmail(email),pec,website:ownDomain?page.url:'',...social,verification_status:verified?'VERIFICATO':'DA_VERIFICARE',source_urls:[page.url],evidence:[{type:'PUBLIC_PAGE',url:page.url,query:result.query,signals:{person_match:!!personMatch,real_estate:!!realEstate,location_match:!!locationMatch,own_domain:!!ownDomain}}]})}return{entities,agency,agencyDomain:ownDomain?host:'',verified}}
async function upsertEntity(job,item){const existing=await rest('research_entities?job_id=eq.'+encodeURIComponent(job.id)+'&select=*')||[],phone=normalizePhone(item.phone_normalized||item.phone_raw),email=normalizeEmail(item.email_normalized||item.email),key=entityKey(item.entity_type,item.name,item.organization,phone,email),old=existing.find(x=>x.entity_key===key||(phone&&x.phone_normalized===phone)||(email&&x.email_normalized===email&&String(x.entity_type)===String(item.entity_type))),stamp=now();if(old){const urls=[...new Set([...(Array.isArray(old.source_urls)?old.source_urls:[]),...(item.source_urls||[])])],ev=[...(Array.isArray(old.evidence)?old.evidence:[])];for(const x of item.evidence||[])if(!ev.some(y=>y?.url===x.url&&y?.query===x.query))ev.push(x);const patch={name:old.name||item.name,organization:old.organization||item.organization,role:old.role||item.role,phone_raw:old.phone_raw||item.phone_raw,phone_normalized:old.phone_normalized||phone,email:old.email||item.email,email_normalized:old.email_normalized||email,pec:old.pec||item.pec,website:old.website||item.website,facebook_url:old.facebook_url||item.facebook_url,instagram_url:old.instagram_url||item.instagram_url,linkedin_url:old.linkedin_url||item.linkedin_url,source_urls:urls,evidence:ev,verification_status:old.verification_status==='VERIFICATO'||item.verification_status==='VERIFICATO'?'VERIFICATO':'DA_VERIFICARE',updated_at:stamp};const rows=await rest('research_entities?id=eq.'+encodeURIComponent(old.id),{method:'PATCH',body:JSON.stringify(patch),prefer:'return=representation'});return rows?.[0]||{...old,...patch}}const row={id:crypto.randomUUID(),job_id:job.id,market_listing_id:job.market_listing_id,entity_key:key,...item,phone_normalized:phone,email_normalized:email,created_at:stamp,updated_at:stamp},rows=await rest('research_entities',{method:'POST',body:JSON.stringify([row]),prefer:'return=representation'});return rows?.[0]||row}
function agencyCascade(seed,agency,domain){const out=[],seen=new Set(),add=(priority,query)=>{query=c(query);const k=norm(query);if(!query||seen.has(k))return;seen.add(k);out.push({id:'cascade-'+crypto.randomUUID(),stage:'AGENZIA',priority,kind:'CASCADE',query,status:'PENDING'})},person=c(seed.advertiser_name),municipality=c(seed.municipality),name=c(agency);add(5,quote(name));if(municipality)add(6,`${quote(name)} ${quote(municipality)}`);if(person)add(7,`${quote(person)} ${quote(name)}`);if(domain&&person)add(8,`site:${domain} ${quote(person)}`);for(const term of ['telefono','email','Instagram','Facebook'])add(9,`${quote(name)} ${term}`);return out}
async function classifyVerifiedAgency(job,agency){const rows=await rest('leads?lead_id=eq.'+encodeURIComponent(job.market_listing_id)+'&select=*')||[],lead=rows[0];if(!lead)return;const m=lead.market_data&&typeof lead.market_data==='object'?lead.market_data:{};await rest('leads?lead_id=eq.'+encodeURIComponent(job.market_listing_id),{method:'PATCH',body:JSON.stringify({source_type:'COMPETITOR_LISTING',competitor_agency:agency,lead_reason:'COMPETITOR_LISTING',status:'MONITORAGGIO_CONCORRENZA',market_data:{...m,agency_name:agency,classification:'COMPETITOR_LISTING',research_status:'RUNNING'},updated_at:now()}),prefer:'return=representation'})}
async function analyzeOne(job){const dossier=job.dossier&&typeof job.dossier==='object'?job.dossier:{},analyzed=new Set(Array.isArray(dossier.analyzed_urls)?dossier.analyzed_urls:[]),results=await rest('research_results?job_id=eq.'+encodeURIComponent(job.id)+'&select=*&order=relevance.asc,updated_at.desc')||[],candidates=results.filter(r=>{const h=hostOf(r.url);return r.url&&!analyzed.has(canonicalUrl(r.url))&&h&&!sameHostOrSub(h,'google.com')&&!sameHostOrSub(h,'google.it')&&![...SOCIAL_DOMAINS].some(x=>sameHostOrSub(h,x))}).slice(0,9);const result=candidates[0];if(!result)return finalize(job);let tab=null;try{tab=await chrome.tabs.create({url:result.url,active:false});await waitForTab(tab.id,25000);const exec=await chrome.scripting.executeScript({target:{tabId:tab.id},func:scrapePublicPage}),page=exec?.[0]?.result;if(page?.text&&page.text.length>80){const parsed=parsePublicPage(page,job.seed||{},result),saved=[];for(const item of parsed.entities)saved.push(await upsertEntity(job,item));const verifiedAgency=saved.find(x=>x.entity_type==='AGENCY'&&x.verification_status==='VERIFICATO');if(verifiedAgency&&!dossier.agency_cascade){const plan=Array.isArray(job.query_plan)?[...job.query_plan]:[],existing=new Set(plan.map(x=>norm(x.query))),extra=agencyCascade(job.seed||{},verifiedAgency.organization||verifiedAgency.name,parsed.agencyDomain).filter(x=>!existing.has(norm(x.query))),room=Math.max(0,36-plan.length),added=extra.slice(0,room);if(added.length){plan.push(...added);await classifyVerifiedAgency(job,verifiedAgency.organization||verifiedAgency.name);const nextD={...dossier,agency_cascade:true,agency_name:verifiedAgency.organization||verifiedAgency.name,agency_domain:parsed.agencyDomain,analyzed_urls:[...analyzed,canonicalUrl(result.url)]};await patchJob(job.id,{status:'RUNNING',query_plan:plan,queries_total:plan.length,dossier:nextD,useful_references:(await rest('research_entities?job_id=eq.'+encodeURIComponent(job.id)+'&select=id')||[]).length});scheduleNext(5000);return}}}analyzed.add(canonicalUrl(result.url));await patchJob(job.id,{status:'ANALYZING',dossier:{...dossier,analyzed_urls:[...analyzed]},useful_references:(await rest('research_entities?job_id=eq.'+encodeURIComponent(job.id)+'&select=id')||[]).length});scheduleNext(7000)}catch(e){analyzed.add(canonicalUrl(result.url));await patchJob(job.id,{status:'ANALYZING',dossier:{...dossier,analyzed_urls:[...analyzed],page_errors:[...(Array.isArray(dossier.page_errors)?dossier.page_errors:[]),{url:result.url,error:String(e.message||e).slice(0,160)}].slice(-20)}});scheduleNext(9000)}finally{if(tab?.id)await chrome.tabs.remove(tab.id).catch(()=>{})}}
async function finalize(job){const [results,entities]=await Promise.all([rest('research_results?job_id=eq.'+encodeURIComponent(job.id)+'&select=*')||[],rest('research_entities?job_id=eq.'+encodeURIComponent(job.id)+'&select=*')||[]]),verifiedAgency=entities.find(x=>x.entity_type==='AGENCY'&&x.verification_status==='VERIFICATO'),plan=Array.isArray(job.query_plan)?job.query_plan:[],territoryQueries=new Set(plan.filter(x=>x.stage==='TERRITORIO').map(x=>x.query)),territory=results.filter(r=>territoryQueries.has(r.query)&&r.relevance==='USEFUL').slice(0,5),status=results.length?'COMPLETED':'PARTIAL',dossier={...(job.dossier||{}),agency_name:verifiedAgency?.organization||verifiedAgency?.name||job.dossier?.agency_name||'',territory_summary:territory.length?territory.map(x=>x.title).filter(Boolean).join(' · '):'',source_count:results.length,entity_count:entities.length,engine_version:VERSION};await patchJob(job.id,{status,completed_at:now(),current_query:'',results_found:results.length,useful_references:entities.length,dossier,error:status==='PARTIAL'?'Ricerca completata senza risultati pubblici utili.':''});const leads=await rest('leads?lead_id=eq.'+encodeURIComponent(job.market_listing_id)+'&select=market_data')||[],m=leads[0]?.market_data&&typeof leads[0].market_data==='object'?leads[0].market_data:{};await rest('leads?lead_id=eq.'+encodeURIComponent(job.market_listing_id),{method:'PATCH',body:JSON.stringify({market_data:{...m,research_status:status,research_completed_at:now(),research_job_id:job.id},updated_at:now()}),prefer:'return=representation'}).catch(()=>{});await notify('F1 · DOSSIER GOOGLE PRONTO',[(job.seed?.street||''),(job.seed?.municipality||''),verifiedAgency?'Agenzia: '+(verifiedAgency.organization||verifiedAgency.name):''].filter(Boolean).join(' · ')||'Ricerca completata')}
async function processJob(job){job=await claimJob(job);if(job.status==='RUNNING'){const q=pendingQuery(job);if(!q){await patchJob(job.id,{status:'ANALYZING',current_query:''});scheduleNext(3000);return}await patchJob(job.id,{current_query:q.query,status:'RUNNING'});const found=await googleQuery(job,q);if(found.verification)return;const count=await saveResults(job,q,found.results);await finishQuery(job,q,count);scheduleNext(9000+Math.floor(Math.random()*6000));return}if(job.status==='ANALYZING'){await analyzeOne(job)}}
async function tick(){if(running)return;running=true;try{if(!(await session()))return;const job=await getCandidateJob();if(!job)return;await processJob(job)}catch(e){console.warn('F1 Companion',e);if(!/SESSIONE_F1/.test(String(e.message||'')))scheduleNext(30000)}finally{running=false}}
chrome.runtime.onMessage.addListener((msg,_sender,sendResponse)=>{if(msg?.type==='F1_SESSION_SYNC'&&msg.session){saveSession(msg.session).then(()=>{sendResponse({ok:true,version:VERSION});tick()}).catch(e=>sendResponse({ok:false,error:e.message}));return true}});
chrome.alarms.onAlarm.addListener(a=>{if(a.name===ALARM_POLL||a.name===ALARM_NEXT)tick()});
chrome.runtime.onInstalled.addListener(()=>{chrome.alarms.create(ALARM_POLL,{periodInMinutes:1});tick()});
chrome.runtime.onStartup.addListener(()=>{chrome.alarms.create(ALARM_POLL,{periodInMinutes:1});tick()});
chrome.alarms.create(ALARM_POLL,{periodInMinutes:1});
tick();
