#!/usr/bin/env python3
from pathlib import Path

p = Path('telefonate-oggi.html')
s = p.read_text(encoding='utf-8')
old = "function niRenderSignal(s,compact=false){let ctx=s.context||{},ents=s.public_entities||[],cats={};ents.forEach(e=>cats[e.category]=(cats[e.category]||0)+1);let catBadges=Object.entries(cats).map(([k,v])=>`<span class=\"ni-badge\">${niEsc(k)} ${v}</span>`).join('');let qs=s.queries||{};return `<div class=\"ni-grid\"><div class=\"ni-kpi\">COMUNE<b>${niEsc(s.comune)}</b></div><div class=\"ni-kpi\">INDIRIZZO<b>${niEsc(s.indirizzo)}</b></div><div class=\"ni-kpi\">EDIFICI RESIDENZIALI OSM / ${niEsc(s.radius_m||500)}m<b>${niEsc(ctx.residential_buildings_osm??'—')}</b></div><div class=\"ni-kpi\">ATTIVITÀ / ENTI PUBBLICI<b>${niEsc(ctx.public_entities_count??ents.length??0)}</b></div></div><div>${catBadges||'<span class=\"ni-badge\">ARRICCHIMENTO '+niEsc(s.enrichment_status||'PENDING')+'</span>'}</div><div class=\"ni-links\">${s.url_annuncio?`<a class=\"btn alt\" target=\"_blank\" rel=\"noopener\" href=\"${niEsc(s.url_annuncio)}\">ANNUNCIO</a>`:''}${qs.google_maps?`<a class=\"btn alt\" target=\"_blank\" rel=\"noopener\" href=\"${niEsc(qs.google_maps)}\">MAPS</a>`:''}${qs.attivita_vicine?`<a class=\"btn alt\" target=\"_blank\" rel=\"noopener\" href=\"${niEsc(qs.attivita_vicine)}\">ATTIVITÀ VICINE</a>`:''}${qs.territorio?`<a class=\"btn alt\" target=\"_blank\" rel=\"noopener\" href=\"${niEsc(qs.territorio)}\">LEGAMI TERRITORIO</a>`:''}${qs.animali_agricoltura?`<a class=\"btn alt\" target=\"_blank\" rel=\"noopener\" href=\"${niEsc(qs.animali_agricoltura)}\">ANIMALI / AGRICOLTURA</a>`:''}</div>${ents.length?`<div class=\"ni-entities\">${ents.slice(0,compact?4:12).map(niEntity).join('')}</div>`:`<div class=\"empty\">Nessuna attività/ente ancora arricchito per questo segnale. Il segnale resta comunque in lista.</div>`}` }"
new = "function niRenderSignal(s,compact=false){let ctx=s.context||{},ents=[...(s.public_entities||[])],cats={};ents.forEach(e=>cats[e.category]=(cats[e.category]||0)+1);let catBadges=Object.entries(cats).map(([k,v])=>`<span class=\"ni-badge\">${niEsc(k)} ${v}</span>`).join('');let qs=s.queries||{};ents.sort((a,b)=>{let ap=(a.phone_public?3:0)+(a.email_public?2:0)+(a.website?1:0),bp=(b.phone_public?3:0)+(b.email_public?2:0)+(b.website?1:0);return bp-ap||String(a.name||'').localeCompare(String(b.name||''),'it')});let useful=ents.filter(e=>e.phone_public||e.email_public||e.website).length;let limit=compact?8:ents.length;return `<div class=\"ni-grid\"><div class=\"ni-kpi\">COMUNE<b>${niEsc(s.comune)}</b></div><div class=\"ni-kpi\">INDIRIZZO<b>${niEsc(s.indirizzo)}</b></div><div class=\"ni-kpi\">EDIFICI RESIDENZIALI OSM / ${niEsc(s.radius_m||500)}m<b>${niEsc(ctx.residential_buildings_osm??'—')}</b></div><div class=\"ni-kpi\">ATTIVITÀ / ENTI PUBBLICI<b>${niEsc(ctx.public_entities_count??ents.length??0)}</b></div></div><div><span class=\"ni-badge\">RIFERIMENTI CON RECAPITO ${useful}</span>${catBadges}</div><div class=\"ni-links\">${s.url_annuncio?`<a class=\"btn alt\" target=\"_blank\" rel=\"noopener\" href=\"${niEsc(s.url_annuncio)}\">ANNUNCIO</a>`:''}${qs.google_maps?`<a class=\"btn alt\" target=\"_blank\" rel=\"noopener\" href=\"${niEsc(qs.google_maps)}\">MAPS</a>`:''}${qs.attivita_vicine?`<a class=\"btn alt\" target=\"_blank\" rel=\"noopener\" href=\"${niEsc(qs.attivita_vicine)}\">ATTIVITÀ VICINE</a>`:''}${qs.territorio?`<a class=\"btn alt\" target=\"_blank\" rel=\"noopener\" href=\"${niEsc(qs.territorio)}\">LEGAMI TERRITORIO</a>`:''}${qs.animali_agricoltura?`<a class=\"btn alt\" target=\"_blank\" rel=\"noopener\" href=\"${niEsc(qs.animali_agricoltura)}\">ANIMALI / AGRICOLTURA</a>`:''}</div>${ents.length?`<div class=\"ni-entities\">${ents.slice(0,limit).map(niEntity).join('')}</div>`:`<div class=\"empty\">Nessuna attività/ente ancora arricchito per questo segnale. Il segnale resta comunque in lista.</div>`}` }"
if old not in s:
    raise SystemExit('Target niRenderSignal non trovato')
s=s.replace(old,new,1)
p.write_text(s,encoding='utf-8')
print('PATCH OK: riferimenti con recapito prioritari')
